/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GenerateMfaBackupCodes200Response,
  GenerateMfaBackupCodesRequest,
  GetChallenge200Response,
  GetChallenge500Response,
  GetCsrfToken200Response,
  ListUserMemberships200ResponseInner,
  LoginWithPasswordRequest,
  Logout401Response,
  Logout403Response,
  RequestLoginCode200Response,
  RequestLoginCode400Response,
  RequestLoginCode429Response,
  RequestLoginCodeRequest,
  RequestMfaSetup200Response,
  RequestMfaSetup409Response,
  RequestRegistrationRequest,
  SwitchMembership200Response,
  SwitchMembership404Response,
  SwitchMembershipRequest,
  VerifyAccountRecoveryRequest,
  VerifyLoginCode200Response,
  VerifyLoginCode202Response,
  VerifyLoginCodeRequest,
  VerifyMfaChallengeRequest,
  VerifyMfaSetupRequest,
  VerifyRegistration200Response,
  VerifyRegistrationRequest,
} from '../models/index';
import {
    GenerateMfaBackupCodes200ResponseFromJSON,
    GenerateMfaBackupCodes200ResponseToJSON,
    GenerateMfaBackupCodesRequestFromJSON,
    GenerateMfaBackupCodesRequestToJSON,
    GetChallenge200ResponseFromJSON,
    GetChallenge200ResponseToJSON,
    GetChallenge500ResponseFromJSON,
    GetChallenge500ResponseToJSON,
    GetCsrfToken200ResponseFromJSON,
    GetCsrfToken200ResponseToJSON,
    ListUserMemberships200ResponseInnerFromJSON,
    ListUserMemberships200ResponseInnerToJSON,
    LoginWithPasswordRequestFromJSON,
    LoginWithPasswordRequestToJSON,
    Logout401ResponseFromJSON,
    Logout401ResponseToJSON,
    Logout403ResponseFromJSON,
    Logout403ResponseToJSON,
    RequestLoginCode200ResponseFromJSON,
    RequestLoginCode200ResponseToJSON,
    RequestLoginCode400ResponseFromJSON,
    RequestLoginCode400ResponseToJSON,
    RequestLoginCode429ResponseFromJSON,
    RequestLoginCode429ResponseToJSON,
    RequestLoginCodeRequestFromJSON,
    RequestLoginCodeRequestToJSON,
    RequestMfaSetup200ResponseFromJSON,
    RequestMfaSetup200ResponseToJSON,
    RequestMfaSetup409ResponseFromJSON,
    RequestMfaSetup409ResponseToJSON,
    RequestRegistrationRequestFromJSON,
    RequestRegistrationRequestToJSON,
    SwitchMembership200ResponseFromJSON,
    SwitchMembership200ResponseToJSON,
    SwitchMembership404ResponseFromJSON,
    SwitchMembership404ResponseToJSON,
    SwitchMembershipRequestFromJSON,
    SwitchMembershipRequestToJSON,
    VerifyAccountRecoveryRequestFromJSON,
    VerifyAccountRecoveryRequestToJSON,
    VerifyLoginCode200ResponseFromJSON,
    VerifyLoginCode200ResponseToJSON,
    VerifyLoginCode202ResponseFromJSON,
    VerifyLoginCode202ResponseToJSON,
    VerifyLoginCodeRequestFromJSON,
    VerifyLoginCodeRequestToJSON,
    VerifyMfaChallengeRequestFromJSON,
    VerifyMfaChallengeRequestToJSON,
    VerifyMfaSetupRequestFromJSON,
    VerifyMfaSetupRequestToJSON,
    VerifyRegistration200ResponseFromJSON,
    VerifyRegistration200ResponseToJSON,
    VerifyRegistrationRequestFromJSON,
    VerifyRegistrationRequestToJSON,
} from '../models/index';

export interface DisableMfaRequest {
    generateMfaBackupCodesRequest: GenerateMfaBackupCodesRequest;
}

export interface GenerateMfaBackupCodesOperationRequest {
    generateMfaBackupCodesRequest: GenerateMfaBackupCodesRequest;
}

export interface LoginWithPasswordOperationRequest {
    loginWithPasswordRequest: LoginWithPasswordRequest;
}

export interface RequestAccountRecoveryRequest {
    requestLoginCodeRequest: RequestLoginCodeRequest;
}

export interface RequestLoginCodeOperationRequest {
    requestLoginCodeRequest: RequestLoginCodeRequest;
}

export interface RequestRegistrationOperationRequest {
    requestRegistrationRequest: RequestRegistrationRequest;
}

export interface SwitchMembershipOperationRequest {
    switchMembershipRequest: SwitchMembershipRequest;
}

export interface VerifyAccountRecoveryOperationRequest {
    verifyAccountRecoveryRequest: VerifyAccountRecoveryRequest;
}

export interface VerifyLoginCodeOperationRequest {
    verifyLoginCodeRequest: VerifyLoginCodeRequest;
}

export interface VerifyMfaChallengeOperationRequest {
    verifyMfaChallengeRequest: VerifyMfaChallengeRequest;
}

export interface VerifyMfaSetupOperationRequest {
    verifyMfaSetupRequest: VerifyMfaSetupRequest;
}

export interface VerifyRegistrationOperationRequest {
    verifyRegistrationRequest: VerifyRegistrationRequest;
}

/**
 * 
 */
export class AuthClient extends runtime.BaseAPI {

    /**
     * Disables multi-factor authentication for the authenticated user. Requires password confirmation. Clears the TOTP secret and all backup codes.
     * Disable MFA
     */
    async disableMfaRaw(requestParameters: DisableMfaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestLoginCode200Response>> {
        if (requestParameters['generateMfaBackupCodesRequest'] == null) {
            throw new runtime.RequiredError(
                'generateMfaBackupCodesRequest',
                'Required parameter "generateMfaBackupCodesRequest" was null or undefined when calling disableMfa().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/mfa/disable`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GenerateMfaBackupCodesRequestToJSON(requestParameters['generateMfaBackupCodesRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestLoginCode200ResponseFromJSON(jsonValue));
    }

    /**
     * Disables multi-factor authentication for the authenticated user. Requires password confirmation. Clears the TOTP secret and all backup codes.
     * Disable MFA
     */
    async disableMfa(generateMfaBackupCodesRequest: GenerateMfaBackupCodesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestLoginCode200Response> {
        const response = await this.disableMfaRaw({ generateMfaBackupCodesRequest: generateMfaBackupCodesRequest }, initOverrides);
        return await response.value();
    }

    /**
     * Regenerates backup codes for the authenticated user. Requires password confirmation. Replaces all existing backup codes — previous codes will no longer work. Store the new codes securely.
     * Regenerate backup codes
     */
    async generateMfaBackupCodesRaw(requestParameters: GenerateMfaBackupCodesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GenerateMfaBackupCodes200Response>> {
        if (requestParameters['generateMfaBackupCodesRequest'] == null) {
            throw new runtime.RequiredError(
                'generateMfaBackupCodesRequest',
                'Required parameter "generateMfaBackupCodesRequest" was null or undefined when calling generateMfaBackupCodes().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/mfa/backup-codes`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GenerateMfaBackupCodesRequestToJSON(requestParameters['generateMfaBackupCodesRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GenerateMfaBackupCodes200ResponseFromJSON(jsonValue));
    }

    /**
     * Regenerates backup codes for the authenticated user. Requires password confirmation. Replaces all existing backup codes — previous codes will no longer work. Store the new codes securely.
     * Regenerate backup codes
     */
    async generateMfaBackupCodes(generateMfaBackupCodesRequest: GenerateMfaBackupCodesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GenerateMfaBackupCodes200Response> {
        const response = await this.generateMfaBackupCodesRaw({ generateMfaBackupCodesRequest: generateMfaBackupCodesRequest }, initOverrides);
        return await response.value();
    }

    /**
     * Returns a proof-of-work challenge that must be solved before submitting registration or login requests.
     * Get an ALTCHA challenge
     */
    async getChallengeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetChallenge200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/challenge`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetChallenge200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns a proof-of-work challenge that must be solved before submitting registration or login requests.
     * Get an ALTCHA challenge
     */
    async getChallenge(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetChallenge200Response> {
        const response = await this.getChallengeRaw(initOverrides);
        return await response.value();
    }

    /**
     * Generates a CSRF token tied to the current session. The token must be sent in the `x-csrf-token` header on all state-changing requests.
     * Get a CSRF token
     */
    async getCsrfTokenRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetCsrfToken200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/csrf`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetCsrfToken200ResponseFromJSON(jsonValue));
    }

    /**
     * Generates a CSRF token tied to the current session. The token must be sent in the `x-csrf-token` header on all state-changing requests.
     * Get a CSRF token
     */
    async getCsrfToken(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetCsrfToken200Response> {
        const response = await this.getCsrfTokenRaw(initOverrides);
        return await response.value();
    }

    /**
     * Returns all memberships of the authenticated user across all organisations. Used for organisation switching and profile display.
     * List user memberships
     */
    async listUserMembershipsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ListUserMemberships200ResponseInner>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/memberships/list`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ListUserMemberships200ResponseInnerFromJSON));
    }

    /**
     * Returns all memberships of the authenticated user across all organisations. Used for organisation switching and profile display.
     * List user memberships
     */
    async listUserMemberships(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ListUserMemberships200ResponseInner>> {
        const response = await this.listUserMembershipsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Authenticates a user with their email and password. Returns 202 with an MFA token if multi-factor authentication is enabled. Requires a valid ALTCHA solution. Rate limited to 10 attempts per 15 minutes.
     * Log in with email and password
     */
    async loginWithPasswordRaw(requestParameters: LoginWithPasswordOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VerifyLoginCode200Response>> {
        if (requestParameters['loginWithPasswordRequest'] == null) {
            throw new runtime.RequiredError(
                'loginWithPasswordRequest',
                'Required parameter "loginWithPasswordRequest" was null or undefined when calling loginWithPassword().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/login/password`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginWithPasswordRequestToJSON(requestParameters['loginWithPasswordRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VerifyLoginCode200ResponseFromJSON(jsonValue));
    }

    /**
     * Authenticates a user with their email and password. Returns 202 with an MFA token if multi-factor authentication is enabled. Requires a valid ALTCHA solution. Rate limited to 10 attempts per 15 minutes.
     * Log in with email and password
     */
    async loginWithPassword(loginWithPasswordRequest: LoginWithPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VerifyLoginCode200Response> {
        const response = await this.loginWithPasswordRaw({ loginWithPasswordRequest: loginWithPasswordRequest }, initOverrides);
        return await response.value();
    }

    /**
     * Destroys the current session, removing it from the session store and clearing session tracking indexes.
     * Log out
     */
    async logoutRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/logout`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Destroys the current session, removing it from the session store and clearing session tracking indexes.
     * Log out
     */
    async logout(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.logoutRaw(initOverrides);
    }

    /**
     * Sends a password recovery code to the specified email address. Always returns 200 to avoid leaking whether the email exists. Rate limited to 5 attempts per 5 minutes.
     * Request password recovery
     */
    async requestAccountRecoveryRaw(requestParameters: RequestAccountRecoveryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestLoginCode200Response>> {
        if (requestParameters['requestLoginCodeRequest'] == null) {
            throw new runtime.RequiredError(
                'requestLoginCodeRequest',
                'Required parameter "requestLoginCodeRequest" was null or undefined when calling requestAccountRecovery().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/recover/request`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RequestLoginCodeRequestToJSON(requestParameters['requestLoginCodeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestLoginCode200ResponseFromJSON(jsonValue));
    }

    /**
     * Sends a password recovery code to the specified email address. Always returns 200 to avoid leaking whether the email exists. Rate limited to 5 attempts per 5 minutes.
     * Request password recovery
     */
    async requestAccountRecovery(requestLoginCodeRequest: RequestLoginCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestLoginCode200Response> {
        const response = await this.requestAccountRecoveryRaw({ requestLoginCodeRequest: requestLoginCodeRequest }, initOverrides);
        return await response.value();
    }

    /**
     * Sends a one-time login code to the specified email address. Always returns 200 to avoid leaking whether the email exists. Rate limited to 5 attempts per 5 minutes.
     * Request a login code
     */
    async requestLoginCodeRaw(requestParameters: RequestLoginCodeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestLoginCode200Response>> {
        if (requestParameters['requestLoginCodeRequest'] == null) {
            throw new runtime.RequiredError(
                'requestLoginCodeRequest',
                'Required parameter "requestLoginCodeRequest" was null or undefined when calling requestLoginCode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/login/code/request`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RequestLoginCodeRequestToJSON(requestParameters['requestLoginCodeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestLoginCode200ResponseFromJSON(jsonValue));
    }

    /**
     * Sends a one-time login code to the specified email address. Always returns 200 to avoid leaking whether the email exists. Rate limited to 5 attempts per 5 minutes.
     * Request a login code
     */
    async requestLoginCode(requestLoginCodeRequest: RequestLoginCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestLoginCode200Response> {
        const response = await this.requestLoginCodeRaw({ requestLoginCodeRequest: requestLoginCodeRequest }, initOverrides);
        return await response.value();
    }

    /**
     * Generates a TOTP secret and provisioning URI for MFA setup. The secret is stored on the user but MFA is not enabled until verified via /auth/mfa/setup/verify. Returns 409 if MFA is already enabled.
     * Request MFA setup
     */
    async requestMfaSetupRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestMfaSetup200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/mfa/setup/request`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestMfaSetup200ResponseFromJSON(jsonValue));
    }

    /**
     * Generates a TOTP secret and provisioning URI for MFA setup. The secret is stored on the user but MFA is not enabled until verified via /auth/mfa/setup/verify. Returns 409 if MFA is already enabled.
     * Request MFA setup
     */
    async requestMfaSetup(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestMfaSetup200Response> {
        const response = await this.requestMfaSetupRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates a new user account, organisation, and owner membership. Sends a verification code via email. Requires a valid ALTCHA solution. Rate limited to 5 attempts per hour.
     * Register a new account
     */
    async requestRegistrationRaw(requestParameters: RequestRegistrationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestLoginCode200Response>> {
        if (requestParameters['requestRegistrationRequest'] == null) {
            throw new runtime.RequiredError(
                'requestRegistrationRequest',
                'Required parameter "requestRegistrationRequest" was null or undefined when calling requestRegistration().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/register/request`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RequestRegistrationRequestToJSON(requestParameters['requestRegistrationRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestLoginCode200ResponseFromJSON(jsonValue));
    }

    /**
     * Creates a new user account, organisation, and owner membership. Sends a verification code via email. Requires a valid ALTCHA solution. Rate limited to 5 attempts per hour.
     * Register a new account
     */
    async requestRegistration(requestRegistrationRequest: RequestRegistrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestLoginCode200Response> {
        const response = await this.requestRegistrationRaw({ requestRegistrationRequest: requestRegistrationRequest }, initOverrides);
        return await response.value();
    }

    /**
     * Switches the active membership to a different organisation. The user must be a member of the target organisation.
     * Switch active membership
     */
    async switchMembershipRaw(requestParameters: SwitchMembershipOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SwitchMembership200Response>> {
        if (requestParameters['switchMembershipRequest'] == null) {
            throw new runtime.RequiredError(
                'switchMembershipRequest',
                'Required parameter "switchMembershipRequest" was null or undefined when calling switchMembership().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/memberships/switch`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SwitchMembershipRequestToJSON(requestParameters['switchMembershipRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SwitchMembership200ResponseFromJSON(jsonValue));
    }

    /**
     * Switches the active membership to a different organisation. The user must be a member of the target organisation.
     * Switch active membership
     */
    async switchMembership(switchMembershipRequest: SwitchMembershipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SwitchMembership200Response> {
        const response = await this.switchMembershipRaw({ switchMembershipRequest: switchMembershipRequest }, initOverrides);
        return await response.value();
    }

    /**
     * Resets the password for an account using a recovery code. Revokes all existing sessions after a successful reset. Rate limited to 10 attempts per 15 minutes.
     * Reset password with recovery code
     */
    async verifyAccountRecoveryRaw(requestParameters: VerifyAccountRecoveryOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestLoginCode200Response>> {
        if (requestParameters['verifyAccountRecoveryRequest'] == null) {
            throw new runtime.RequiredError(
                'verifyAccountRecoveryRequest',
                'Required parameter "verifyAccountRecoveryRequest" was null or undefined when calling verifyAccountRecovery().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/recover/verify`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VerifyAccountRecoveryRequestToJSON(requestParameters['verifyAccountRecoveryRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestLoginCode200ResponseFromJSON(jsonValue));
    }

    /**
     * Resets the password for an account using a recovery code. Revokes all existing sessions after a successful reset. Rate limited to 10 attempts per 15 minutes.
     * Reset password with recovery code
     */
    async verifyAccountRecovery(verifyAccountRecoveryRequest: VerifyAccountRecoveryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestLoginCode200Response> {
        const response = await this.verifyAccountRecoveryRaw({ verifyAccountRecoveryRequest: verifyAccountRecoveryRequest }, initOverrides);
        return await response.value();
    }

    /**
     * Completes a code-based login. Returns 202 with an MFA token if multi-factor authentication is enabled. Rate limited to 10 attempts per 15 minutes.
     * Verify login code
     */
    async verifyLoginCodeRaw(requestParameters: VerifyLoginCodeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VerifyLoginCode200Response>> {
        if (requestParameters['verifyLoginCodeRequest'] == null) {
            throw new runtime.RequiredError(
                'verifyLoginCodeRequest',
                'Required parameter "verifyLoginCodeRequest" was null or undefined when calling verifyLoginCode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/login/code/verify`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VerifyLoginCodeRequestToJSON(requestParameters['verifyLoginCodeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VerifyLoginCode200ResponseFromJSON(jsonValue));
    }

    /**
     * Completes a code-based login. Returns 202 with an MFA token if multi-factor authentication is enabled. Rate limited to 10 attempts per 15 minutes.
     * Verify login code
     */
    async verifyLoginCode(verifyLoginCodeRequest: VerifyLoginCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VerifyLoginCode200Response> {
        const response = await this.verifyLoginCodeRaw({ verifyLoginCodeRequest: verifyLoginCodeRequest }, initOverrides);
        return await response.value();
    }

    /**
     * Completes multi-factor authentication using a TOTP code or a one-time backup code. Consumes the MFA token on success. Backup codes are single-use and removed after verification. Rate limited to 10 attempts per 15 minutes.
     * Complete MFA challenge
     */
    async verifyMfaChallengeRaw(requestParameters: VerifyMfaChallengeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VerifyLoginCode200Response>> {
        if (requestParameters['verifyMfaChallengeRequest'] == null) {
            throw new runtime.RequiredError(
                'verifyMfaChallengeRequest',
                'Required parameter "verifyMfaChallengeRequest" was null or undefined when calling verifyMfaChallenge().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/mfa/challenge`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VerifyMfaChallengeRequestToJSON(requestParameters['verifyMfaChallengeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VerifyLoginCode200ResponseFromJSON(jsonValue));
    }

    /**
     * Completes multi-factor authentication using a TOTP code or a one-time backup code. Consumes the MFA token on success. Backup codes are single-use and removed after verification. Rate limited to 10 attempts per 15 minutes.
     * Complete MFA challenge
     */
    async verifyMfaChallenge(verifyMfaChallengeRequest: VerifyMfaChallengeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VerifyLoginCode200Response> {
        const response = await this.verifyMfaChallengeRaw({ verifyMfaChallengeRequest: verifyMfaChallengeRequest }, initOverrides);
        return await response.value();
    }

    /**
     * Completes MFA setup by verifying a TOTP code from the user\'s authenticator app. On success, enables MFA and returns a set of one-time backup codes. Store these codes securely — they cannot be retrieved again.
     * Verify MFA setup
     */
    async verifyMfaSetupRaw(requestParameters: VerifyMfaSetupOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GenerateMfaBackupCodes200Response>> {
        if (requestParameters['verifyMfaSetupRequest'] == null) {
            throw new runtime.RequiredError(
                'verifyMfaSetupRequest',
                'Required parameter "verifyMfaSetupRequest" was null or undefined when calling verifyMfaSetup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/mfa/setup/verify`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VerifyMfaSetupRequestToJSON(requestParameters['verifyMfaSetupRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GenerateMfaBackupCodes200ResponseFromJSON(jsonValue));
    }

    /**
     * Completes MFA setup by verifying a TOTP code from the user\'s authenticator app. On success, enables MFA and returns a set of one-time backup codes. Store these codes securely — they cannot be retrieved again.
     * Verify MFA setup
     */
    async verifyMfaSetup(verifyMfaSetupRequest: VerifyMfaSetupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GenerateMfaBackupCodes200Response> {
        const response = await this.verifyMfaSetupRaw({ verifyMfaSetupRequest: verifyMfaSetupRequest }, initOverrides);
        return await response.value();
    }

    /**
     * Verifies a newly registered account using the code sent via email. On success, creates a session.
     * Verify registration
     */
    async verifyRegistrationRaw(requestParameters: VerifyRegistrationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VerifyRegistration200Response>> {
        if (requestParameters['verifyRegistrationRequest'] == null) {
            throw new runtime.RequiredError(
                'verifyRegistrationRequest',
                'Required parameter "verifyRegistrationRequest" was null or undefined when calling verifyRegistration().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/register/verify`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VerifyRegistrationRequestToJSON(requestParameters['verifyRegistrationRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VerifyRegistration200ResponseFromJSON(jsonValue));
    }

    /**
     * Verifies a newly registered account using the code sent via email. On success, creates a session.
     * Verify registration
     */
    async verifyRegistration(verifyRegistrationRequest: VerifyRegistrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VerifyRegistration200Response> {
        const response = await this.verifyRegistrationRaw({ verifyRegistrationRequest: verifyRegistrationRequest }, initOverrides);
        return await response.value();
    }

}
