/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateDatabase201Response,
  CreateDatabaseRequest,
  GetChallenge500Response,
  ListDatabases200ResponseInner,
  ListDatabasesLimitParameter,
  ListDatabasesOrderParameter,
  ListDatabasesWhereParameter,
  Logout401Response,
  Logout403Response,
  RequestLoginCode400Response,
  RequestMfaSetup409Response,
  SearchDatabasesRequest,
  SwitchMembership404Response,
  UpdateDatabaseRequest,
} from '../models/index';
import {
    CreateDatabase201ResponseFromJSON,
    CreateDatabase201ResponseToJSON,
    CreateDatabaseRequestFromJSON,
    CreateDatabaseRequestToJSON,
    GetChallenge500ResponseFromJSON,
    GetChallenge500ResponseToJSON,
    ListDatabases200ResponseInnerFromJSON,
    ListDatabases200ResponseInnerToJSON,
    ListDatabasesLimitParameterFromJSON,
    ListDatabasesLimitParameterToJSON,
    ListDatabasesOrderParameterFromJSON,
    ListDatabasesOrderParameterToJSON,
    ListDatabasesWhereParameterFromJSON,
    ListDatabasesWhereParameterToJSON,
    Logout401ResponseFromJSON,
    Logout401ResponseToJSON,
    Logout403ResponseFromJSON,
    Logout403ResponseToJSON,
    RequestLoginCode400ResponseFromJSON,
    RequestLoginCode400ResponseToJSON,
    RequestMfaSetup409ResponseFromJSON,
    RequestMfaSetup409ResponseToJSON,
    SearchDatabasesRequestFromJSON,
    SearchDatabasesRequestToJSON,
    SwitchMembership404ResponseFromJSON,
    SwitchMembership404ResponseToJSON,
    UpdateDatabaseRequestFromJSON,
    UpdateDatabaseRequestToJSON,
} from '../models/index';

export interface CreateDatabaseOperationRequest {
    createDatabaseRequest: CreateDatabaseRequest;
}

export interface DeleteDatabaseRequest {
    id: string;
}

export interface GetDatabaseRequest {
    id: string;
}

export interface ListDatabasesRequest {
    limit?: ListDatabasesLimitParameter;
    order?: ListDatabasesOrderParameter;
    select?: Set<ListDatabasesSelectEnum>;
    where?: ListDatabasesWhereParameter;
}

export interface SearchDatabasesOperationRequest {
    searchDatabasesRequest?: SearchDatabasesRequest;
}

export interface UpdateDatabaseOperationRequest {
    id: string;
    updateDatabaseRequest?: UpdateDatabaseRequest;
}

/**
 * 
 */
export class DatabasesClient extends runtime.BaseAPI {

    /**
     * Creates a new database in the current organisation.
     * Create a database
     */
    async createDatabaseRaw(requestParameters: CreateDatabaseOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateDatabase201Response>> {
        if (requestParameters['createDatabaseRequest'] == null) {
            throw new runtime.RequiredError(
                'createDatabaseRequest',
                'Required parameter "createDatabaseRequest" was null or undefined when calling createDatabase().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/databases`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateDatabaseRequestToJSON(requestParameters['createDatabaseRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateDatabase201ResponseFromJSON(jsonValue));
    }

    /**
     * Creates a new database in the current organisation.
     * Create a database
     */
    async createDatabase(createDatabaseRequest: CreateDatabaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateDatabase201Response> {
        const response = await this.createDatabaseRaw({ createDatabaseRequest: createDatabaseRequest }, initOverrides);
        return await response.value();
    }

    /**
     * Permanently deletes a database by its ID. Returns 404 if the database does not exist within the current organisation.
     * Delete a database
     */
    async deleteDatabaseRaw(requestParameters: DeleteDatabaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteDatabase().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/databases/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Permanently deletes a database by its ID. Returns 404 if the database does not exist within the current organisation.
     * Delete a database
     */
    async deleteDatabase(id: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteDatabaseRaw({ id: id }, initOverrides);
    }

    /**
     * Retrieves a single database by its ID.
     * Get a database
     */
    async getDatabaseRaw(requestParameters: GetDatabaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateDatabase201Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getDatabase().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/databases/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateDatabase201ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves a single database by its ID.
     * Get a database
     */
    async getDatabase(id: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateDatabase201Response> {
        const response = await this.getDatabaseRaw({ id: id }, initOverrides);
        return await response.value();
    }

    /**
     * Returns a list of all databases. Supports filtering, pagination, and field selection.
     * List databases
     */
    async listDatabasesRaw(requestParameters: ListDatabasesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ListDatabases200ResponseInner>>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['order'] != null) {
            queryParameters['order'] = requestParameters['order'];
        }

        if (requestParameters['select'] != null) {
            queryParameters['select'] = requestParameters['select'];
        }

        if (requestParameters['where'] != null) {
            queryParameters['where'] = requestParameters['where'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/databases`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ListDatabases200ResponseInnerFromJSON));
    }

    /**
     * Returns a list of all databases. Supports filtering, pagination, and field selection.
     * List databases
     */
    async listDatabases(limit?: ListDatabasesLimitParameter, order?: ListDatabasesOrderParameter, select?: Set<ListDatabasesSelectEnum>, where?: ListDatabasesWhereParameter, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ListDatabases200ResponseInner>> {
        const response = await this.listDatabasesRaw({ limit: limit, order: order, select: select, where: where }, initOverrides);
        return await response.value();
    }

    /**
     * Search all databases with advanced filtering, including nested AND/OR logic and comparison operators.
     * Search databases
     */
    async searchDatabasesRaw(requestParameters: SearchDatabasesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ListDatabases200ResponseInner>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/databases/search`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SearchDatabasesRequestToJSON(requestParameters['searchDatabasesRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ListDatabases200ResponseInnerFromJSON));
    }

    /**
     * Search all databases with advanced filtering, including nested AND/OR logic and comparison operators.
     * Search databases
     */
    async searchDatabases(searchDatabasesRequest?: SearchDatabasesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ListDatabases200ResponseInner>> {
        const response = await this.searchDatabasesRaw({ searchDatabasesRequest: searchDatabasesRequest }, initOverrides);
        return await response.value();
    }

    /**
     * Updates an existing database by its ID. Returns 404 if the database does not exist within the current organisation.
     * Update a database
     */
    async updateDatabaseRaw(requestParameters: UpdateDatabaseOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateDatabase201Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateDatabase().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/databases/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateDatabaseRequestToJSON(requestParameters['updateDatabaseRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateDatabase201ResponseFromJSON(jsonValue));
    }

    /**
     * Updates an existing database by its ID. Returns 404 if the database does not exist within the current organisation.
     * Update a database
     */
    async updateDatabase(id: string, updateDatabaseRequest?: UpdateDatabaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateDatabase201Response> {
        const response = await this.updateDatabaseRaw({ id: id, updateDatabaseRequest: updateDatabaseRequest }, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ListDatabasesSelectEnum = {
    CreatedAt: 'created_at',
    Description: 'description',
    Id: 'id',
    Name: 'name',
    OrganisationId: 'organisation_id',
    Public: 'public',
    Slug: 'slug',
    UpdatedAt: 'updated_at'
} as const;
export type ListDatabasesSelectEnum = typeof ListDatabasesSelectEnum[keyof typeof ListDatabasesSelectEnum];
