/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateOrganisation201Response,
  CreateOrganisationRequest,
  GetChallenge500Response,
  ListDatabasesLimitParameter,
  ListOrganisations200ResponseInner,
  ListOrganisationsOrderParameter,
  ListOrganisationsWhereParameter,
  Logout401Response,
  Logout403Response,
  RequestLoginCode400Response,
  RequestMfaSetup409Response,
  SearchOrganisationsRequest,
  SwitchMembership404Response,
  UpdateOrganisationRequest,
} from '../models/index';
import {
    CreateOrganisation201ResponseFromJSON,
    CreateOrganisation201ResponseToJSON,
    CreateOrganisationRequestFromJSON,
    CreateOrganisationRequestToJSON,
    GetChallenge500ResponseFromJSON,
    GetChallenge500ResponseToJSON,
    ListDatabasesLimitParameterFromJSON,
    ListDatabasesLimitParameterToJSON,
    ListOrganisations200ResponseInnerFromJSON,
    ListOrganisations200ResponseInnerToJSON,
    ListOrganisationsOrderParameterFromJSON,
    ListOrganisationsOrderParameterToJSON,
    ListOrganisationsWhereParameterFromJSON,
    ListOrganisationsWhereParameterToJSON,
    Logout401ResponseFromJSON,
    Logout401ResponseToJSON,
    Logout403ResponseFromJSON,
    Logout403ResponseToJSON,
    RequestLoginCode400ResponseFromJSON,
    RequestLoginCode400ResponseToJSON,
    RequestMfaSetup409ResponseFromJSON,
    RequestMfaSetup409ResponseToJSON,
    SearchOrganisationsRequestFromJSON,
    SearchOrganisationsRequestToJSON,
    SwitchMembership404ResponseFromJSON,
    SwitchMembership404ResponseToJSON,
    UpdateOrganisationRequestFromJSON,
    UpdateOrganisationRequestToJSON,
} from '../models/index';

export interface CreateOrganisationOperationRequest {
    createOrganisationRequest: CreateOrganisationRequest;
}

export interface DeleteOrganisationRequest {
    id: string;
}

export interface GetOrganisationRequest {
    id: string;
}

export interface ListOrganisationsRequest {
    limit?: ListDatabasesLimitParameter;
    order?: ListOrganisationsOrderParameter;
    select?: Set<ListOrganisationsSelectEnum>;
    where?: ListOrganisationsWhereParameter;
}

export interface SearchOrganisationsOperationRequest {
    searchOrganisationsRequest?: SearchOrganisationsRequest;
}

export interface UpdateOrganisationOperationRequest {
    id: string;
    updateOrganisationRequest?: UpdateOrganisationRequest;
}

/**
 * 
 */
export class OrganisationsClient extends runtime.BaseAPI {

    /**
     * Creates a new organisation and adds the authenticated user as its owner. Cannot be performed with a token.
     * Create an organisation
     */
    async createOrganisationRaw(requestParameters: CreateOrganisationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateOrganisation201Response>> {
        if (requestParameters['createOrganisationRequest'] == null) {
            throw new runtime.RequiredError(
                'createOrganisationRequest',
                'Required parameter "createOrganisationRequest" was null or undefined when calling createOrganisation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/organisations`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateOrganisationRequestToJSON(requestParameters['createOrganisationRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateOrganisation201ResponseFromJSON(jsonValue));
    }

    /**
     * Creates a new organisation and adds the authenticated user as its owner. Cannot be performed with a token.
     * Create an organisation
     */
    async createOrganisation(createOrganisationRequest: CreateOrganisationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateOrganisation201Response> {
        const response = await this.createOrganisationRaw({ createOrganisationRequest: createOrganisationRequest }, initOverrides);
        return await response.value();
    }

    /**
     * Permanently deletes the active organisation. All databases, views, workers, and resources must be removed first.
     * Delete an organisation
     */
    async deleteOrganisationRaw(requestParameters: DeleteOrganisationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteOrganisation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/organisations/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Permanently deletes the active organisation. All databases, views, workers, and resources must be removed first.
     * Delete an organisation
     */
    async deleteOrganisation(id: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteOrganisationRaw({ id: id }, initOverrides);
    }

    /**
     * Retrieves an organisation by its ID.
     * Get an organisation
     */
    async getOrganisationRaw(requestParameters: GetOrganisationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateOrganisation201Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getOrganisation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/organisations/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateOrganisation201ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves an organisation by its ID.
     * Get an organisation
     */
    async getOrganisation(id: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateOrganisation201Response> {
        const response = await this.getOrganisationRaw({ id: id }, initOverrides);
        return await response.value();
    }

    /**
     * Returns a list of all organisations. Supports filtering, pagination, and field selection.
     * List organisations
     */
    async listOrganisationsRaw(requestParameters: ListOrganisationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ListOrganisations200ResponseInner>>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['order'] != null) {
            queryParameters['order'] = requestParameters['order'];
        }

        if (requestParameters['select'] != null) {
            queryParameters['select'] = requestParameters['select'];
        }

        if (requestParameters['where'] != null) {
            queryParameters['where'] = requestParameters['where'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/organisations`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ListOrganisations200ResponseInnerFromJSON));
    }

    /**
     * Returns a list of all organisations. Supports filtering, pagination, and field selection.
     * List organisations
     */
    async listOrganisations(limit?: ListDatabasesLimitParameter, order?: ListOrganisationsOrderParameter, select?: Set<ListOrganisationsSelectEnum>, where?: ListOrganisationsWhereParameter, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ListOrganisations200ResponseInner>> {
        const response = await this.listOrganisationsRaw({ limit: limit, order: order, select: select, where: where }, initOverrides);
        return await response.value();
    }

    /**
     * Search all organisations with advanced filtering, including nested AND/OR logic and comparison operators.
     * Search organisations
     */
    async searchOrganisationsRaw(requestParameters: SearchOrganisationsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ListOrganisations200ResponseInner>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/organisations/search`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SearchOrganisationsRequestToJSON(requestParameters['searchOrganisationsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ListOrganisations200ResponseInnerFromJSON));
    }

    /**
     * Search all organisations with advanced filtering, including nested AND/OR logic and comparison operators.
     * Search organisations
     */
    async searchOrganisations(searchOrganisationsRequest?: SearchOrganisationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ListOrganisations200ResponseInner>> {
        const response = await this.searchOrganisationsRaw({ searchOrganisationsRequest: searchOrganisationsRequest }, initOverrides);
        return await response.value();
    }

    /**
     * Updates the active organisation.
     * Update an organisation
     */
    async updateOrganisationRaw(requestParameters: UpdateOrganisationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateOrganisation201Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateOrganisation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/organisations/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateOrganisationRequestToJSON(requestParameters['updateOrganisationRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateOrganisation201ResponseFromJSON(jsonValue));
    }

    /**
     * Updates the active organisation.
     * Update an organisation
     */
    async updateOrganisation(id: string, updateOrganisationRequest?: UpdateOrganisationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateOrganisation201Response> {
        const response = await this.updateOrganisationRaw({ id: id, updateOrganisationRequest: updateOrganisationRequest }, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ListOrganisationsSelectEnum = {
    CreatedAt: 'created_at',
    Id: 'id',
    Name: 'name',
    Public: 'public',
    Slug: 'slug',
    UpdatedAt: 'updated_at'
} as const;
export type ListOrganisationsSelectEnum = typeof ListOrganisationsSelectEnum[keyof typeof ListOrganisationsSelectEnum];
