/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateToken201Response,
  CreateTokenRequest,
  GetChallenge500Response,
  GetToken200Response,
  ListDatabasesLimitParameter,
  ListTokens200ResponseInner,
  ListTokensOrderParameter,
  ListTokensWhereParameter,
  Logout401Response,
  Logout403Response,
  RequestLoginCode400Response,
  SearchTokensRequest,
  SwitchMembership404Response,
  UpdateTokenRequest,
} from '../models/index';
import {
    CreateToken201ResponseFromJSON,
    CreateToken201ResponseToJSON,
    CreateTokenRequestFromJSON,
    CreateTokenRequestToJSON,
    GetChallenge500ResponseFromJSON,
    GetChallenge500ResponseToJSON,
    GetToken200ResponseFromJSON,
    GetToken200ResponseToJSON,
    ListDatabasesLimitParameterFromJSON,
    ListDatabasesLimitParameterToJSON,
    ListTokens200ResponseInnerFromJSON,
    ListTokens200ResponseInnerToJSON,
    ListTokensOrderParameterFromJSON,
    ListTokensOrderParameterToJSON,
    ListTokensWhereParameterFromJSON,
    ListTokensWhereParameterToJSON,
    Logout401ResponseFromJSON,
    Logout401ResponseToJSON,
    Logout403ResponseFromJSON,
    Logout403ResponseToJSON,
    RequestLoginCode400ResponseFromJSON,
    RequestLoginCode400ResponseToJSON,
    SearchTokensRequestFromJSON,
    SearchTokensRequestToJSON,
    SwitchMembership404ResponseFromJSON,
    SwitchMembership404ResponseToJSON,
    UpdateTokenRequestFromJSON,
    UpdateTokenRequestToJSON,
} from '../models/index';

export interface CreateTokenOperationRequest {
    createTokenRequest: CreateTokenRequest;
}

export interface DeleteTokenRequest {
    id: string;
}

export interface GetTokenRequest {
    id: string;
}

export interface ListTokensRequest {
    limit?: ListDatabasesLimitParameter;
    order?: ListTokensOrderParameter;
    select?: Set<ListTokensSelectEnum>;
    where?: ListTokensWhereParameter;
}

export interface SearchTokensOperationRequest {
    searchTokensRequest?: SearchTokensRequest;
}

export interface UpdateTokenOperationRequest {
    id: string;
    updateTokenRequest?: UpdateTokenRequest;
}

/**
 * 
 */
export class TokensClient extends runtime.BaseAPI {

    /**
     * Creates a new API token for the current organisation. The raw token value is returned only in this response and cannot be retrieved again.
     * Create an API token
     */
    async createTokenRaw(requestParameters: CreateTokenOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateToken201Response>> {
        if (requestParameters['createTokenRequest'] == null) {
            throw new runtime.RequiredError(
                'createTokenRequest',
                'Required parameter "createTokenRequest" was null or undefined when calling createToken().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/tokens`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateTokenRequestToJSON(requestParameters['createTokenRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateToken201ResponseFromJSON(jsonValue));
    }

    /**
     * Creates a new API token for the current organisation. The raw token value is returned only in this response and cannot be retrieved again.
     * Create an API token
     */
    async createToken(createTokenRequest: CreateTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateToken201Response> {
        const response = await this.createTokenRaw({ createTokenRequest: createTokenRequest }, initOverrides);
        return await response.value();
    }

    /**
     * Permanently deletes an API token by its ID. Returns 404 if the token does not exist within the current organisation.
     * Delete an API token
     */
    async deleteTokenRaw(requestParameters: DeleteTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteToken().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/tokens/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Permanently deletes an API token by its ID. Returns 404 if the token does not exist within the current organisation.
     * Delete an API token
     */
    async deleteToken(id: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteTokenRaw({ id: id }, initOverrides);
    }

    /**
     * Retrieves a single API token by its ID. Returns 404 if the token does not exist within the current organisation.
     * Get an API token
     */
    async getTokenRaw(requestParameters: GetTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetToken200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getToken().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/tokens/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetToken200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves a single API token by its ID. Returns 404 if the token does not exist within the current organisation.
     * Get an API token
     */
    async getToken(id: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetToken200Response> {
        const response = await this.getTokenRaw({ id: id }, initOverrides);
        return await response.value();
    }

    /**
     * Returns a list of API tokens in the current organisation. Supports filtering, pagination, and field selection.
     * List API tokens
     */
    async listTokensRaw(requestParameters: ListTokensRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ListTokens200ResponseInner>>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['order'] != null) {
            queryParameters['order'] = requestParameters['order'];
        }

        if (requestParameters['select'] != null) {
            queryParameters['select'] = requestParameters['select'];
        }

        if (requestParameters['where'] != null) {
            queryParameters['where'] = requestParameters['where'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/tokens`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ListTokens200ResponseInnerFromJSON));
    }

    /**
     * Returns a list of API tokens in the current organisation. Supports filtering, pagination, and field selection.
     * List API tokens
     */
    async listTokens(limit?: ListDatabasesLimitParameter, order?: ListTokensOrderParameter, select?: Set<ListTokensSelectEnum>, where?: ListTokensWhereParameter, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ListTokens200ResponseInner>> {
        const response = await this.listTokensRaw({ limit: limit, order: order, select: select, where: where }, initOverrides);
        return await response.value();
    }

    /**
     * Search API tokens with advanced filtering, including nested AND/OR logic and comparison operators.
     * Search API tokens
     */
    async searchTokensRaw(requestParameters: SearchTokensOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ListTokens200ResponseInner>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/tokens/search`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SearchTokensRequestToJSON(requestParameters['searchTokensRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ListTokens200ResponseInnerFromJSON));
    }

    /**
     * Search API tokens with advanced filtering, including nested AND/OR logic and comparison operators.
     * Search API tokens
     */
    async searchTokens(searchTokensRequest?: SearchTokensRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ListTokens200ResponseInner>> {
        const response = await this.searchTokensRaw({ searchTokensRequest: searchTokensRequest }, initOverrides);
        return await response.value();
    }

    /**
     * Updates an existing API token by its ID. Returns 404 if the token does not exist within the current organisation.
     * Update an API token
     */
    async updateTokenRaw(requestParameters: UpdateTokenOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetToken200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateToken().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/tokens/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateTokenRequestToJSON(requestParameters['updateTokenRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetToken200ResponseFromJSON(jsonValue));
    }

    /**
     * Updates an existing API token by its ID. Returns 404 if the token does not exist within the current organisation.
     * Update an API token
     */
    async updateToken(id: string, updateTokenRequest?: UpdateTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetToken200Response> {
        const response = await this.updateTokenRaw({ id: id, updateTokenRequest: updateTokenRequest }, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ListTokensSelectEnum = {
    Active: 'active',
    CreatedAt: 'created_at',
    ExpiresAt: 'expires_at',
    Id: 'id',
    LastUsedAt: 'last_used_at',
    Name: 'name',
    OrganisationId: 'organisation_id',
    Scopes: 'scopes',
    UpdatedAt: 'updated_at'
} as const;
export type ListTokensSelectEnum = typeof ListTokensSelectEnum[keyof typeof ListTokensSelectEnum];
