/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateOrganisationRequest
 */
export interface CreateOrganisationRequest {
    /**
     * The display name of the organisation
     * @type {string}
     * @memberof CreateOrganisationRequest
     */
    name: string;
    /**
     * Whether this organisation is publicly visible to other users
     * @type {boolean}
     * @memberof CreateOrganisationRequest
     */
    _public?: boolean;
    /**
     * The URL-friendly identifier of the organisation
     * @type {string}
     * @memberof CreateOrganisationRequest
     */
    slug: string;
}

/**
 * Check if a given object implements the CreateOrganisationRequest interface.
 */
export function instanceOfCreateOrganisationRequest(value: object): value is CreateOrganisationRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    return true;
}

export function CreateOrganisationRequestFromJSON(json: any): CreateOrganisationRequest {
    return CreateOrganisationRequestFromJSONTyped(json, false);
}

export function CreateOrganisationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrganisationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        '_public': json['public'] == null ? undefined : json['public'],
        'slug': json['slug'],
    };
}

export function CreateOrganisationRequestToJSON(json: any): CreateOrganisationRequest {
    return CreateOrganisationRequestToJSONTyped(json, false);
}

export function CreateOrganisationRequestToJSONTyped(value?: CreateOrganisationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'public': value['_public'],
        'slug': value['slug'],
    };
}

