/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateOrganisation201Response
 */
export interface CreateOrganisation201Response {
    /**
     * The date and time the organisation was created
     * @type {Date}
     * @memberof CreateOrganisation201Response
     */
    createdAt: Date;
    /**
     * The unique identifier of the organisation
     * @type {string}
     * @memberof CreateOrganisation201Response
     */
    id: string;
    /**
     * The display name of the organisation
     * @type {string}
     * @memberof CreateOrganisation201Response
     */
    name: string;
    /**
     * Whether this organisation is publicly visible to other users
     * @type {boolean}
     * @memberof CreateOrganisation201Response
     */
    _public: boolean;
    /**
     * The URL-friendly identifier of the organisation
     * @type {string}
     * @memberof CreateOrganisation201Response
     */
    slug: string;
    /**
     * The date and time the organisation was last updated
     * @type {Date}
     * @memberof CreateOrganisation201Response
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the CreateOrganisation201Response interface.
 */
export function instanceOfCreateOrganisation201Response(value: object): value is CreateOrganisation201Response {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('_public' in value) || value['_public'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function CreateOrganisation201ResponseFromJSON(json: any): CreateOrganisation201Response {
    return CreateOrganisation201ResponseFromJSONTyped(json, false);
}

export function CreateOrganisation201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrganisation201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['created_at'])),
        'id': json['id'],
        'name': json['name'],
        '_public': json['public'],
        'slug': json['slug'],
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function CreateOrganisation201ResponseToJSON(json: any): CreateOrganisation201Response {
    return CreateOrganisation201ResponseToJSONTyped(json, false);
}

export function CreateOrganisation201ResponseToJSONTyped(value?: CreateOrganisation201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'].toISOString(),
        'id': value['id'],
        'name': value['name'],
        'public': value['_public'],
        'slug': value['slug'],
        'updated_at': value['updatedAt'].toISOString(),
    };
}

