/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateResource201Response
 */
export interface CreateResource201Response {
    /**
     * Resource-specific configuration
     * @type {{ [key: string]: any; }}
     * @memberof CreateResource201Response
     */
    config: { [key: string]: any; };
    /**
     * The date and time the resource was created
     * @type {Date}
     * @memberof CreateResource201Response
     */
    createdAt: Date;
    /**
     * The unique identifier of the resource
     * @type {string}
     * @memberof CreateResource201Response
     */
    id: string;
    /**
     * The display name of the resource
     * @type {string}
     * @memberof CreateResource201Response
     */
    name: string;
    /**
     * The organisation this resource belongs to
     * @type {string}
     * @memberof CreateResource201Response
     */
    organisationId: string;
    /**
     * The resource type
     * @type {string}
     * @memberof CreateResource201Response
     */
    type: CreateResource201ResponseTypeEnum;
    /**
     * The date and time the resource was last updated
     * @type {Date}
     * @memberof CreateResource201Response
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const CreateResource201ResponseTypeEnum = {
    Postgres: 'postgres',
    S3: 's3',
    Smtp: 'smtp'
} as const;
export type CreateResource201ResponseTypeEnum = typeof CreateResource201ResponseTypeEnum[keyof typeof CreateResource201ResponseTypeEnum];


/**
 * Check if a given object implements the CreateResource201Response interface.
 */
export function instanceOfCreateResource201Response(value: object): value is CreateResource201Response {
    if (!('config' in value) || value['config'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('organisationId' in value) || value['organisationId'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function CreateResource201ResponseFromJSON(json: any): CreateResource201Response {
    return CreateResource201ResponseFromJSONTyped(json, false);
}

export function CreateResource201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateResource201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'config': json['config'],
        'createdAt': (new Date(json['created_at'])),
        'id': json['id'],
        'name': json['name'],
        'organisationId': json['organisation_id'],
        'type': json['type'],
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function CreateResource201ResponseToJSON(json: any): CreateResource201Response {
    return CreateResource201ResponseToJSONTyped(json, false);
}

export function CreateResource201ResponseToJSONTyped(value?: CreateResource201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'config': value['config'],
        'created_at': value['createdAt'].toISOString(),
        'id': value['id'],
        'name': value['name'],
        'organisation_id': value['organisationId'],
        'type': value['type'],
        'updated_at': value['updatedAt'].toISOString(),
    };
}

