/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTokenRequest
 */
export interface CreateTokenRequest {
    /**
     * The date and time the token expires
     * @type {Date}
     * @memberof CreateTokenRequest
     */
    expiresAt?: Date;
    /**
     * The display name of the token
     * @type {string}
     * @memberof CreateTokenRequest
     */
    name: string;
    /**
     * Permission scopes granted to this token
     * @type {Array<string>}
     * @memberof CreateTokenRequest
     */
    scopes: Array<string>;
}

/**
 * Check if a given object implements the CreateTokenRequest interface.
 */
export function instanceOfCreateTokenRequest(value: object): value is CreateTokenRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('scopes' in value) || value['scopes'] === undefined) return false;
    return true;
}

export function CreateTokenRequestFromJSON(json: any): CreateTokenRequest {
    return CreateTokenRequestFromJSONTyped(json, false);
}

export function CreateTokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTokenRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'expiresAt': json['expires_at'] == null ? undefined : (new Date(json['expires_at'])),
        'name': json['name'],
        'scopes': json['scopes'],
    };
}

export function CreateTokenRequestToJSON(json: any): CreateTokenRequest {
    return CreateTokenRequestToJSONTyped(json, false);
}

export function CreateTokenRequestToJSONTyped(value?: CreateTokenRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'expires_at': value['expiresAt'] == null ? value['expiresAt'] : value['expiresAt'].toISOString(),
        'name': value['name'],
        'scopes': value['scopes'],
    };
}

