/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateUser201Response
 */
export interface CreateUser201Response {
    /**
     * Whether the account is enabled
     * @type {boolean}
     * @memberof CreateUser201Response
     */
    active: boolean;
    /**
     * The date and time the user was created
     * @type {Date}
     * @memberof CreateUser201Response
     */
    createdAt: Date;
    /**
     * The email address of the user
     * @type {string}
     * @memberof CreateUser201Response
     */
    email: string;
    /**
     * The unique public handle of the user
     * @type {string}
     * @memberof CreateUser201Response
     */
    handle: string;
    /**
     * The unique identifier of the user
     * @type {string}
     * @memberof CreateUser201Response
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUser201Response
     */
    locale: string | null;
    /**
     * Whether multi-factor authentication is enabled
     * @type {boolean}
     * @memberof CreateUser201Response
     */
    mfaEnabled: boolean;
    /**
     * The display name of the user
     * @type {string}
     * @memberof CreateUser201Response
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUser201Response
     */
    publicEmail: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateUser201Response
     */
    publicName: string | null;
    /**
     * The date and time the user was last updated
     * @type {Date}
     * @memberof CreateUser201Response
     */
    updatedAt: Date;
    /**
     * Whether the email address has been verified
     * @type {boolean}
     * @memberof CreateUser201Response
     */
    verified: boolean;
}

/**
 * Check if a given object implements the CreateUser201Response interface.
 */
export function instanceOfCreateUser201Response(value: object): value is CreateUser201Response {
    if (!('active' in value) || value['active'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('handle' in value) || value['handle'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('locale' in value) || value['locale'] === undefined) return false;
    if (!('mfaEnabled' in value) || value['mfaEnabled'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('publicEmail' in value) || value['publicEmail'] === undefined) return false;
    if (!('publicName' in value) || value['publicName'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('verified' in value) || value['verified'] === undefined) return false;
    return true;
}

export function CreateUser201ResponseFromJSON(json: any): CreateUser201Response {
    return CreateUser201ResponseFromJSONTyped(json, false);
}

export function CreateUser201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUser201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'active': json['active'],
        'createdAt': (new Date(json['created_at'])),
        'email': json['email'],
        'handle': json['handle'],
        'id': json['id'],
        'locale': json['locale'],
        'mfaEnabled': json['mfa_enabled'],
        'name': json['name'],
        'publicEmail': json['public_email'],
        'publicName': json['public_name'],
        'updatedAt': (new Date(json['updated_at'])),
        'verified': json['verified'],
    };
}

export function CreateUser201ResponseToJSON(json: any): CreateUser201Response {
    return CreateUser201ResponseToJSONTyped(json, false);
}

export function CreateUser201ResponseToJSONTyped(value?: CreateUser201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'active': value['active'],
        'created_at': value['createdAt'].toISOString(),
        'email': value['email'],
        'handle': value['handle'],
        'id': value['id'],
        'locale': value['locale'],
        'mfa_enabled': value['mfaEnabled'],
        'name': value['name'],
        'public_email': value['publicEmail'],
        'public_name': value['publicName'],
        'updated_at': value['updatedAt'].toISOString(),
        'verified': value['verified'],
    };
}

