/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateToken201Response
 */
export interface CreateToken201Response {
    /**
     * Whether the token is usable
     * @type {boolean}
     * @memberof CreateToken201Response
     */
    active: boolean;
    /**
     * The date and time the token was created
     * @type {Date}
     * @memberof CreateToken201Response
     */
    createdAt: Date;
    /**
     * The date and time the token expires
     * @type {Date}
     * @memberof CreateToken201Response
     */
    expiresAt: Date | null;
    /**
     * The unique identifier of the token
     * @type {string}
     * @memberof CreateToken201Response
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof CreateToken201Response
     */
    lastUsedAt: Date | null;
    /**
     * The display name of the token
     * @type {string}
     * @memberof CreateToken201Response
     */
    name: string;
    /**
     * The organisation this token belongs to
     * @type {string}
     * @memberof CreateToken201Response
     */
    organisationId: string;
    /**
     * Permission scopes granted to this token
     * @type {Array<string>}
     * @memberof CreateToken201Response
     */
    scopes: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof CreateToken201Response
     */
    updatedAt: Date | null;
    /**
     * The raw API token, only returned once upon creation
     * @type {string}
     * @memberof CreateToken201Response
     */
    token: string;
}

/**
 * Check if a given object implements the CreateToken201Response interface.
 */
export function instanceOfCreateToken201Response(value: object): value is CreateToken201Response {
    if (!('active' in value) || value['active'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('lastUsedAt' in value) || value['lastUsedAt'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('organisationId' in value) || value['organisationId'] === undefined) return false;
    if (!('scopes' in value) || value['scopes'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function CreateToken201ResponseFromJSON(json: any): CreateToken201Response {
    return CreateToken201ResponseFromJSONTyped(json, false);
}

export function CreateToken201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateToken201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'active': json['active'],
        'createdAt': (new Date(json['created_at'])),
        'expiresAt': (json['expires_at'] == null ? null : new Date(json['expires_at'])),
        'id': json['id'],
        'lastUsedAt': (json['last_used_at'] == null ? null : new Date(json['last_used_at'])),
        'name': json['name'],
        'organisationId': json['organisation_id'],
        'scopes': json['scopes'],
        'updatedAt': (json['updated_at'] == null ? null : new Date(json['updated_at'])),
        'token': json['token'],
    };
}

export function CreateToken201ResponseToJSON(json: any): CreateToken201Response {
    return CreateToken201ResponseToJSONTyped(json, false);
}

export function CreateToken201ResponseToJSONTyped(value?: CreateToken201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'active': value['active'],
        'created_at': value['createdAt'].toISOString(),
        'expires_at': value['expiresAt'] == null ? value['expiresAt'] : value['expiresAt'].toISOString(),
        'id': value['id'],
        'last_used_at': value['lastUsedAt'] == null ? value['lastUsedAt'] : value['lastUsedAt'].toISOString(),
        'name': value['name'],
        'organisation_id': value['organisationId'],
        'scopes': value['scopes'],
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'token': value['token'],
    };
}

