/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateWorkerRequest
 */
export interface CreateWorkerRequest {
    /**
     * A description of the worker
     * @type {string}
     * @memberof CreateWorkerRequest
     */
    description?: string;
    /**
     * The display name of the worker
     * @type {string}
     * @memberof CreateWorkerRequest
     */
    name: string;
    /**
     * Whether this worker is publicly visible to other organisations
     * @type {boolean}
     * @memberof CreateWorkerRequest
     */
    _public?: boolean;
    /**
     * The URL-friendly identifier of the worker
     * @type {string}
     * @memberof CreateWorkerRequest
     */
    slug: string;
}

/**
 * Check if a given object implements the CreateWorkerRequest interface.
 */
export function instanceOfCreateWorkerRequest(value: object): value is CreateWorkerRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    return true;
}

export function CreateWorkerRequestFromJSON(json: any): CreateWorkerRequest {
    return CreateWorkerRequestFromJSONTyped(json, false);
}

export function CreateWorkerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWorkerRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'name': json['name'],
        '_public': json['public'] == null ? undefined : json['public'],
        'slug': json['slug'],
    };
}

export function CreateWorkerRequestToJSON(json: any): CreateWorkerRequest {
    return CreateWorkerRequestToJSONTyped(json, false);
}

export function CreateWorkerRequestToJSONTyped(value?: CreateWorkerRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'name': value['name'],
        'public': value['_public'],
        'slug': value['slug'],
    };
}

