/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateDatabase201Response
 */
export interface CreateDatabase201Response {
    /**
     * The date and time the database was created
     * @type {Date}
     * @memberof CreateDatabase201Response
     */
    createdAt: Date;
    /**
     * A description of the database
     * @type {string}
     * @memberof CreateDatabase201Response
     */
    description: string | null;
    /**
     * The unique identifier of the database
     * @type {string}
     * @memberof CreateDatabase201Response
     */
    id: string;
    /**
     * The display name of the database
     * @type {string}
     * @memberof CreateDatabase201Response
     */
    name: string;
    /**
     * The organisation this database belongs to
     * @type {string}
     * @memberof CreateDatabase201Response
     */
    organisationId: string;
    /**
     * Whether this database is publicly visible to other organisations
     * @type {boolean}
     * @memberof CreateDatabase201Response
     */
    _public: boolean;
    /**
     * The composite slug in organisation:database format
     * @type {string}
     * @memberof CreateDatabase201Response
     */
    slug: string;
    /**
     * The date and time the database was last updated
     * @type {Date}
     * @memberof CreateDatabase201Response
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the CreateDatabase201Response interface.
 */
export function instanceOfCreateDatabase201Response(value: object): value is CreateDatabase201Response {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('organisationId' in value) || value['organisationId'] === undefined) return false;
    if (!('_public' in value) || value['_public'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function CreateDatabase201ResponseFromJSON(json: any): CreateDatabase201Response {
    return CreateDatabase201ResponseFromJSONTyped(json, false);
}

export function CreateDatabase201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDatabase201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['created_at'])),
        'description': json['description'],
        'id': json['id'],
        'name': json['name'],
        'organisationId': json['organisation_id'],
        '_public': json['public'],
        'slug': json['slug'],
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function CreateDatabase201ResponseToJSON(json: any): CreateDatabase201Response {
    return CreateDatabase201ResponseToJSONTyped(json, false);
}

export function CreateDatabase201ResponseToJSONTyped(value?: CreateDatabase201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'].toISOString(),
        'description': value['description'],
        'id': value['id'],
        'name': value['name'],
        'organisation_id': value['organisationId'],
        'public': value['_public'],
        'slug': value['slug'],
        'updated_at': value['updatedAt'].toISOString(),
    };
}

