/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateMembershipRequest
 */
export interface CreateMembershipRequest {
    /**
     * Permission scopes granted to this member
     * @type {Array<string>}
     * @memberof CreateMembershipRequest
     */
    scopes: Array<string>;
    /**
     * The user this membership belongs to
     * @type {string}
     * @memberof CreateMembershipRequest
     */
    userId: string;
}

/**
 * Check if a given object implements the CreateMembershipRequest interface.
 */
export function instanceOfCreateMembershipRequest(value: object): value is CreateMembershipRequest {
    if (!('scopes' in value) || value['scopes'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function CreateMembershipRequestFromJSON(json: any): CreateMembershipRequest {
    return CreateMembershipRequestFromJSONTyped(json, false);
}

export function CreateMembershipRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMembershipRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'scopes': json['scopes'],
        'userId': json['user_id'],
    };
}

export function CreateMembershipRequestToJSON(json: any): CreateMembershipRequest {
    return CreateMembershipRequestToJSONTyped(json, false);
}

export function CreateMembershipRequestToJSONTyped(value?: CreateMembershipRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scopes': value['scopes'],
        'user_id': value['userId'],
    };
}

