/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenerateMfaBackupCodesRequest
 */
export interface GenerateMfaBackupCodesRequest {
    /**
     * The password for the user account
     * @type {string}
     * @memberof GenerateMfaBackupCodesRequest
     */
    password: string;
}

/**
 * Check if a given object implements the GenerateMfaBackupCodesRequest interface.
 */
export function instanceOfGenerateMfaBackupCodesRequest(value: object): value is GenerateMfaBackupCodesRequest {
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function GenerateMfaBackupCodesRequestFromJSON(json: any): GenerateMfaBackupCodesRequest {
    return GenerateMfaBackupCodesRequestFromJSONTyped(json, false);
}

export function GenerateMfaBackupCodesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateMfaBackupCodesRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'password': json['password'],
    };
}

export function GenerateMfaBackupCodesRequestToJSON(json: any): GenerateMfaBackupCodesRequest {
    return GenerateMfaBackupCodesRequestToJSONTyped(json, false);
}

export function GenerateMfaBackupCodesRequestToJSONTyped(value?: GenerateMfaBackupCodesRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'password': value['password'],
    };
}

