/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetChallenge200Response
 */
export interface GetChallenge200Response {
    /**
     * The hash algorithm used for the challenge
     * @type {string}
     * @memberof GetChallenge200Response
     */
    algorithm: string;
    /**
     * The hash of the secret number that the client must find
     * @type {string}
     * @memberof GetChallenge200Response
     */
    challenge: string;
    /**
     * The maximum number the client should iterate to
     * @type {number}
     * @memberof GetChallenge200Response
     */
    maxnumber?: number;
    /**
     * A random salt, may contain URL-encoded parameters
     * @type {string}
     * @memberof GetChallenge200Response
     */
    salt: string;
    /**
     * The HMAC signature for server-side verification
     * @type {string}
     * @memberof GetChallenge200Response
     */
    signature: string;
}

/**
 * Check if a given object implements the GetChallenge200Response interface.
 */
export function instanceOfGetChallenge200Response(value: object): value is GetChallenge200Response {
    if (!('algorithm' in value) || value['algorithm'] === undefined) return false;
    if (!('challenge' in value) || value['challenge'] === undefined) return false;
    if (!('salt' in value) || value['salt'] === undefined) return false;
    if (!('signature' in value) || value['signature'] === undefined) return false;
    return true;
}

export function GetChallenge200ResponseFromJSON(json: any): GetChallenge200Response {
    return GetChallenge200ResponseFromJSONTyped(json, false);
}

export function GetChallenge200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetChallenge200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'algorithm': json['algorithm'],
        'challenge': json['challenge'],
        'maxnumber': json['maxnumber'] == null ? undefined : json['maxnumber'],
        'salt': json['salt'],
        'signature': json['signature'],
    };
}

export function GetChallenge200ResponseToJSON(json: any): GetChallenge200Response {
    return GetChallenge200ResponseToJSONTyped(json, false);
}

export function GetChallenge200ResponseToJSONTyped(value?: GetChallenge200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'algorithm': value['algorithm'],
        'challenge': value['challenge'],
        'maxnumber': value['maxnumber'],
        'salt': value['salt'],
        'signature': value['signature'],
    };
}

