/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetCsrfToken200Response
 */
export interface GetCsrfToken200Response {
    /**
     * The CSRF token to include in subsequent requests
     * @type {string}
     * @memberof GetCsrfToken200Response
     */
    token: string;
}

/**
 * Check if a given object implements the GetCsrfToken200Response interface.
 */
export function instanceOfGetCsrfToken200Response(value: object): value is GetCsrfToken200Response {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function GetCsrfToken200ResponseFromJSON(json: any): GetCsrfToken200Response {
    return GetCsrfToken200ResponseFromJSONTyped(json, false);
}

export function GetCsrfToken200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCsrfToken200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function GetCsrfToken200ResponseToJSON(json: any): GetCsrfToken200Response {
    return GetCsrfToken200ResponseToJSONTyped(json, false);
}

export function GetCsrfToken200ResponseToJSONTyped(value?: GetCsrfToken200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

