/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListTokensWhereParameterLastUsedAtAnyOf } from './ListTokensWhereParameterLastUsedAtAnyOf';
import {
    ListTokensWhereParameterLastUsedAtAnyOfFromJSON,
    ListTokensWhereParameterLastUsedAtAnyOfFromJSONTyped,
    ListTokensWhereParameterLastUsedAtAnyOfToJSON,
    ListTokensWhereParameterLastUsedAtAnyOfToJSONTyped,
} from './ListTokensWhereParameterLastUsedAtAnyOf';

/**
 * 
 * @export
 * @interface ListTokensWhereParameterLastUsedAt
 */
export interface ListTokensWhereParameterLastUsedAt {
    /**
     * 
     * @type {Date}
     * @memberof ListTokensWhereParameterLastUsedAt
     */
    eq?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ListTokensWhereParameterLastUsedAt
     */
    gt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ListTokensWhereParameterLastUsedAt
     */
    gte?: Date | null;
    /**
     * Pattern match (ilike). Use % as wildcard.
     * @type {string}
     * @memberof ListTokensWhereParameterLastUsedAt
     */
    ilike?: string;
    /**
     * Comma-separated list of values (in)
     * @type {string}
     * @memberof ListTokensWhereParameterLastUsedAt
     */
    _in?: string;
    /**
     * Pattern match (like). Use % as wildcard.
     * @type {string}
     * @memberof ListTokensWhereParameterLastUsedAt
     */
    like?: string;
    /**
     * 
     * @type {Date}
     * @memberof ListTokensWhereParameterLastUsedAt
     */
    lt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ListTokensWhereParameterLastUsedAt
     */
    lte?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ListTokensWhereParameterLastUsedAt
     */
    neq?: Date | null;
    /**
     * Comma-separated list of values (nin)
     * @type {string}
     * @memberof ListTokensWhereParameterLastUsedAt
     */
    nin?: string;
    /**
     * Check for NULL (true) or NOT NULL (false)
     * @type {string}
     * @memberof ListTokensWhereParameterLastUsedAt
     */
    _null?: ListTokensWhereParameterLastUsedAtNullEnum;
}


/**
 * @export
 */
export const ListTokensWhereParameterLastUsedAtNullEnum = {
    True: 'true',
    False: 'false'
} as const;
export type ListTokensWhereParameterLastUsedAtNullEnum = typeof ListTokensWhereParameterLastUsedAtNullEnum[keyof typeof ListTokensWhereParameterLastUsedAtNullEnum];


/**
 * Check if a given object implements the ListTokensWhereParameterLastUsedAt interface.
 */
export function instanceOfListTokensWhereParameterLastUsedAt(value: object): value is ListTokensWhereParameterLastUsedAt {
    return true;
}

export function ListTokensWhereParameterLastUsedAtFromJSON(json: any): ListTokensWhereParameterLastUsedAt {
    return ListTokensWhereParameterLastUsedAtFromJSONTyped(json, false);
}

export function ListTokensWhereParameterLastUsedAtFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListTokensWhereParameterLastUsedAt {
    if (json == null) {
        return json;
    }
    return {
        
        'eq': json['eq'] == null ? undefined : (new Date(json['eq'])),
        'gt': json['gt'] == null ? undefined : (new Date(json['gt'])),
        'gte': json['gte'] == null ? undefined : (new Date(json['gte'])),
        'ilike': json['ilike'] == null ? undefined : json['ilike'],
        '_in': json['in'] == null ? undefined : json['in'],
        'like': json['like'] == null ? undefined : json['like'],
        'lt': json['lt'] == null ? undefined : (new Date(json['lt'])),
        'lte': json['lte'] == null ? undefined : (new Date(json['lte'])),
        'neq': json['neq'] == null ? undefined : (new Date(json['neq'])),
        'nin': json['nin'] == null ? undefined : json['nin'],
        '_null': json['null'] == null ? undefined : json['null'],
    };
}

export function ListTokensWhereParameterLastUsedAtToJSON(json: any): ListTokensWhereParameterLastUsedAt {
    return ListTokensWhereParameterLastUsedAtToJSONTyped(json, false);
}

export function ListTokensWhereParameterLastUsedAtToJSONTyped(value?: ListTokensWhereParameterLastUsedAt | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'eq': value['eq'] == null ? value['eq'] : value['eq'].toISOString(),
        'gt': value['gt'] == null ? value['gt'] : value['gt'].toISOString(),
        'gte': value['gte'] == null ? value['gte'] : value['gte'].toISOString(),
        'ilike': value['ilike'],
        'in': value['_in'],
        'like': value['like'],
        'lt': value['lt'] == null ? value['lt'] : value['lt'].toISOString(),
        'lte': value['lte'] == null ? value['lte'] : value['lte'].toISOString(),
        'neq': value['neq'] == null ? value['neq'] : value['neq'].toISOString(),
        'nin': value['nin'],
        'null': value['_null'],
    };
}

