/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListMembershipsOrderParameter
 */
export interface ListMembershipsOrderParameter {
    /**
     * Sort direction for this field
     * @type {string}
     * @memberof ListMembershipsOrderParameter
     */
    createdAt?: ListMembershipsOrderParameterCreatedAtEnum;
    /**
     * Sort direction for this field
     * @type {string}
     * @memberof ListMembershipsOrderParameter
     */
    id?: ListMembershipsOrderParameterIdEnum;
    /**
     * Sort direction for this field
     * @type {string}
     * @memberof ListMembershipsOrderParameter
     */
    organisationId?: ListMembershipsOrderParameterOrganisationIdEnum;
    /**
     * Sort direction for this field
     * @type {string}
     * @memberof ListMembershipsOrderParameter
     */
    scopes?: ListMembershipsOrderParameterScopesEnum;
    /**
     * Sort direction for this field
     * @type {string}
     * @memberof ListMembershipsOrderParameter
     */
    updatedAt?: ListMembershipsOrderParameterUpdatedAtEnum;
    /**
     * Sort direction for this field
     * @type {string}
     * @memberof ListMembershipsOrderParameter
     */
    userId?: ListMembershipsOrderParameterUserIdEnum;
}


/**
 * @export
 */
export const ListMembershipsOrderParameterCreatedAtEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type ListMembershipsOrderParameterCreatedAtEnum = typeof ListMembershipsOrderParameterCreatedAtEnum[keyof typeof ListMembershipsOrderParameterCreatedAtEnum];

/**
 * @export
 */
export const ListMembershipsOrderParameterIdEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type ListMembershipsOrderParameterIdEnum = typeof ListMembershipsOrderParameterIdEnum[keyof typeof ListMembershipsOrderParameterIdEnum];

/**
 * @export
 */
export const ListMembershipsOrderParameterOrganisationIdEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type ListMembershipsOrderParameterOrganisationIdEnum = typeof ListMembershipsOrderParameterOrganisationIdEnum[keyof typeof ListMembershipsOrderParameterOrganisationIdEnum];

/**
 * @export
 */
export const ListMembershipsOrderParameterScopesEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type ListMembershipsOrderParameterScopesEnum = typeof ListMembershipsOrderParameterScopesEnum[keyof typeof ListMembershipsOrderParameterScopesEnum];

/**
 * @export
 */
export const ListMembershipsOrderParameterUpdatedAtEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type ListMembershipsOrderParameterUpdatedAtEnum = typeof ListMembershipsOrderParameterUpdatedAtEnum[keyof typeof ListMembershipsOrderParameterUpdatedAtEnum];

/**
 * @export
 */
export const ListMembershipsOrderParameterUserIdEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type ListMembershipsOrderParameterUserIdEnum = typeof ListMembershipsOrderParameterUserIdEnum[keyof typeof ListMembershipsOrderParameterUserIdEnum];


/**
 * Check if a given object implements the ListMembershipsOrderParameter interface.
 */
export function instanceOfListMembershipsOrderParameter(value: object): value is ListMembershipsOrderParameter {
    return true;
}

export function ListMembershipsOrderParameterFromJSON(json: any): ListMembershipsOrderParameter {
    return ListMembershipsOrderParameterFromJSONTyped(json, false);
}

export function ListMembershipsOrderParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListMembershipsOrderParameter {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'id': json['id'] == null ? undefined : json['id'],
        'organisationId': json['organisation_id'] == null ? undefined : json['organisation_id'],
        'scopes': json['scopes'] == null ? undefined : json['scopes'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
    };
}

export function ListMembershipsOrderParameterToJSON(json: any): ListMembershipsOrderParameter {
    return ListMembershipsOrderParameterToJSONTyped(json, false);
}

export function ListMembershipsOrderParameterToJSONTyped(value?: ListMembershipsOrderParameter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'],
        'id': value['id'],
        'organisation_id': value['organisationId'],
        'scopes': value['scopes'],
        'updated_at': value['updatedAt'],
        'user_id': value['userId'],
    };
}

