/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListOrganisationsOrderParameter
 */
export interface ListOrganisationsOrderParameter {
    /**
     * Sort direction for this field
     * @type {string}
     * @memberof ListOrganisationsOrderParameter
     */
    createdAt?: ListOrganisationsOrderParameterCreatedAtEnum;
    /**
     * Sort direction for this field
     * @type {string}
     * @memberof ListOrganisationsOrderParameter
     */
    id?: ListOrganisationsOrderParameterIdEnum;
    /**
     * Sort direction for this field
     * @type {string}
     * @memberof ListOrganisationsOrderParameter
     */
    name?: ListOrganisationsOrderParameterNameEnum;
    /**
     * Sort direction for this field
     * @type {string}
     * @memberof ListOrganisationsOrderParameter
     */
    _public?: ListOrganisationsOrderParameterPublicEnum;
    /**
     * Sort direction for this field
     * @type {string}
     * @memberof ListOrganisationsOrderParameter
     */
    slug?: ListOrganisationsOrderParameterSlugEnum;
    /**
     * Sort direction for this field
     * @type {string}
     * @memberof ListOrganisationsOrderParameter
     */
    updatedAt?: ListOrganisationsOrderParameterUpdatedAtEnum;
}


/**
 * @export
 */
export const ListOrganisationsOrderParameterCreatedAtEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type ListOrganisationsOrderParameterCreatedAtEnum = typeof ListOrganisationsOrderParameterCreatedAtEnum[keyof typeof ListOrganisationsOrderParameterCreatedAtEnum];

/**
 * @export
 */
export const ListOrganisationsOrderParameterIdEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type ListOrganisationsOrderParameterIdEnum = typeof ListOrganisationsOrderParameterIdEnum[keyof typeof ListOrganisationsOrderParameterIdEnum];

/**
 * @export
 */
export const ListOrganisationsOrderParameterNameEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type ListOrganisationsOrderParameterNameEnum = typeof ListOrganisationsOrderParameterNameEnum[keyof typeof ListOrganisationsOrderParameterNameEnum];

/**
 * @export
 */
export const ListOrganisationsOrderParameterPublicEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type ListOrganisationsOrderParameterPublicEnum = typeof ListOrganisationsOrderParameterPublicEnum[keyof typeof ListOrganisationsOrderParameterPublicEnum];

/**
 * @export
 */
export const ListOrganisationsOrderParameterSlugEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type ListOrganisationsOrderParameterSlugEnum = typeof ListOrganisationsOrderParameterSlugEnum[keyof typeof ListOrganisationsOrderParameterSlugEnum];

/**
 * @export
 */
export const ListOrganisationsOrderParameterUpdatedAtEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type ListOrganisationsOrderParameterUpdatedAtEnum = typeof ListOrganisationsOrderParameterUpdatedAtEnum[keyof typeof ListOrganisationsOrderParameterUpdatedAtEnum];


/**
 * Check if a given object implements the ListOrganisationsOrderParameter interface.
 */
export function instanceOfListOrganisationsOrderParameter(value: object): value is ListOrganisationsOrderParameter {
    return true;
}

export function ListOrganisationsOrderParameterFromJSON(json: any): ListOrganisationsOrderParameter {
    return ListOrganisationsOrderParameterFromJSONTyped(json, false);
}

export function ListOrganisationsOrderParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListOrganisationsOrderParameter {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        '_public': json['public'] == null ? undefined : json['public'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

export function ListOrganisationsOrderParameterToJSON(json: any): ListOrganisationsOrderParameter {
    return ListOrganisationsOrderParameterToJSONTyped(json, false);
}

export function ListOrganisationsOrderParameterToJSONTyped(value?: ListOrganisationsOrderParameter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'],
        'id': value['id'],
        'name': value['name'],
        'public': value['_public'],
        'slug': value['slug'],
        'updated_at': value['updatedAt'],
    };
}

