/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListViewsWhereParameterOrganisationId } from './ListViewsWhereParameterOrganisationId';
import {
    ListViewsWhereParameterOrganisationIdFromJSON,
    ListViewsWhereParameterOrganisationIdFromJSONTyped,
    ListViewsWhereParameterOrganisationIdToJSON,
    ListViewsWhereParameterOrganisationIdToJSONTyped,
} from './ListViewsWhereParameterOrganisationId';
import type { ListViewsWhereParameterUpdatedAt } from './ListViewsWhereParameterUpdatedAt';
import {
    ListViewsWhereParameterUpdatedAtFromJSON,
    ListViewsWhereParameterUpdatedAtFromJSONTyped,
    ListViewsWhereParameterUpdatedAtToJSON,
    ListViewsWhereParameterUpdatedAtToJSONTyped,
} from './ListViewsWhereParameterUpdatedAt';
import type { ListViewsWhereParameterPublic } from './ListViewsWhereParameterPublic';
import {
    ListViewsWhereParameterPublicFromJSON,
    ListViewsWhereParameterPublicFromJSONTyped,
    ListViewsWhereParameterPublicToJSON,
    ListViewsWhereParameterPublicToJSONTyped,
} from './ListViewsWhereParameterPublic';
import type { ListViewsWhereParameterId } from './ListViewsWhereParameterId';
import {
    ListViewsWhereParameterIdFromJSON,
    ListViewsWhereParameterIdFromJSONTyped,
    ListViewsWhereParameterIdToJSON,
    ListViewsWhereParameterIdToJSONTyped,
} from './ListViewsWhereParameterId';
import type { ListViewsWhereParameterSlug } from './ListViewsWhereParameterSlug';
import {
    ListViewsWhereParameterSlugFromJSON,
    ListViewsWhereParameterSlugFromJSONTyped,
    ListViewsWhereParameterSlugToJSON,
    ListViewsWhereParameterSlugToJSONTyped,
} from './ListViewsWhereParameterSlug';
import type { ListViewsWhereParameterDescription } from './ListViewsWhereParameterDescription';
import {
    ListViewsWhereParameterDescriptionFromJSON,
    ListViewsWhereParameterDescriptionFromJSONTyped,
    ListViewsWhereParameterDescriptionToJSON,
    ListViewsWhereParameterDescriptionToJSONTyped,
} from './ListViewsWhereParameterDescription';
import type { ListViewsWhereParameterCreatedAt } from './ListViewsWhereParameterCreatedAt';
import {
    ListViewsWhereParameterCreatedAtFromJSON,
    ListViewsWhereParameterCreatedAtFromJSONTyped,
    ListViewsWhereParameterCreatedAtToJSON,
    ListViewsWhereParameterCreatedAtToJSONTyped,
} from './ListViewsWhereParameterCreatedAt';
import type { ListViewsWhereParameterName } from './ListViewsWhereParameterName';
import {
    ListViewsWhereParameterNameFromJSON,
    ListViewsWhereParameterNameFromJSONTyped,
    ListViewsWhereParameterNameToJSON,
    ListViewsWhereParameterNameToJSONTyped,
} from './ListViewsWhereParameterName';

/**
 * 
 * @export
 * @interface ListViewsWhereParameter
 */
export interface ListViewsWhereParameter {
    /**
     * 
     * @type {ListViewsWhereParameterCreatedAt}
     * @memberof ListViewsWhereParameter
     */
    createdAt?: ListViewsWhereParameterCreatedAt;
    /**
     * 
     * @type {ListViewsWhereParameterDescription}
     * @memberof ListViewsWhereParameter
     */
    description?: ListViewsWhereParameterDescription;
    /**
     * 
     * @type {ListViewsWhereParameterId}
     * @memberof ListViewsWhereParameter
     */
    id?: ListViewsWhereParameterId;
    /**
     * 
     * @type {ListViewsWhereParameterName}
     * @memberof ListViewsWhereParameter
     */
    name?: ListViewsWhereParameterName;
    /**
     * 
     * @type {ListViewsWhereParameterOrganisationId}
     * @memberof ListViewsWhereParameter
     */
    organisationId?: ListViewsWhereParameterOrganisationId;
    /**
     * 
     * @type {ListViewsWhereParameterPublic}
     * @memberof ListViewsWhereParameter
     */
    _public?: ListViewsWhereParameterPublic;
    /**
     * 
     * @type {ListViewsWhereParameterSlug}
     * @memberof ListViewsWhereParameter
     */
    slug?: ListViewsWhereParameterSlug;
    /**
     * 
     * @type {ListViewsWhereParameterUpdatedAt}
     * @memberof ListViewsWhereParameter
     */
    updatedAt?: ListViewsWhereParameterUpdatedAt;
}

/**
 * Check if a given object implements the ListViewsWhereParameter interface.
 */
export function instanceOfListViewsWhereParameter(value: object): value is ListViewsWhereParameter {
    return true;
}

export function ListViewsWhereParameterFromJSON(json: any): ListViewsWhereParameter {
    return ListViewsWhereParameterFromJSONTyped(json, false);
}

export function ListViewsWhereParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListViewsWhereParameter {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'] == null ? undefined : ListViewsWhereParameterCreatedAtFromJSON(json['created_at']),
        'description': json['description'] == null ? undefined : ListViewsWhereParameterDescriptionFromJSON(json['description']),
        'id': json['id'] == null ? undefined : ListViewsWhereParameterIdFromJSON(json['id']),
        'name': json['name'] == null ? undefined : ListViewsWhereParameterNameFromJSON(json['name']),
        'organisationId': json['organisation_id'] == null ? undefined : ListViewsWhereParameterOrganisationIdFromJSON(json['organisation_id']),
        '_public': json['public'] == null ? undefined : ListViewsWhereParameterPublicFromJSON(json['public']),
        'slug': json['slug'] == null ? undefined : ListViewsWhereParameterSlugFromJSON(json['slug']),
        'updatedAt': json['updated_at'] == null ? undefined : ListViewsWhereParameterUpdatedAtFromJSON(json['updated_at']),
    };
}

export function ListViewsWhereParameterToJSON(json: any): ListViewsWhereParameter {
    return ListViewsWhereParameterToJSONTyped(json, false);
}

export function ListViewsWhereParameterToJSONTyped(value?: ListViewsWhereParameter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': ListViewsWhereParameterCreatedAtToJSON(value['createdAt']),
        'description': ListViewsWhereParameterDescriptionToJSON(value['description']),
        'id': ListViewsWhereParameterIdToJSON(value['id']),
        'name': ListViewsWhereParameterNameToJSON(value['name']),
        'organisation_id': ListViewsWhereParameterOrganisationIdToJSON(value['organisationId']),
        'public': ListViewsWhereParameterPublicToJSON(value['_public']),
        'slug': ListViewsWhereParameterSlugToJSON(value['slug']),
        'updated_at': ListViewsWhereParameterUpdatedAtToJSON(value['updatedAt']),
    };
}

