/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListViewsWhereParameterOrganisationIdAnyOf } from './ListViewsWhereParameterOrganisationIdAnyOf';
import {
    ListViewsWhereParameterOrganisationIdAnyOfFromJSON,
    ListViewsWhereParameterOrganisationIdAnyOfFromJSONTyped,
    ListViewsWhereParameterOrganisationIdAnyOfToJSON,
    ListViewsWhereParameterOrganisationIdAnyOfToJSONTyped,
} from './ListViewsWhereParameterOrganisationIdAnyOf';

/**
 * 
 * @export
 * @interface ListViewsWhereParameterOrganisationId
 */
export interface ListViewsWhereParameterOrganisationId {
    /**
     * The organisation this view belongs to
     * @type {string}
     * @memberof ListViewsWhereParameterOrganisationId
     */
    eq?: string;
    /**
     * The organisation this view belongs to
     * @type {string}
     * @memberof ListViewsWhereParameterOrganisationId
     */
    gt?: string;
    /**
     * The organisation this view belongs to
     * @type {string}
     * @memberof ListViewsWhereParameterOrganisationId
     */
    gte?: string;
    /**
     * Pattern match (ilike). Use % as wildcard.
     * @type {string}
     * @memberof ListViewsWhereParameterOrganisationId
     */
    ilike?: string;
    /**
     * Comma-separated list of values (in)
     * @type {string}
     * @memberof ListViewsWhereParameterOrganisationId
     */
    _in?: string;
    /**
     * Pattern match (like). Use % as wildcard.
     * @type {string}
     * @memberof ListViewsWhereParameterOrganisationId
     */
    like?: string;
    /**
     * The organisation this view belongs to
     * @type {string}
     * @memberof ListViewsWhereParameterOrganisationId
     */
    lt?: string;
    /**
     * The organisation this view belongs to
     * @type {string}
     * @memberof ListViewsWhereParameterOrganisationId
     */
    lte?: string;
    /**
     * The organisation this view belongs to
     * @type {string}
     * @memberof ListViewsWhereParameterOrganisationId
     */
    neq?: string;
    /**
     * Comma-separated list of values (nin)
     * @type {string}
     * @memberof ListViewsWhereParameterOrganisationId
     */
    nin?: string;
    /**
     * Check for NULL (true) or NOT NULL (false)
     * @type {string}
     * @memberof ListViewsWhereParameterOrganisationId
     */
    _null?: ListViewsWhereParameterOrganisationIdNullEnum;
}


/**
 * @export
 */
export const ListViewsWhereParameterOrganisationIdNullEnum = {
    True: 'true',
    False: 'false'
} as const;
export type ListViewsWhereParameterOrganisationIdNullEnum = typeof ListViewsWhereParameterOrganisationIdNullEnum[keyof typeof ListViewsWhereParameterOrganisationIdNullEnum];


/**
 * Check if a given object implements the ListViewsWhereParameterOrganisationId interface.
 */
export function instanceOfListViewsWhereParameterOrganisationId(value: object): value is ListViewsWhereParameterOrganisationId {
    return true;
}

export function ListViewsWhereParameterOrganisationIdFromJSON(json: any): ListViewsWhereParameterOrganisationId {
    return ListViewsWhereParameterOrganisationIdFromJSONTyped(json, false);
}

export function ListViewsWhereParameterOrganisationIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListViewsWhereParameterOrganisationId {
    if (json == null) {
        return json;
    }
    return {
        
        'eq': json['eq'] == null ? undefined : json['eq'],
        'gt': json['gt'] == null ? undefined : json['gt'],
        'gte': json['gte'] == null ? undefined : json['gte'],
        'ilike': json['ilike'] == null ? undefined : json['ilike'],
        '_in': json['in'] == null ? undefined : json['in'],
        'like': json['like'] == null ? undefined : json['like'],
        'lt': json['lt'] == null ? undefined : json['lt'],
        'lte': json['lte'] == null ? undefined : json['lte'],
        'neq': json['neq'] == null ? undefined : json['neq'],
        'nin': json['nin'] == null ? undefined : json['nin'],
        '_null': json['null'] == null ? undefined : json['null'],
    };
}

export function ListViewsWhereParameterOrganisationIdToJSON(json: any): ListViewsWhereParameterOrganisationId {
    return ListViewsWhereParameterOrganisationIdToJSONTyped(json, false);
}

export function ListViewsWhereParameterOrganisationIdToJSONTyped(value?: ListViewsWhereParameterOrganisationId | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'eq': value['eq'],
        'gt': value['gt'],
        'gte': value['gte'],
        'ilike': value['ilike'],
        'in': value['_in'],
        'like': value['like'],
        'lt': value['lt'],
        'lte': value['lte'],
        'neq': value['neq'],
        'nin': value['nin'],
        'null': value['_null'],
    };
}

