/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListWorkersWhereParameterOrganisationIdAnyOf } from './ListWorkersWhereParameterOrganisationIdAnyOf';
import {
    ListWorkersWhereParameterOrganisationIdAnyOfFromJSON,
    ListWorkersWhereParameterOrganisationIdAnyOfFromJSONTyped,
    ListWorkersWhereParameterOrganisationIdAnyOfToJSON,
    ListWorkersWhereParameterOrganisationIdAnyOfToJSONTyped,
} from './ListWorkersWhereParameterOrganisationIdAnyOf';

/**
 * 
 * @export
 * @interface ListWorkersWhereParameterOrganisationId
 */
export interface ListWorkersWhereParameterOrganisationId {
    /**
     * The organisation this worker belongs to
     * @type {string}
     * @memberof ListWorkersWhereParameterOrganisationId
     */
    eq?: string;
    /**
     * The organisation this worker belongs to
     * @type {string}
     * @memberof ListWorkersWhereParameterOrganisationId
     */
    gt?: string;
    /**
     * The organisation this worker belongs to
     * @type {string}
     * @memberof ListWorkersWhereParameterOrganisationId
     */
    gte?: string;
    /**
     * Pattern match (ilike). Use % as wildcard.
     * @type {string}
     * @memberof ListWorkersWhereParameterOrganisationId
     */
    ilike?: string;
    /**
     * Comma-separated list of values (in)
     * @type {string}
     * @memberof ListWorkersWhereParameterOrganisationId
     */
    _in?: string;
    /**
     * Pattern match (like). Use % as wildcard.
     * @type {string}
     * @memberof ListWorkersWhereParameterOrganisationId
     */
    like?: string;
    /**
     * The organisation this worker belongs to
     * @type {string}
     * @memberof ListWorkersWhereParameterOrganisationId
     */
    lt?: string;
    /**
     * The organisation this worker belongs to
     * @type {string}
     * @memberof ListWorkersWhereParameterOrganisationId
     */
    lte?: string;
    /**
     * The organisation this worker belongs to
     * @type {string}
     * @memberof ListWorkersWhereParameterOrganisationId
     */
    neq?: string;
    /**
     * Comma-separated list of values (nin)
     * @type {string}
     * @memberof ListWorkersWhereParameterOrganisationId
     */
    nin?: string;
    /**
     * Check for NULL (true) or NOT NULL (false)
     * @type {string}
     * @memberof ListWorkersWhereParameterOrganisationId
     */
    _null?: ListWorkersWhereParameterOrganisationIdNullEnum;
}


/**
 * @export
 */
export const ListWorkersWhereParameterOrganisationIdNullEnum = {
    True: 'true',
    False: 'false'
} as const;
export type ListWorkersWhereParameterOrganisationIdNullEnum = typeof ListWorkersWhereParameterOrganisationIdNullEnum[keyof typeof ListWorkersWhereParameterOrganisationIdNullEnum];


/**
 * Check if a given object implements the ListWorkersWhereParameterOrganisationId interface.
 */
export function instanceOfListWorkersWhereParameterOrganisationId(value: object): value is ListWorkersWhereParameterOrganisationId {
    return true;
}

export function ListWorkersWhereParameterOrganisationIdFromJSON(json: any): ListWorkersWhereParameterOrganisationId {
    return ListWorkersWhereParameterOrganisationIdFromJSONTyped(json, false);
}

export function ListWorkersWhereParameterOrganisationIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListWorkersWhereParameterOrganisationId {
    if (json == null) {
        return json;
    }
    return {
        
        'eq': json['eq'] == null ? undefined : json['eq'],
        'gt': json['gt'] == null ? undefined : json['gt'],
        'gte': json['gte'] == null ? undefined : json['gte'],
        'ilike': json['ilike'] == null ? undefined : json['ilike'],
        '_in': json['in'] == null ? undefined : json['in'],
        'like': json['like'] == null ? undefined : json['like'],
        'lt': json['lt'] == null ? undefined : json['lt'],
        'lte': json['lte'] == null ? undefined : json['lte'],
        'neq': json['neq'] == null ? undefined : json['neq'],
        'nin': json['nin'] == null ? undefined : json['nin'],
        '_null': json['null'] == null ? undefined : json['null'],
    };
}

export function ListWorkersWhereParameterOrganisationIdToJSON(json: any): ListWorkersWhereParameterOrganisationId {
    return ListWorkersWhereParameterOrganisationIdToJSONTyped(json, false);
}

export function ListWorkersWhereParameterOrganisationIdToJSONTyped(value?: ListWorkersWhereParameterOrganisationId | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'eq': value['eq'],
        'gt': value['gt'],
        'gte': value['gte'],
        'ilike': value['ilike'],
        'in': value['_in'],
        'like': value['like'],
        'lt': value['lt'],
        'lte': value['lte'],
        'neq': value['neq'],
        'nin': value['nin'],
        'null': value['_null'],
    };
}

