/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListUsersOrderParameter
 */
export interface ListUsersOrderParameter {
    /**
     * Sort direction for this field
     * @type {string}
     * @memberof ListUsersOrderParameter
     */
    createdAt?: ListUsersOrderParameterCreatedAtEnum;
    /**
     * Sort direction for this field
     * @type {string}
     * @memberof ListUsersOrderParameter
     */
    handle?: ListUsersOrderParameterHandleEnum;
    /**
     * Sort direction for this field
     * @type {string}
     * @memberof ListUsersOrderParameter
     */
    id?: ListUsersOrderParameterIdEnum;
    /**
     * Sort direction for this field
     * @type {string}
     * @memberof ListUsersOrderParameter
     */
    publicEmail?: ListUsersOrderParameterPublicEmailEnum;
    /**
     * Sort direction for this field
     * @type {string}
     * @memberof ListUsersOrderParameter
     */
    publicName?: ListUsersOrderParameterPublicNameEnum;
    /**
     * Sort direction for this field
     * @type {string}
     * @memberof ListUsersOrderParameter
     */
    updatedAt?: ListUsersOrderParameterUpdatedAtEnum;
}


/**
 * @export
 */
export const ListUsersOrderParameterCreatedAtEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type ListUsersOrderParameterCreatedAtEnum = typeof ListUsersOrderParameterCreatedAtEnum[keyof typeof ListUsersOrderParameterCreatedAtEnum];

/**
 * @export
 */
export const ListUsersOrderParameterHandleEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type ListUsersOrderParameterHandleEnum = typeof ListUsersOrderParameterHandleEnum[keyof typeof ListUsersOrderParameterHandleEnum];

/**
 * @export
 */
export const ListUsersOrderParameterIdEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type ListUsersOrderParameterIdEnum = typeof ListUsersOrderParameterIdEnum[keyof typeof ListUsersOrderParameterIdEnum];

/**
 * @export
 */
export const ListUsersOrderParameterPublicEmailEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type ListUsersOrderParameterPublicEmailEnum = typeof ListUsersOrderParameterPublicEmailEnum[keyof typeof ListUsersOrderParameterPublicEmailEnum];

/**
 * @export
 */
export const ListUsersOrderParameterPublicNameEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type ListUsersOrderParameterPublicNameEnum = typeof ListUsersOrderParameterPublicNameEnum[keyof typeof ListUsersOrderParameterPublicNameEnum];

/**
 * @export
 */
export const ListUsersOrderParameterUpdatedAtEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type ListUsersOrderParameterUpdatedAtEnum = typeof ListUsersOrderParameterUpdatedAtEnum[keyof typeof ListUsersOrderParameterUpdatedAtEnum];


/**
 * Check if a given object implements the ListUsersOrderParameter interface.
 */
export function instanceOfListUsersOrderParameter(value: object): value is ListUsersOrderParameter {
    return true;
}

export function ListUsersOrderParameterFromJSON(json: any): ListUsersOrderParameter {
    return ListUsersOrderParameterFromJSONTyped(json, false);
}

export function ListUsersOrderParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListUsersOrderParameter {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'handle': json['handle'] == null ? undefined : json['handle'],
        'id': json['id'] == null ? undefined : json['id'],
        'publicEmail': json['public_email'] == null ? undefined : json['public_email'],
        'publicName': json['public_name'] == null ? undefined : json['public_name'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

export function ListUsersOrderParameterToJSON(json: any): ListUsersOrderParameter {
    return ListUsersOrderParameterToJSONTyped(json, false);
}

export function ListUsersOrderParameterToJSONTyped(value?: ListUsersOrderParameter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'],
        'handle': value['handle'],
        'id': value['id'],
        'public_email': value['publicEmail'],
        'public_name': value['publicName'],
        'updated_at': value['updatedAt'],
    };
}

