/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListOrganisationsWhereParameterNameAnyOf } from './ListOrganisationsWhereParameterNameAnyOf';
import {
    ListOrganisationsWhereParameterNameAnyOfFromJSON,
    ListOrganisationsWhereParameterNameAnyOfFromJSONTyped,
    ListOrganisationsWhereParameterNameAnyOfToJSON,
    ListOrganisationsWhereParameterNameAnyOfToJSONTyped,
} from './ListOrganisationsWhereParameterNameAnyOf';

/**
 * 
 * @export
 * @interface ListOrganisationsWhereParameterName
 */
export interface ListOrganisationsWhereParameterName {
    /**
     * The display name of the organisation
     * @type {string}
     * @memberof ListOrganisationsWhereParameterName
     */
    eq?: string;
    /**
     * The display name of the organisation
     * @type {string}
     * @memberof ListOrganisationsWhereParameterName
     */
    gt?: string;
    /**
     * The display name of the organisation
     * @type {string}
     * @memberof ListOrganisationsWhereParameterName
     */
    gte?: string;
    /**
     * Pattern match (ilike). Use % as wildcard.
     * @type {string}
     * @memberof ListOrganisationsWhereParameterName
     */
    ilike?: string;
    /**
     * Comma-separated list of values (in)
     * @type {string}
     * @memberof ListOrganisationsWhereParameterName
     */
    _in?: string;
    /**
     * Pattern match (like). Use % as wildcard.
     * @type {string}
     * @memberof ListOrganisationsWhereParameterName
     */
    like?: string;
    /**
     * The display name of the organisation
     * @type {string}
     * @memberof ListOrganisationsWhereParameterName
     */
    lt?: string;
    /**
     * The display name of the organisation
     * @type {string}
     * @memberof ListOrganisationsWhereParameterName
     */
    lte?: string;
    /**
     * The display name of the organisation
     * @type {string}
     * @memberof ListOrganisationsWhereParameterName
     */
    neq?: string;
    /**
     * Comma-separated list of values (nin)
     * @type {string}
     * @memberof ListOrganisationsWhereParameterName
     */
    nin?: string;
    /**
     * Check for NULL (true) or NOT NULL (false)
     * @type {string}
     * @memberof ListOrganisationsWhereParameterName
     */
    _null?: ListOrganisationsWhereParameterNameNullEnum;
}


/**
 * @export
 */
export const ListOrganisationsWhereParameterNameNullEnum = {
    True: 'true',
    False: 'false'
} as const;
export type ListOrganisationsWhereParameterNameNullEnum = typeof ListOrganisationsWhereParameterNameNullEnum[keyof typeof ListOrganisationsWhereParameterNameNullEnum];


/**
 * Check if a given object implements the ListOrganisationsWhereParameterName interface.
 */
export function instanceOfListOrganisationsWhereParameterName(value: object): value is ListOrganisationsWhereParameterName {
    return true;
}

export function ListOrganisationsWhereParameterNameFromJSON(json: any): ListOrganisationsWhereParameterName {
    return ListOrganisationsWhereParameterNameFromJSONTyped(json, false);
}

export function ListOrganisationsWhereParameterNameFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListOrganisationsWhereParameterName {
    if (json == null) {
        return json;
    }
    return {
        
        'eq': json['eq'] == null ? undefined : json['eq'],
        'gt': json['gt'] == null ? undefined : json['gt'],
        'gte': json['gte'] == null ? undefined : json['gte'],
        'ilike': json['ilike'] == null ? undefined : json['ilike'],
        '_in': json['in'] == null ? undefined : json['in'],
        'like': json['like'] == null ? undefined : json['like'],
        'lt': json['lt'] == null ? undefined : json['lt'],
        'lte': json['lte'] == null ? undefined : json['lte'],
        'neq': json['neq'] == null ? undefined : json['neq'],
        'nin': json['nin'] == null ? undefined : json['nin'],
        '_null': json['null'] == null ? undefined : json['null'],
    };
}

export function ListOrganisationsWhereParameterNameToJSON(json: any): ListOrganisationsWhereParameterName {
    return ListOrganisationsWhereParameterNameToJSONTyped(json, false);
}

export function ListOrganisationsWhereParameterNameToJSONTyped(value?: ListOrganisationsWhereParameterName | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'eq': value['eq'],
        'gt': value['gt'],
        'gte': value['gte'],
        'ilike': value['ilike'],
        'in': value['_in'],
        'like': value['like'],
        'lt': value['lt'],
        'lte': value['lte'],
        'neq': value['neq'],
        'nin': value['nin'],
        'null': value['_null'],
    };
}

