/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListTokensWhereParameterLastUsedAt } from './ListTokensWhereParameterLastUsedAt';
import {
    ListTokensWhereParameterLastUsedAtFromJSON,
    ListTokensWhereParameterLastUsedAtFromJSONTyped,
    ListTokensWhereParameterLastUsedAtToJSON,
    ListTokensWhereParameterLastUsedAtToJSONTyped,
} from './ListTokensWhereParameterLastUsedAt';
import type { ListTokensWhereParameterScopes } from './ListTokensWhereParameterScopes';
import {
    ListTokensWhereParameterScopesFromJSON,
    ListTokensWhereParameterScopesFromJSONTyped,
    ListTokensWhereParameterScopesToJSON,
    ListTokensWhereParameterScopesToJSONTyped,
} from './ListTokensWhereParameterScopes';
import type { ListTokensWhereParameterActive } from './ListTokensWhereParameterActive';
import {
    ListTokensWhereParameterActiveFromJSON,
    ListTokensWhereParameterActiveFromJSONTyped,
    ListTokensWhereParameterActiveToJSON,
    ListTokensWhereParameterActiveToJSONTyped,
} from './ListTokensWhereParameterActive';
import type { ListTokensWhereParameterOrganisationId } from './ListTokensWhereParameterOrganisationId';
import {
    ListTokensWhereParameterOrganisationIdFromJSON,
    ListTokensWhereParameterOrganisationIdFromJSONTyped,
    ListTokensWhereParameterOrganisationIdToJSON,
    ListTokensWhereParameterOrganisationIdToJSONTyped,
} from './ListTokensWhereParameterOrganisationId';
import type { ListTokensWhereParameterExpiresAt } from './ListTokensWhereParameterExpiresAt';
import {
    ListTokensWhereParameterExpiresAtFromJSON,
    ListTokensWhereParameterExpiresAtFromJSONTyped,
    ListTokensWhereParameterExpiresAtToJSON,
    ListTokensWhereParameterExpiresAtToJSONTyped,
} from './ListTokensWhereParameterExpiresAt';
import type { ListTokensWhereParameterCreatedAt } from './ListTokensWhereParameterCreatedAt';
import {
    ListTokensWhereParameterCreatedAtFromJSON,
    ListTokensWhereParameterCreatedAtFromJSONTyped,
    ListTokensWhereParameterCreatedAtToJSON,
    ListTokensWhereParameterCreatedAtToJSONTyped,
} from './ListTokensWhereParameterCreatedAt';
import type { ListTokensWhereParameterId } from './ListTokensWhereParameterId';
import {
    ListTokensWhereParameterIdFromJSON,
    ListTokensWhereParameterIdFromJSONTyped,
    ListTokensWhereParameterIdToJSON,
    ListTokensWhereParameterIdToJSONTyped,
} from './ListTokensWhereParameterId';
import type { ListTokensWhereParameterName } from './ListTokensWhereParameterName';
import {
    ListTokensWhereParameterNameFromJSON,
    ListTokensWhereParameterNameFromJSONTyped,
    ListTokensWhereParameterNameToJSON,
    ListTokensWhereParameterNameToJSONTyped,
} from './ListTokensWhereParameterName';

/**
 * 
 * @export
 * @interface ListTokensWhereParameter
 */
export interface ListTokensWhereParameter {
    /**
     * 
     * @type {ListTokensWhereParameterActive}
     * @memberof ListTokensWhereParameter
     */
    active?: ListTokensWhereParameterActive;
    /**
     * 
     * @type {ListTokensWhereParameterCreatedAt}
     * @memberof ListTokensWhereParameter
     */
    createdAt?: ListTokensWhereParameterCreatedAt;
    /**
     * 
     * @type {ListTokensWhereParameterExpiresAt}
     * @memberof ListTokensWhereParameter
     */
    expiresAt?: ListTokensWhereParameterExpiresAt;
    /**
     * 
     * @type {ListTokensWhereParameterId}
     * @memberof ListTokensWhereParameter
     */
    id?: ListTokensWhereParameterId;
    /**
     * 
     * @type {ListTokensWhereParameterLastUsedAt}
     * @memberof ListTokensWhereParameter
     */
    lastUsedAt?: ListTokensWhereParameterLastUsedAt;
    /**
     * 
     * @type {ListTokensWhereParameterName}
     * @memberof ListTokensWhereParameter
     */
    name?: ListTokensWhereParameterName;
    /**
     * 
     * @type {ListTokensWhereParameterOrganisationId}
     * @memberof ListTokensWhereParameter
     */
    organisationId?: ListTokensWhereParameterOrganisationId;
    /**
     * 
     * @type {ListTokensWhereParameterScopes}
     * @memberof ListTokensWhereParameter
     */
    scopes?: ListTokensWhereParameterScopes;
    /**
     * 
     * @type {ListTokensWhereParameterLastUsedAt}
     * @memberof ListTokensWhereParameter
     */
    updatedAt?: ListTokensWhereParameterLastUsedAt;
}

/**
 * Check if a given object implements the ListTokensWhereParameter interface.
 */
export function instanceOfListTokensWhereParameter(value: object): value is ListTokensWhereParameter {
    return true;
}

export function ListTokensWhereParameterFromJSON(json: any): ListTokensWhereParameter {
    return ListTokensWhereParameterFromJSONTyped(json, false);
}

export function ListTokensWhereParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListTokensWhereParameter {
    if (json == null) {
        return json;
    }
    return {
        
        'active': json['active'] == null ? undefined : ListTokensWhereParameterActiveFromJSON(json['active']),
        'createdAt': json['created_at'] == null ? undefined : ListTokensWhereParameterCreatedAtFromJSON(json['created_at']),
        'expiresAt': json['expires_at'] == null ? undefined : ListTokensWhereParameterExpiresAtFromJSON(json['expires_at']),
        'id': json['id'] == null ? undefined : ListTokensWhereParameterIdFromJSON(json['id']),
        'lastUsedAt': json['last_used_at'] == null ? undefined : ListTokensWhereParameterLastUsedAtFromJSON(json['last_used_at']),
        'name': json['name'] == null ? undefined : ListTokensWhereParameterNameFromJSON(json['name']),
        'organisationId': json['organisation_id'] == null ? undefined : ListTokensWhereParameterOrganisationIdFromJSON(json['organisation_id']),
        'scopes': json['scopes'] == null ? undefined : ListTokensWhereParameterScopesFromJSON(json['scopes']),
        'updatedAt': json['updated_at'] == null ? undefined : ListTokensWhereParameterLastUsedAtFromJSON(json['updated_at']),
    };
}

export function ListTokensWhereParameterToJSON(json: any): ListTokensWhereParameter {
    return ListTokensWhereParameterToJSONTyped(json, false);
}

export function ListTokensWhereParameterToJSONTyped(value?: ListTokensWhereParameter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'active': ListTokensWhereParameterActiveToJSON(value['active']),
        'created_at': ListTokensWhereParameterCreatedAtToJSON(value['createdAt']),
        'expires_at': ListTokensWhereParameterExpiresAtToJSON(value['expiresAt']),
        'id': ListTokensWhereParameterIdToJSON(value['id']),
        'last_used_at': ListTokensWhereParameterLastUsedAtToJSON(value['lastUsedAt']),
        'name': ListTokensWhereParameterNameToJSON(value['name']),
        'organisation_id': ListTokensWhereParameterOrganisationIdToJSON(value['organisationId']),
        'scopes': ListTokensWhereParameterScopesToJSON(value['scopes']),
        'updated_at': ListTokensWhereParameterLastUsedAtToJSON(value['updatedAt']),
    };
}

