/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListViewsWhereParameterPublicAnyOf } from './ListViewsWhereParameterPublicAnyOf';
import {
    ListViewsWhereParameterPublicAnyOfFromJSON,
    ListViewsWhereParameterPublicAnyOfFromJSONTyped,
    ListViewsWhereParameterPublicAnyOfToJSON,
    ListViewsWhereParameterPublicAnyOfToJSONTyped,
} from './ListViewsWhereParameterPublicAnyOf';

/**
 * 
 * @export
 * @interface ListViewsWhereParameterPublic
 */
export interface ListViewsWhereParameterPublic {
    /**
     * Whether this view is publicly visible to other organisations
     * @type {boolean}
     * @memberof ListViewsWhereParameterPublic
     */
    eq?: boolean;
    /**
     * Whether this view is publicly visible to other organisations
     * @type {boolean}
     * @memberof ListViewsWhereParameterPublic
     */
    gt?: boolean;
    /**
     * Whether this view is publicly visible to other organisations
     * @type {boolean}
     * @memberof ListViewsWhereParameterPublic
     */
    gte?: boolean;
    /**
     * Pattern match (ilike). Use % as wildcard.
     * @type {string}
     * @memberof ListViewsWhereParameterPublic
     */
    ilike?: string;
    /**
     * Comma-separated list of values (in)
     * @type {string}
     * @memberof ListViewsWhereParameterPublic
     */
    _in?: string;
    /**
     * Pattern match (like). Use % as wildcard.
     * @type {string}
     * @memberof ListViewsWhereParameterPublic
     */
    like?: string;
    /**
     * Whether this view is publicly visible to other organisations
     * @type {boolean}
     * @memberof ListViewsWhereParameterPublic
     */
    lt?: boolean;
    /**
     * Whether this view is publicly visible to other organisations
     * @type {boolean}
     * @memberof ListViewsWhereParameterPublic
     */
    lte?: boolean;
    /**
     * Whether this view is publicly visible to other organisations
     * @type {boolean}
     * @memberof ListViewsWhereParameterPublic
     */
    neq?: boolean;
    /**
     * Comma-separated list of values (nin)
     * @type {string}
     * @memberof ListViewsWhereParameterPublic
     */
    nin?: string;
    /**
     * Check for NULL (true) or NOT NULL (false)
     * @type {string}
     * @memberof ListViewsWhereParameterPublic
     */
    _null?: ListViewsWhereParameterPublicNullEnum;
}


/**
 * @export
 */
export const ListViewsWhereParameterPublicNullEnum = {
    True: 'true',
    False: 'false'
} as const;
export type ListViewsWhereParameterPublicNullEnum = typeof ListViewsWhereParameterPublicNullEnum[keyof typeof ListViewsWhereParameterPublicNullEnum];


/**
 * Check if a given object implements the ListViewsWhereParameterPublic interface.
 */
export function instanceOfListViewsWhereParameterPublic(value: object): value is ListViewsWhereParameterPublic {
    return true;
}

export function ListViewsWhereParameterPublicFromJSON(json: any): ListViewsWhereParameterPublic {
    return ListViewsWhereParameterPublicFromJSONTyped(json, false);
}

export function ListViewsWhereParameterPublicFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListViewsWhereParameterPublic {
    if (json == null) {
        return json;
    }
    return {
        
        'eq': json['eq'] == null ? undefined : json['eq'],
        'gt': json['gt'] == null ? undefined : json['gt'],
        'gte': json['gte'] == null ? undefined : json['gte'],
        'ilike': json['ilike'] == null ? undefined : json['ilike'],
        '_in': json['in'] == null ? undefined : json['in'],
        'like': json['like'] == null ? undefined : json['like'],
        'lt': json['lt'] == null ? undefined : json['lt'],
        'lte': json['lte'] == null ? undefined : json['lte'],
        'neq': json['neq'] == null ? undefined : json['neq'],
        'nin': json['nin'] == null ? undefined : json['nin'],
        '_null': json['null'] == null ? undefined : json['null'],
    };
}

export function ListViewsWhereParameterPublicToJSON(json: any): ListViewsWhereParameterPublic {
    return ListViewsWhereParameterPublicToJSONTyped(json, false);
}

export function ListViewsWhereParameterPublicToJSONTyped(value?: ListViewsWhereParameterPublic | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'eq': value['eq'],
        'gt': value['gt'],
        'gte': value['gte'],
        'ilike': value['ilike'],
        'in': value['_in'],
        'like': value['like'],
        'lt': value['lt'],
        'lte': value['lte'],
        'neq': value['neq'],
        'nin': value['nin'],
        'null': value['_null'],
    };
}

