/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListTokensWhereParameterOrganisationIdAnyOf
 */
export interface ListTokensWhereParameterOrganisationIdAnyOf {
    /**
     * The organisation this token belongs to
     * @type {string}
     * @memberof ListTokensWhereParameterOrganisationIdAnyOf
     */
    eq?: string;
    /**
     * The organisation this token belongs to
     * @type {string}
     * @memberof ListTokensWhereParameterOrganisationIdAnyOf
     */
    gt?: string;
    /**
     * The organisation this token belongs to
     * @type {string}
     * @memberof ListTokensWhereParameterOrganisationIdAnyOf
     */
    gte?: string;
    /**
     * Pattern match (ilike). Use % as wildcard.
     * @type {string}
     * @memberof ListTokensWhereParameterOrganisationIdAnyOf
     */
    ilike?: string;
    /**
     * Comma-separated list of values (in)
     * @type {string}
     * @memberof ListTokensWhereParameterOrganisationIdAnyOf
     */
    _in?: string;
    /**
     * Pattern match (like). Use % as wildcard.
     * @type {string}
     * @memberof ListTokensWhereParameterOrganisationIdAnyOf
     */
    like?: string;
    /**
     * The organisation this token belongs to
     * @type {string}
     * @memberof ListTokensWhereParameterOrganisationIdAnyOf
     */
    lt?: string;
    /**
     * The organisation this token belongs to
     * @type {string}
     * @memberof ListTokensWhereParameterOrganisationIdAnyOf
     */
    lte?: string;
    /**
     * The organisation this token belongs to
     * @type {string}
     * @memberof ListTokensWhereParameterOrganisationIdAnyOf
     */
    neq?: string;
    /**
     * Comma-separated list of values (nin)
     * @type {string}
     * @memberof ListTokensWhereParameterOrganisationIdAnyOf
     */
    nin?: string;
    /**
     * Check for NULL (true) or NOT NULL (false)
     * @type {string}
     * @memberof ListTokensWhereParameterOrganisationIdAnyOf
     */
    _null?: ListTokensWhereParameterOrganisationIdAnyOfNullEnum;
}


/**
 * @export
 */
export const ListTokensWhereParameterOrganisationIdAnyOfNullEnum = {
    True: 'true',
    False: 'false'
} as const;
export type ListTokensWhereParameterOrganisationIdAnyOfNullEnum = typeof ListTokensWhereParameterOrganisationIdAnyOfNullEnum[keyof typeof ListTokensWhereParameterOrganisationIdAnyOfNullEnum];


/**
 * Check if a given object implements the ListTokensWhereParameterOrganisationIdAnyOf interface.
 */
export function instanceOfListTokensWhereParameterOrganisationIdAnyOf(value: object): value is ListTokensWhereParameterOrganisationIdAnyOf {
    return true;
}

export function ListTokensWhereParameterOrganisationIdAnyOfFromJSON(json: any): ListTokensWhereParameterOrganisationIdAnyOf {
    return ListTokensWhereParameterOrganisationIdAnyOfFromJSONTyped(json, false);
}

export function ListTokensWhereParameterOrganisationIdAnyOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListTokensWhereParameterOrganisationIdAnyOf {
    if (json == null) {
        return json;
    }
    return {
        
        'eq': json['eq'] == null ? undefined : json['eq'],
        'gt': json['gt'] == null ? undefined : json['gt'],
        'gte': json['gte'] == null ? undefined : json['gte'],
        'ilike': json['ilike'] == null ? undefined : json['ilike'],
        '_in': json['in'] == null ? undefined : json['in'],
        'like': json['like'] == null ? undefined : json['like'],
        'lt': json['lt'] == null ? undefined : json['lt'],
        'lte': json['lte'] == null ? undefined : json['lte'],
        'neq': json['neq'] == null ? undefined : json['neq'],
        'nin': json['nin'] == null ? undefined : json['nin'],
        '_null': json['null'] == null ? undefined : json['null'],
    };
}

export function ListTokensWhereParameterOrganisationIdAnyOfToJSON(json: any): ListTokensWhereParameterOrganisationIdAnyOf {
    return ListTokensWhereParameterOrganisationIdAnyOfToJSONTyped(json, false);
}

export function ListTokensWhereParameterOrganisationIdAnyOfToJSONTyped(value?: ListTokensWhereParameterOrganisationIdAnyOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'eq': value['eq'],
        'gt': value['gt'],
        'gte': value['gte'],
        'ilike': value['ilike'],
        'in': value['_in'],
        'like': value['like'],
        'lt': value['lt'],
        'lte': value['lte'],
        'neq': value['neq'],
        'nin': value['nin'],
        'null': value['_null'],
    };
}

