/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListUsersWhereParameterHandleAnyOf } from './ListUsersWhereParameterHandleAnyOf';
import {
    ListUsersWhereParameterHandleAnyOfFromJSON,
    ListUsersWhereParameterHandleAnyOfFromJSONTyped,
    ListUsersWhereParameterHandleAnyOfToJSON,
    ListUsersWhereParameterHandleAnyOfToJSONTyped,
} from './ListUsersWhereParameterHandleAnyOf';

/**
 * 
 * @export
 * @interface ListUsersWhereParameterHandle
 */
export interface ListUsersWhereParameterHandle {
    /**
     * The unique public handle of the user
     * @type {string}
     * @memberof ListUsersWhereParameterHandle
     */
    eq?: string;
    /**
     * The unique public handle of the user
     * @type {string}
     * @memberof ListUsersWhereParameterHandle
     */
    gt?: string;
    /**
     * The unique public handle of the user
     * @type {string}
     * @memberof ListUsersWhereParameterHandle
     */
    gte?: string;
    /**
     * Pattern match (ilike). Use % as wildcard.
     * @type {string}
     * @memberof ListUsersWhereParameterHandle
     */
    ilike?: string;
    /**
     * Comma-separated list of values (in)
     * @type {string}
     * @memberof ListUsersWhereParameterHandle
     */
    _in?: string;
    /**
     * Pattern match (like). Use % as wildcard.
     * @type {string}
     * @memberof ListUsersWhereParameterHandle
     */
    like?: string;
    /**
     * The unique public handle of the user
     * @type {string}
     * @memberof ListUsersWhereParameterHandle
     */
    lt?: string;
    /**
     * The unique public handle of the user
     * @type {string}
     * @memberof ListUsersWhereParameterHandle
     */
    lte?: string;
    /**
     * The unique public handle of the user
     * @type {string}
     * @memberof ListUsersWhereParameterHandle
     */
    neq?: string;
    /**
     * Comma-separated list of values (nin)
     * @type {string}
     * @memberof ListUsersWhereParameterHandle
     */
    nin?: string;
    /**
     * Check for NULL (true) or NOT NULL (false)
     * @type {string}
     * @memberof ListUsersWhereParameterHandle
     */
    _null?: ListUsersWhereParameterHandleNullEnum;
}


/**
 * @export
 */
export const ListUsersWhereParameterHandleNullEnum = {
    True: 'true',
    False: 'false'
} as const;
export type ListUsersWhereParameterHandleNullEnum = typeof ListUsersWhereParameterHandleNullEnum[keyof typeof ListUsersWhereParameterHandleNullEnum];


/**
 * Check if a given object implements the ListUsersWhereParameterHandle interface.
 */
export function instanceOfListUsersWhereParameterHandle(value: object): value is ListUsersWhereParameterHandle {
    return true;
}

export function ListUsersWhereParameterHandleFromJSON(json: any): ListUsersWhereParameterHandle {
    return ListUsersWhereParameterHandleFromJSONTyped(json, false);
}

export function ListUsersWhereParameterHandleFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListUsersWhereParameterHandle {
    if (json == null) {
        return json;
    }
    return {
        
        'eq': json['eq'] == null ? undefined : json['eq'],
        'gt': json['gt'] == null ? undefined : json['gt'],
        'gte': json['gte'] == null ? undefined : json['gte'],
        'ilike': json['ilike'] == null ? undefined : json['ilike'],
        '_in': json['in'] == null ? undefined : json['in'],
        'like': json['like'] == null ? undefined : json['like'],
        'lt': json['lt'] == null ? undefined : json['lt'],
        'lte': json['lte'] == null ? undefined : json['lte'],
        'neq': json['neq'] == null ? undefined : json['neq'],
        'nin': json['nin'] == null ? undefined : json['nin'],
        '_null': json['null'] == null ? undefined : json['null'],
    };
}

export function ListUsersWhereParameterHandleToJSON(json: any): ListUsersWhereParameterHandle {
    return ListUsersWhereParameterHandleToJSONTyped(json, false);
}

export function ListUsersWhereParameterHandleToJSONTyped(value?: ListUsersWhereParameterHandle | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'eq': value['eq'],
        'gt': value['gt'],
        'gte': value['gte'],
        'ilike': value['ilike'],
        'in': value['_in'],
        'like': value['like'],
        'lt': value['lt'],
        'lte': value['lte'],
        'neq': value['neq'],
        'nin': value['nin'],
        'null': value['_null'],
    };
}

