/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListWorkers200ResponseInner
 */
export interface ListWorkers200ResponseInner {
    /**
     * The date and time the worker was created
     * @type {Date}
     * @memberof ListWorkers200ResponseInner
     */
    createdAt?: Date;
    /**
     * A description of the worker
     * @type {string}
     * @memberof ListWorkers200ResponseInner
     */
    description?: string | null;
    /**
     * The unique identifier of the worker
     * @type {string}
     * @memberof ListWorkers200ResponseInner
     */
    id?: string;
    /**
     * The display name of the worker
     * @type {string}
     * @memberof ListWorkers200ResponseInner
     */
    name?: string;
    /**
     * The organisation this worker belongs to
     * @type {string}
     * @memberof ListWorkers200ResponseInner
     */
    organisationId?: string;
    /**
     * Whether this worker is publicly visible to other organisations
     * @type {boolean}
     * @memberof ListWorkers200ResponseInner
     */
    _public?: boolean;
    /**
     * The composite slug in organisation:worker format
     * @type {string}
     * @memberof ListWorkers200ResponseInner
     */
    slug?: string;
    /**
     * The date and time the worker was last updated
     * @type {Date}
     * @memberof ListWorkers200ResponseInner
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the ListWorkers200ResponseInner interface.
 */
export function instanceOfListWorkers200ResponseInner(value: object): value is ListWorkers200ResponseInner {
    return true;
}

export function ListWorkers200ResponseInnerFromJSON(json: any): ListWorkers200ResponseInner {
    return ListWorkers200ResponseInnerFromJSONTyped(json, false);
}

export function ListWorkers200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListWorkers200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'organisationId': json['organisation_id'] == null ? undefined : json['organisation_id'],
        '_public': json['public'] == null ? undefined : json['public'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function ListWorkers200ResponseInnerToJSON(json: any): ListWorkers200ResponseInner {
    return ListWorkers200ResponseInnerToJSONTyped(json, false);
}

export function ListWorkers200ResponseInnerToJSONTyped(value?: ListWorkers200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'description': value['description'],
        'id': value['id'],
        'name': value['name'],
        'organisation_id': value['organisationId'],
        'public': value['_public'],
        'slug': value['slug'],
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

