/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListOrganisationsWhereParameterPublic } from './ListOrganisationsWhereParameterPublic';
import {
    ListOrganisationsWhereParameterPublicFromJSON,
    ListOrganisationsWhereParameterPublicFromJSONTyped,
    ListOrganisationsWhereParameterPublicToJSON,
    ListOrganisationsWhereParameterPublicToJSONTyped,
} from './ListOrganisationsWhereParameterPublic';
import type { ListOrganisationsWhereParameterUpdatedAt } from './ListOrganisationsWhereParameterUpdatedAt';
import {
    ListOrganisationsWhereParameterUpdatedAtFromJSON,
    ListOrganisationsWhereParameterUpdatedAtFromJSONTyped,
    ListOrganisationsWhereParameterUpdatedAtToJSON,
    ListOrganisationsWhereParameterUpdatedAtToJSONTyped,
} from './ListOrganisationsWhereParameterUpdatedAt';
import type { ListOrganisationsWhereParameterCreatedAt } from './ListOrganisationsWhereParameterCreatedAt';
import {
    ListOrganisationsWhereParameterCreatedAtFromJSON,
    ListOrganisationsWhereParameterCreatedAtFromJSONTyped,
    ListOrganisationsWhereParameterCreatedAtToJSON,
    ListOrganisationsWhereParameterCreatedAtToJSONTyped,
} from './ListOrganisationsWhereParameterCreatedAt';
import type { ListOrganisationsWhereParameterName } from './ListOrganisationsWhereParameterName';
import {
    ListOrganisationsWhereParameterNameFromJSON,
    ListOrganisationsWhereParameterNameFromJSONTyped,
    ListOrganisationsWhereParameterNameToJSON,
    ListOrganisationsWhereParameterNameToJSONTyped,
} from './ListOrganisationsWhereParameterName';
import type { ListOrganisationsWhereParameterId } from './ListOrganisationsWhereParameterId';
import {
    ListOrganisationsWhereParameterIdFromJSON,
    ListOrganisationsWhereParameterIdFromJSONTyped,
    ListOrganisationsWhereParameterIdToJSON,
    ListOrganisationsWhereParameterIdToJSONTyped,
} from './ListOrganisationsWhereParameterId';
import type { ListOrganisationsWhereParameterSlug } from './ListOrganisationsWhereParameterSlug';
import {
    ListOrganisationsWhereParameterSlugFromJSON,
    ListOrganisationsWhereParameterSlugFromJSONTyped,
    ListOrganisationsWhereParameterSlugToJSON,
    ListOrganisationsWhereParameterSlugToJSONTyped,
} from './ListOrganisationsWhereParameterSlug';

/**
 * 
 * @export
 * @interface ListOrganisationsWhereParameter
 */
export interface ListOrganisationsWhereParameter {
    /**
     * 
     * @type {ListOrganisationsWhereParameterCreatedAt}
     * @memberof ListOrganisationsWhereParameter
     */
    createdAt?: ListOrganisationsWhereParameterCreatedAt;
    /**
     * 
     * @type {ListOrganisationsWhereParameterId}
     * @memberof ListOrganisationsWhereParameter
     */
    id?: ListOrganisationsWhereParameterId;
    /**
     * 
     * @type {ListOrganisationsWhereParameterName}
     * @memberof ListOrganisationsWhereParameter
     */
    name?: ListOrganisationsWhereParameterName;
    /**
     * 
     * @type {ListOrganisationsWhereParameterPublic}
     * @memberof ListOrganisationsWhereParameter
     */
    _public?: ListOrganisationsWhereParameterPublic;
    /**
     * 
     * @type {ListOrganisationsWhereParameterSlug}
     * @memberof ListOrganisationsWhereParameter
     */
    slug?: ListOrganisationsWhereParameterSlug;
    /**
     * 
     * @type {ListOrganisationsWhereParameterUpdatedAt}
     * @memberof ListOrganisationsWhereParameter
     */
    updatedAt?: ListOrganisationsWhereParameterUpdatedAt;
}

/**
 * Check if a given object implements the ListOrganisationsWhereParameter interface.
 */
export function instanceOfListOrganisationsWhereParameter(value: object): value is ListOrganisationsWhereParameter {
    return true;
}

export function ListOrganisationsWhereParameterFromJSON(json: any): ListOrganisationsWhereParameter {
    return ListOrganisationsWhereParameterFromJSONTyped(json, false);
}

export function ListOrganisationsWhereParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListOrganisationsWhereParameter {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'] == null ? undefined : ListOrganisationsWhereParameterCreatedAtFromJSON(json['created_at']),
        'id': json['id'] == null ? undefined : ListOrganisationsWhereParameterIdFromJSON(json['id']),
        'name': json['name'] == null ? undefined : ListOrganisationsWhereParameterNameFromJSON(json['name']),
        '_public': json['public'] == null ? undefined : ListOrganisationsWhereParameterPublicFromJSON(json['public']),
        'slug': json['slug'] == null ? undefined : ListOrganisationsWhereParameterSlugFromJSON(json['slug']),
        'updatedAt': json['updated_at'] == null ? undefined : ListOrganisationsWhereParameterUpdatedAtFromJSON(json['updated_at']),
    };
}

export function ListOrganisationsWhereParameterToJSON(json: any): ListOrganisationsWhereParameter {
    return ListOrganisationsWhereParameterToJSONTyped(json, false);
}

export function ListOrganisationsWhereParameterToJSONTyped(value?: ListOrganisationsWhereParameter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': ListOrganisationsWhereParameterCreatedAtToJSON(value['createdAt']),
        'id': ListOrganisationsWhereParameterIdToJSON(value['id']),
        'name': ListOrganisationsWhereParameterNameToJSON(value['name']),
        'public': ListOrganisationsWhereParameterPublicToJSON(value['_public']),
        'slug': ListOrganisationsWhereParameterSlugToJSON(value['slug']),
        'updated_at': ListOrganisationsWhereParameterUpdatedAtToJSON(value['updatedAt']),
    };
}

