/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListDatabasesWhereParameterOrganisationIdAnyOf
 */
export interface ListDatabasesWhereParameterOrganisationIdAnyOf {
    /**
     * The organisation this database belongs to
     * @type {string}
     * @memberof ListDatabasesWhereParameterOrganisationIdAnyOf
     */
    eq?: string;
    /**
     * The organisation this database belongs to
     * @type {string}
     * @memberof ListDatabasesWhereParameterOrganisationIdAnyOf
     */
    gt?: string;
    /**
     * The organisation this database belongs to
     * @type {string}
     * @memberof ListDatabasesWhereParameterOrganisationIdAnyOf
     */
    gte?: string;
    /**
     * Pattern match (ilike). Use % as wildcard.
     * @type {string}
     * @memberof ListDatabasesWhereParameterOrganisationIdAnyOf
     */
    ilike?: string;
    /**
     * Comma-separated list of values (in)
     * @type {string}
     * @memberof ListDatabasesWhereParameterOrganisationIdAnyOf
     */
    _in?: string;
    /**
     * Pattern match (like). Use % as wildcard.
     * @type {string}
     * @memberof ListDatabasesWhereParameterOrganisationIdAnyOf
     */
    like?: string;
    /**
     * The organisation this database belongs to
     * @type {string}
     * @memberof ListDatabasesWhereParameterOrganisationIdAnyOf
     */
    lt?: string;
    /**
     * The organisation this database belongs to
     * @type {string}
     * @memberof ListDatabasesWhereParameterOrganisationIdAnyOf
     */
    lte?: string;
    /**
     * The organisation this database belongs to
     * @type {string}
     * @memberof ListDatabasesWhereParameterOrganisationIdAnyOf
     */
    neq?: string;
    /**
     * Comma-separated list of values (nin)
     * @type {string}
     * @memberof ListDatabasesWhereParameterOrganisationIdAnyOf
     */
    nin?: string;
    /**
     * Check for NULL (true) or NOT NULL (false)
     * @type {string}
     * @memberof ListDatabasesWhereParameterOrganisationIdAnyOf
     */
    _null?: ListDatabasesWhereParameterOrganisationIdAnyOfNullEnum;
}


/**
 * @export
 */
export const ListDatabasesWhereParameterOrganisationIdAnyOfNullEnum = {
    True: 'true',
    False: 'false'
} as const;
export type ListDatabasesWhereParameterOrganisationIdAnyOfNullEnum = typeof ListDatabasesWhereParameterOrganisationIdAnyOfNullEnum[keyof typeof ListDatabasesWhereParameterOrganisationIdAnyOfNullEnum];


/**
 * Check if a given object implements the ListDatabasesWhereParameterOrganisationIdAnyOf interface.
 */
export function instanceOfListDatabasesWhereParameterOrganisationIdAnyOf(value: object): value is ListDatabasesWhereParameterOrganisationIdAnyOf {
    return true;
}

export function ListDatabasesWhereParameterOrganisationIdAnyOfFromJSON(json: any): ListDatabasesWhereParameterOrganisationIdAnyOf {
    return ListDatabasesWhereParameterOrganisationIdAnyOfFromJSONTyped(json, false);
}

export function ListDatabasesWhereParameterOrganisationIdAnyOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListDatabasesWhereParameterOrganisationIdAnyOf {
    if (json == null) {
        return json;
    }
    return {
        
        'eq': json['eq'] == null ? undefined : json['eq'],
        'gt': json['gt'] == null ? undefined : json['gt'],
        'gte': json['gte'] == null ? undefined : json['gte'],
        'ilike': json['ilike'] == null ? undefined : json['ilike'],
        '_in': json['in'] == null ? undefined : json['in'],
        'like': json['like'] == null ? undefined : json['like'],
        'lt': json['lt'] == null ? undefined : json['lt'],
        'lte': json['lte'] == null ? undefined : json['lte'],
        'neq': json['neq'] == null ? undefined : json['neq'],
        'nin': json['nin'] == null ? undefined : json['nin'],
        '_null': json['null'] == null ? undefined : json['null'],
    };
}

export function ListDatabasesWhereParameterOrganisationIdAnyOfToJSON(json: any): ListDatabasesWhereParameterOrganisationIdAnyOf {
    return ListDatabasesWhereParameterOrganisationIdAnyOfToJSONTyped(json, false);
}

export function ListDatabasesWhereParameterOrganisationIdAnyOfToJSONTyped(value?: ListDatabasesWhereParameterOrganisationIdAnyOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'eq': value['eq'],
        'gt': value['gt'],
        'gte': value['gte'],
        'ilike': value['ilike'],
        'in': value['_in'],
        'like': value['like'],
        'lt': value['lt'],
        'lte': value['lte'],
        'neq': value['neq'],
        'nin': value['nin'],
        'null': value['_null'],
    };
}

