/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListDatabasesWhereParameterOrganisationIdAnyOf } from './ListDatabasesWhereParameterOrganisationIdAnyOf';
import {
    ListDatabasesWhereParameterOrganisationIdAnyOfFromJSON,
    ListDatabasesWhereParameterOrganisationIdAnyOfFromJSONTyped,
    ListDatabasesWhereParameterOrganisationIdAnyOfToJSON,
    ListDatabasesWhereParameterOrganisationIdAnyOfToJSONTyped,
} from './ListDatabasesWhereParameterOrganisationIdAnyOf';

/**
 * 
 * @export
 * @interface ListDatabasesWhereParameterOrganisationId
 */
export interface ListDatabasesWhereParameterOrganisationId {
    /**
     * The organisation this database belongs to
     * @type {string}
     * @memberof ListDatabasesWhereParameterOrganisationId
     */
    eq?: string;
    /**
     * The organisation this database belongs to
     * @type {string}
     * @memberof ListDatabasesWhereParameterOrganisationId
     */
    gt?: string;
    /**
     * The organisation this database belongs to
     * @type {string}
     * @memberof ListDatabasesWhereParameterOrganisationId
     */
    gte?: string;
    /**
     * Pattern match (ilike). Use % as wildcard.
     * @type {string}
     * @memberof ListDatabasesWhereParameterOrganisationId
     */
    ilike?: string;
    /**
     * Comma-separated list of values (in)
     * @type {string}
     * @memberof ListDatabasesWhereParameterOrganisationId
     */
    _in?: string;
    /**
     * Pattern match (like). Use % as wildcard.
     * @type {string}
     * @memberof ListDatabasesWhereParameterOrganisationId
     */
    like?: string;
    /**
     * The organisation this database belongs to
     * @type {string}
     * @memberof ListDatabasesWhereParameterOrganisationId
     */
    lt?: string;
    /**
     * The organisation this database belongs to
     * @type {string}
     * @memberof ListDatabasesWhereParameterOrganisationId
     */
    lte?: string;
    /**
     * The organisation this database belongs to
     * @type {string}
     * @memberof ListDatabasesWhereParameterOrganisationId
     */
    neq?: string;
    /**
     * Comma-separated list of values (nin)
     * @type {string}
     * @memberof ListDatabasesWhereParameterOrganisationId
     */
    nin?: string;
    /**
     * Check for NULL (true) or NOT NULL (false)
     * @type {string}
     * @memberof ListDatabasesWhereParameterOrganisationId
     */
    _null?: ListDatabasesWhereParameterOrganisationIdNullEnum;
}


/**
 * @export
 */
export const ListDatabasesWhereParameterOrganisationIdNullEnum = {
    True: 'true',
    False: 'false'
} as const;
export type ListDatabasesWhereParameterOrganisationIdNullEnum = typeof ListDatabasesWhereParameterOrganisationIdNullEnum[keyof typeof ListDatabasesWhereParameterOrganisationIdNullEnum];


/**
 * Check if a given object implements the ListDatabasesWhereParameterOrganisationId interface.
 */
export function instanceOfListDatabasesWhereParameterOrganisationId(value: object): value is ListDatabasesWhereParameterOrganisationId {
    return true;
}

export function ListDatabasesWhereParameterOrganisationIdFromJSON(json: any): ListDatabasesWhereParameterOrganisationId {
    return ListDatabasesWhereParameterOrganisationIdFromJSONTyped(json, false);
}

export function ListDatabasesWhereParameterOrganisationIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListDatabasesWhereParameterOrganisationId {
    if (json == null) {
        return json;
    }
    return {
        
        'eq': json['eq'] == null ? undefined : json['eq'],
        'gt': json['gt'] == null ? undefined : json['gt'],
        'gte': json['gte'] == null ? undefined : json['gte'],
        'ilike': json['ilike'] == null ? undefined : json['ilike'],
        '_in': json['in'] == null ? undefined : json['in'],
        'like': json['like'] == null ? undefined : json['like'],
        'lt': json['lt'] == null ? undefined : json['lt'],
        'lte': json['lte'] == null ? undefined : json['lte'],
        'neq': json['neq'] == null ? undefined : json['neq'],
        'nin': json['nin'] == null ? undefined : json['nin'],
        '_null': json['null'] == null ? undefined : json['null'],
    };
}

export function ListDatabasesWhereParameterOrganisationIdToJSON(json: any): ListDatabasesWhereParameterOrganisationId {
    return ListDatabasesWhereParameterOrganisationIdToJSONTyped(json, false);
}

export function ListDatabasesWhereParameterOrganisationIdToJSONTyped(value?: ListDatabasesWhereParameterOrganisationId | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'eq': value['eq'],
        'gt': value['gt'],
        'gte': value['gte'],
        'ilike': value['ilike'],
        'in': value['_in'],
        'like': value['like'],
        'lt': value['lt'],
        'lte': value['lte'],
        'neq': value['neq'],
        'nin': value['nin'],
        'null': value['_null'],
    };
}

