/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListViewsWhereParameterDescriptionAnyOf
 */
export interface ListViewsWhereParameterDescriptionAnyOf {
    /**
     * A description of the view
     * @type {string}
     * @memberof ListViewsWhereParameterDescriptionAnyOf
     */
    eq?: string | null;
    /**
     * A description of the view
     * @type {string}
     * @memberof ListViewsWhereParameterDescriptionAnyOf
     */
    gt?: string | null;
    /**
     * A description of the view
     * @type {string}
     * @memberof ListViewsWhereParameterDescriptionAnyOf
     */
    gte?: string | null;
    /**
     * Pattern match (ilike). Use % as wildcard.
     * @type {string}
     * @memberof ListViewsWhereParameterDescriptionAnyOf
     */
    ilike?: string;
    /**
     * Comma-separated list of values (in)
     * @type {string}
     * @memberof ListViewsWhereParameterDescriptionAnyOf
     */
    _in?: string;
    /**
     * Pattern match (like). Use % as wildcard.
     * @type {string}
     * @memberof ListViewsWhereParameterDescriptionAnyOf
     */
    like?: string;
    /**
     * A description of the view
     * @type {string}
     * @memberof ListViewsWhereParameterDescriptionAnyOf
     */
    lt?: string | null;
    /**
     * A description of the view
     * @type {string}
     * @memberof ListViewsWhereParameterDescriptionAnyOf
     */
    lte?: string | null;
    /**
     * A description of the view
     * @type {string}
     * @memberof ListViewsWhereParameterDescriptionAnyOf
     */
    neq?: string | null;
    /**
     * Comma-separated list of values (nin)
     * @type {string}
     * @memberof ListViewsWhereParameterDescriptionAnyOf
     */
    nin?: string;
    /**
     * Check for NULL (true) or NOT NULL (false)
     * @type {string}
     * @memberof ListViewsWhereParameterDescriptionAnyOf
     */
    _null?: ListViewsWhereParameterDescriptionAnyOfNullEnum;
}


/**
 * @export
 */
export const ListViewsWhereParameterDescriptionAnyOfNullEnum = {
    True: 'true',
    False: 'false'
} as const;
export type ListViewsWhereParameterDescriptionAnyOfNullEnum = typeof ListViewsWhereParameterDescriptionAnyOfNullEnum[keyof typeof ListViewsWhereParameterDescriptionAnyOfNullEnum];


/**
 * Check if a given object implements the ListViewsWhereParameterDescriptionAnyOf interface.
 */
export function instanceOfListViewsWhereParameterDescriptionAnyOf(value: object): value is ListViewsWhereParameterDescriptionAnyOf {
    return true;
}

export function ListViewsWhereParameterDescriptionAnyOfFromJSON(json: any): ListViewsWhereParameterDescriptionAnyOf {
    return ListViewsWhereParameterDescriptionAnyOfFromJSONTyped(json, false);
}

export function ListViewsWhereParameterDescriptionAnyOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListViewsWhereParameterDescriptionAnyOf {
    if (json == null) {
        return json;
    }
    return {
        
        'eq': json['eq'] == null ? undefined : json['eq'],
        'gt': json['gt'] == null ? undefined : json['gt'],
        'gte': json['gte'] == null ? undefined : json['gte'],
        'ilike': json['ilike'] == null ? undefined : json['ilike'],
        '_in': json['in'] == null ? undefined : json['in'],
        'like': json['like'] == null ? undefined : json['like'],
        'lt': json['lt'] == null ? undefined : json['lt'],
        'lte': json['lte'] == null ? undefined : json['lte'],
        'neq': json['neq'] == null ? undefined : json['neq'],
        'nin': json['nin'] == null ? undefined : json['nin'],
        '_null': json['null'] == null ? undefined : json['null'],
    };
}

export function ListViewsWhereParameterDescriptionAnyOfToJSON(json: any): ListViewsWhereParameterDescriptionAnyOf {
    return ListViewsWhereParameterDescriptionAnyOfToJSONTyped(json, false);
}

export function ListViewsWhereParameterDescriptionAnyOfToJSONTyped(value?: ListViewsWhereParameterDescriptionAnyOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'eq': value['eq'],
        'gt': value['gt'],
        'gte': value['gte'],
        'ilike': value['ilike'],
        'in': value['_in'],
        'like': value['like'],
        'lt': value['lt'],
        'lte': value['lte'],
        'neq': value['neq'],
        'nin': value['nin'],
        'null': value['_null'],
    };
}

