/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListResourcesWhereParameterTypeAnyOf
 */
export interface ListResourcesWhereParameterTypeAnyOf {
    /**
     * The resource type
     * @type {string}
     * @memberof ListResourcesWhereParameterTypeAnyOf
     */
    eq?: ListResourcesWhereParameterTypeAnyOfEqEnum;
    /**
     * The resource type
     * @type {string}
     * @memberof ListResourcesWhereParameterTypeAnyOf
     */
    gt?: ListResourcesWhereParameterTypeAnyOfGtEnum;
    /**
     * The resource type
     * @type {string}
     * @memberof ListResourcesWhereParameterTypeAnyOf
     */
    gte?: ListResourcesWhereParameterTypeAnyOfGteEnum;
    /**
     * Pattern match (ilike). Use % as wildcard.
     * @type {string}
     * @memberof ListResourcesWhereParameterTypeAnyOf
     */
    ilike?: string;
    /**
     * Comma-separated list of values (in)
     * @type {string}
     * @memberof ListResourcesWhereParameterTypeAnyOf
     */
    _in?: string;
    /**
     * Pattern match (like). Use % as wildcard.
     * @type {string}
     * @memberof ListResourcesWhereParameterTypeAnyOf
     */
    like?: string;
    /**
     * The resource type
     * @type {string}
     * @memberof ListResourcesWhereParameterTypeAnyOf
     */
    lt?: ListResourcesWhereParameterTypeAnyOfLtEnum;
    /**
     * The resource type
     * @type {string}
     * @memberof ListResourcesWhereParameterTypeAnyOf
     */
    lte?: ListResourcesWhereParameterTypeAnyOfLteEnum;
    /**
     * The resource type
     * @type {string}
     * @memberof ListResourcesWhereParameterTypeAnyOf
     */
    neq?: ListResourcesWhereParameterTypeAnyOfNeqEnum;
    /**
     * Comma-separated list of values (nin)
     * @type {string}
     * @memberof ListResourcesWhereParameterTypeAnyOf
     */
    nin?: string;
    /**
     * Check for NULL (true) or NOT NULL (false)
     * @type {string}
     * @memberof ListResourcesWhereParameterTypeAnyOf
     */
    _null?: ListResourcesWhereParameterTypeAnyOfNullEnum;
}


/**
 * @export
 */
export const ListResourcesWhereParameterTypeAnyOfEqEnum = {
    Postgres: 'postgres',
    S3: 's3',
    Smtp: 'smtp'
} as const;
export type ListResourcesWhereParameterTypeAnyOfEqEnum = typeof ListResourcesWhereParameterTypeAnyOfEqEnum[keyof typeof ListResourcesWhereParameterTypeAnyOfEqEnum];

/**
 * @export
 */
export const ListResourcesWhereParameterTypeAnyOfGtEnum = {
    Postgres: 'postgres',
    S3: 's3',
    Smtp: 'smtp'
} as const;
export type ListResourcesWhereParameterTypeAnyOfGtEnum = typeof ListResourcesWhereParameterTypeAnyOfGtEnum[keyof typeof ListResourcesWhereParameterTypeAnyOfGtEnum];

/**
 * @export
 */
export const ListResourcesWhereParameterTypeAnyOfGteEnum = {
    Postgres: 'postgres',
    S3: 's3',
    Smtp: 'smtp'
} as const;
export type ListResourcesWhereParameterTypeAnyOfGteEnum = typeof ListResourcesWhereParameterTypeAnyOfGteEnum[keyof typeof ListResourcesWhereParameterTypeAnyOfGteEnum];

/**
 * @export
 */
export const ListResourcesWhereParameterTypeAnyOfLtEnum = {
    Postgres: 'postgres',
    S3: 's3',
    Smtp: 'smtp'
} as const;
export type ListResourcesWhereParameterTypeAnyOfLtEnum = typeof ListResourcesWhereParameterTypeAnyOfLtEnum[keyof typeof ListResourcesWhereParameterTypeAnyOfLtEnum];

/**
 * @export
 */
export const ListResourcesWhereParameterTypeAnyOfLteEnum = {
    Postgres: 'postgres',
    S3: 's3',
    Smtp: 'smtp'
} as const;
export type ListResourcesWhereParameterTypeAnyOfLteEnum = typeof ListResourcesWhereParameterTypeAnyOfLteEnum[keyof typeof ListResourcesWhereParameterTypeAnyOfLteEnum];

/**
 * @export
 */
export const ListResourcesWhereParameterTypeAnyOfNeqEnum = {
    Postgres: 'postgres',
    S3: 's3',
    Smtp: 'smtp'
} as const;
export type ListResourcesWhereParameterTypeAnyOfNeqEnum = typeof ListResourcesWhereParameterTypeAnyOfNeqEnum[keyof typeof ListResourcesWhereParameterTypeAnyOfNeqEnum];

/**
 * @export
 */
export const ListResourcesWhereParameterTypeAnyOfNullEnum = {
    True: 'true',
    False: 'false'
} as const;
export type ListResourcesWhereParameterTypeAnyOfNullEnum = typeof ListResourcesWhereParameterTypeAnyOfNullEnum[keyof typeof ListResourcesWhereParameterTypeAnyOfNullEnum];


/**
 * Check if a given object implements the ListResourcesWhereParameterTypeAnyOf interface.
 */
export function instanceOfListResourcesWhereParameterTypeAnyOf(value: object): value is ListResourcesWhereParameterTypeAnyOf {
    return true;
}

export function ListResourcesWhereParameterTypeAnyOfFromJSON(json: any): ListResourcesWhereParameterTypeAnyOf {
    return ListResourcesWhereParameterTypeAnyOfFromJSONTyped(json, false);
}

export function ListResourcesWhereParameterTypeAnyOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListResourcesWhereParameterTypeAnyOf {
    if (json == null) {
        return json;
    }
    return {
        
        'eq': json['eq'] == null ? undefined : json['eq'],
        'gt': json['gt'] == null ? undefined : json['gt'],
        'gte': json['gte'] == null ? undefined : json['gte'],
        'ilike': json['ilike'] == null ? undefined : json['ilike'],
        '_in': json['in'] == null ? undefined : json['in'],
        'like': json['like'] == null ? undefined : json['like'],
        'lt': json['lt'] == null ? undefined : json['lt'],
        'lte': json['lte'] == null ? undefined : json['lte'],
        'neq': json['neq'] == null ? undefined : json['neq'],
        'nin': json['nin'] == null ? undefined : json['nin'],
        '_null': json['null'] == null ? undefined : json['null'],
    };
}

export function ListResourcesWhereParameterTypeAnyOfToJSON(json: any): ListResourcesWhereParameterTypeAnyOf {
    return ListResourcesWhereParameterTypeAnyOfToJSONTyped(json, false);
}

export function ListResourcesWhereParameterTypeAnyOfToJSONTyped(value?: ListResourcesWhereParameterTypeAnyOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'eq': value['eq'],
        'gt': value['gt'],
        'gte': value['gte'],
        'ilike': value['ilike'],
        'in': value['_in'],
        'like': value['like'],
        'lt': value['lt'],
        'lte': value['lte'],
        'neq': value['neq'],
        'nin': value['nin'],
        'null': value['_null'],
    };
}

