/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListDatabasesOrderParameter
 */
export interface ListDatabasesOrderParameter {
    /**
     * Sort direction for this field
     * @type {string}
     * @memberof ListDatabasesOrderParameter
     */
    createdAt?: ListDatabasesOrderParameterCreatedAtEnum;
    /**
     * Sort direction for this field
     * @type {string}
     * @memberof ListDatabasesOrderParameter
     */
    description?: ListDatabasesOrderParameterDescriptionEnum;
    /**
     * Sort direction for this field
     * @type {string}
     * @memberof ListDatabasesOrderParameter
     */
    id?: ListDatabasesOrderParameterIdEnum;
    /**
     * Sort direction for this field
     * @type {string}
     * @memberof ListDatabasesOrderParameter
     */
    name?: ListDatabasesOrderParameterNameEnum;
    /**
     * Sort direction for this field
     * @type {string}
     * @memberof ListDatabasesOrderParameter
     */
    organisationId?: ListDatabasesOrderParameterOrganisationIdEnum;
    /**
     * Sort direction for this field
     * @type {string}
     * @memberof ListDatabasesOrderParameter
     */
    _public?: ListDatabasesOrderParameterPublicEnum;
    /**
     * Sort direction for this field
     * @type {string}
     * @memberof ListDatabasesOrderParameter
     */
    slug?: ListDatabasesOrderParameterSlugEnum;
    /**
     * Sort direction for this field
     * @type {string}
     * @memberof ListDatabasesOrderParameter
     */
    updatedAt?: ListDatabasesOrderParameterUpdatedAtEnum;
}


/**
 * @export
 */
export const ListDatabasesOrderParameterCreatedAtEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type ListDatabasesOrderParameterCreatedAtEnum = typeof ListDatabasesOrderParameterCreatedAtEnum[keyof typeof ListDatabasesOrderParameterCreatedAtEnum];

/**
 * @export
 */
export const ListDatabasesOrderParameterDescriptionEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type ListDatabasesOrderParameterDescriptionEnum = typeof ListDatabasesOrderParameterDescriptionEnum[keyof typeof ListDatabasesOrderParameterDescriptionEnum];

/**
 * @export
 */
export const ListDatabasesOrderParameterIdEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type ListDatabasesOrderParameterIdEnum = typeof ListDatabasesOrderParameterIdEnum[keyof typeof ListDatabasesOrderParameterIdEnum];

/**
 * @export
 */
export const ListDatabasesOrderParameterNameEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type ListDatabasesOrderParameterNameEnum = typeof ListDatabasesOrderParameterNameEnum[keyof typeof ListDatabasesOrderParameterNameEnum];

/**
 * @export
 */
export const ListDatabasesOrderParameterOrganisationIdEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type ListDatabasesOrderParameterOrganisationIdEnum = typeof ListDatabasesOrderParameterOrganisationIdEnum[keyof typeof ListDatabasesOrderParameterOrganisationIdEnum];

/**
 * @export
 */
export const ListDatabasesOrderParameterPublicEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type ListDatabasesOrderParameterPublicEnum = typeof ListDatabasesOrderParameterPublicEnum[keyof typeof ListDatabasesOrderParameterPublicEnum];

/**
 * @export
 */
export const ListDatabasesOrderParameterSlugEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type ListDatabasesOrderParameterSlugEnum = typeof ListDatabasesOrderParameterSlugEnum[keyof typeof ListDatabasesOrderParameterSlugEnum];

/**
 * @export
 */
export const ListDatabasesOrderParameterUpdatedAtEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type ListDatabasesOrderParameterUpdatedAtEnum = typeof ListDatabasesOrderParameterUpdatedAtEnum[keyof typeof ListDatabasesOrderParameterUpdatedAtEnum];


/**
 * Check if a given object implements the ListDatabasesOrderParameter interface.
 */
export function instanceOfListDatabasesOrderParameter(value: object): value is ListDatabasesOrderParameter {
    return true;
}

export function ListDatabasesOrderParameterFromJSON(json: any): ListDatabasesOrderParameter {
    return ListDatabasesOrderParameterFromJSONTyped(json, false);
}

export function ListDatabasesOrderParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListDatabasesOrderParameter {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'organisationId': json['organisation_id'] == null ? undefined : json['organisation_id'],
        '_public': json['public'] == null ? undefined : json['public'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

export function ListDatabasesOrderParameterToJSON(json: any): ListDatabasesOrderParameter {
    return ListDatabasesOrderParameterToJSONTyped(json, false);
}

export function ListDatabasesOrderParameterToJSONTyped(value?: ListDatabasesOrderParameter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'],
        'description': value['description'],
        'id': value['id'],
        'name': value['name'],
        'organisation_id': value['organisationId'],
        'public': value['_public'],
        'slug': value['slug'],
        'updated_at': value['updatedAt'],
    };
}

