/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListResourcesWhereParameterConfigAnyOf } from './ListResourcesWhereParameterConfigAnyOf';
import {
    ListResourcesWhereParameterConfigAnyOfFromJSON,
    ListResourcesWhereParameterConfigAnyOfFromJSONTyped,
    ListResourcesWhereParameterConfigAnyOfToJSON,
    ListResourcesWhereParameterConfigAnyOfToJSONTyped,
} from './ListResourcesWhereParameterConfigAnyOf';

/**
 * 
 * @export
 * @interface ListResourcesWhereParameterConfig
 */
export interface ListResourcesWhereParameterConfig {
    /**
     * Resource-specific configuration
     * @type {{ [key: string]: object; }}
     * @memberof ListResourcesWhereParameterConfig
     */
    eq?: { [key: string]: object; };
    /**
     * Resource-specific configuration
     * @type {{ [key: string]: object; }}
     * @memberof ListResourcesWhereParameterConfig
     */
    gt?: { [key: string]: object; };
    /**
     * Resource-specific configuration
     * @type {{ [key: string]: object; }}
     * @memberof ListResourcesWhereParameterConfig
     */
    gte?: { [key: string]: object; };
    /**
     * Pattern match (ilike). Use % as wildcard.
     * @type {string}
     * @memberof ListResourcesWhereParameterConfig
     */
    ilike?: string;
    /**
     * Comma-separated list of values (in)
     * @type {string}
     * @memberof ListResourcesWhereParameterConfig
     */
    _in?: string;
    /**
     * Pattern match (like). Use % as wildcard.
     * @type {string}
     * @memberof ListResourcesWhereParameterConfig
     */
    like?: string;
    /**
     * Resource-specific configuration
     * @type {{ [key: string]: object; }}
     * @memberof ListResourcesWhereParameterConfig
     */
    lt?: { [key: string]: object; };
    /**
     * Resource-specific configuration
     * @type {{ [key: string]: object; }}
     * @memberof ListResourcesWhereParameterConfig
     */
    lte?: { [key: string]: object; };
    /**
     * Resource-specific configuration
     * @type {{ [key: string]: object; }}
     * @memberof ListResourcesWhereParameterConfig
     */
    neq?: { [key: string]: object; };
    /**
     * Comma-separated list of values (nin)
     * @type {string}
     * @memberof ListResourcesWhereParameterConfig
     */
    nin?: string;
    /**
     * Check for NULL (true) or NOT NULL (false)
     * @type {string}
     * @memberof ListResourcesWhereParameterConfig
     */
    _null?: ListResourcesWhereParameterConfigNullEnum;
}


/**
 * @export
 */
export const ListResourcesWhereParameterConfigNullEnum = {
    True: 'true',
    False: 'false'
} as const;
export type ListResourcesWhereParameterConfigNullEnum = typeof ListResourcesWhereParameterConfigNullEnum[keyof typeof ListResourcesWhereParameterConfigNullEnum];


/**
 * Check if a given object implements the ListResourcesWhereParameterConfig interface.
 */
export function instanceOfListResourcesWhereParameterConfig(value: object): value is ListResourcesWhereParameterConfig {
    return true;
}

export function ListResourcesWhereParameterConfigFromJSON(json: any): ListResourcesWhereParameterConfig {
    return ListResourcesWhereParameterConfigFromJSONTyped(json, false);
}

export function ListResourcesWhereParameterConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListResourcesWhereParameterConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'eq': json['eq'] == null ? undefined : json['eq'],
        'gt': json['gt'] == null ? undefined : json['gt'],
        'gte': json['gte'] == null ? undefined : json['gte'],
        'ilike': json['ilike'] == null ? undefined : json['ilike'],
        '_in': json['in'] == null ? undefined : json['in'],
        'like': json['like'] == null ? undefined : json['like'],
        'lt': json['lt'] == null ? undefined : json['lt'],
        'lte': json['lte'] == null ? undefined : json['lte'],
        'neq': json['neq'] == null ? undefined : json['neq'],
        'nin': json['nin'] == null ? undefined : json['nin'],
        '_null': json['null'] == null ? undefined : json['null'],
    };
}

export function ListResourcesWhereParameterConfigToJSON(json: any): ListResourcesWhereParameterConfig {
    return ListResourcesWhereParameterConfigToJSONTyped(json, false);
}

export function ListResourcesWhereParameterConfigToJSONTyped(value?: ListResourcesWhereParameterConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'eq': value['eq'],
        'gt': value['gt'],
        'gte': value['gte'],
        'ilike': value['ilike'],
        'in': value['_in'],
        'like': value['like'],
        'lt': value['lt'],
        'lte': value['lte'],
        'neq': value['neq'],
        'nin': value['nin'],
        'null': value['_null'],
    };
}

