/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListUsersWhereParameterUpdatedAtAnyOf
 */
export interface ListUsersWhereParameterUpdatedAtAnyOf {
    /**
     * The date and time the user was last updated
     * @type {Date}
     * @memberof ListUsersWhereParameterUpdatedAtAnyOf
     */
    eq?: Date;
    /**
     * The date and time the user was last updated
     * @type {Date}
     * @memberof ListUsersWhereParameterUpdatedAtAnyOf
     */
    gt?: Date;
    /**
     * The date and time the user was last updated
     * @type {Date}
     * @memberof ListUsersWhereParameterUpdatedAtAnyOf
     */
    gte?: Date;
    /**
     * Pattern match (ilike). Use % as wildcard.
     * @type {string}
     * @memberof ListUsersWhereParameterUpdatedAtAnyOf
     */
    ilike?: string;
    /**
     * Comma-separated list of values (in)
     * @type {string}
     * @memberof ListUsersWhereParameterUpdatedAtAnyOf
     */
    _in?: string;
    /**
     * Pattern match (like). Use % as wildcard.
     * @type {string}
     * @memberof ListUsersWhereParameterUpdatedAtAnyOf
     */
    like?: string;
    /**
     * The date and time the user was last updated
     * @type {Date}
     * @memberof ListUsersWhereParameterUpdatedAtAnyOf
     */
    lt?: Date;
    /**
     * The date and time the user was last updated
     * @type {Date}
     * @memberof ListUsersWhereParameterUpdatedAtAnyOf
     */
    lte?: Date;
    /**
     * The date and time the user was last updated
     * @type {Date}
     * @memberof ListUsersWhereParameterUpdatedAtAnyOf
     */
    neq?: Date;
    /**
     * Comma-separated list of values (nin)
     * @type {string}
     * @memberof ListUsersWhereParameterUpdatedAtAnyOf
     */
    nin?: string;
    /**
     * Check for NULL (true) or NOT NULL (false)
     * @type {string}
     * @memberof ListUsersWhereParameterUpdatedAtAnyOf
     */
    _null?: ListUsersWhereParameterUpdatedAtAnyOfNullEnum;
}


/**
 * @export
 */
export const ListUsersWhereParameterUpdatedAtAnyOfNullEnum = {
    True: 'true',
    False: 'false'
} as const;
export type ListUsersWhereParameterUpdatedAtAnyOfNullEnum = typeof ListUsersWhereParameterUpdatedAtAnyOfNullEnum[keyof typeof ListUsersWhereParameterUpdatedAtAnyOfNullEnum];


/**
 * Check if a given object implements the ListUsersWhereParameterUpdatedAtAnyOf interface.
 */
export function instanceOfListUsersWhereParameterUpdatedAtAnyOf(value: object): value is ListUsersWhereParameterUpdatedAtAnyOf {
    return true;
}

export function ListUsersWhereParameterUpdatedAtAnyOfFromJSON(json: any): ListUsersWhereParameterUpdatedAtAnyOf {
    return ListUsersWhereParameterUpdatedAtAnyOfFromJSONTyped(json, false);
}

export function ListUsersWhereParameterUpdatedAtAnyOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListUsersWhereParameterUpdatedAtAnyOf {
    if (json == null) {
        return json;
    }
    return {
        
        'eq': json['eq'] == null ? undefined : (new Date(json['eq'])),
        'gt': json['gt'] == null ? undefined : (new Date(json['gt'])),
        'gte': json['gte'] == null ? undefined : (new Date(json['gte'])),
        'ilike': json['ilike'] == null ? undefined : json['ilike'],
        '_in': json['in'] == null ? undefined : json['in'],
        'like': json['like'] == null ? undefined : json['like'],
        'lt': json['lt'] == null ? undefined : (new Date(json['lt'])),
        'lte': json['lte'] == null ? undefined : (new Date(json['lte'])),
        'neq': json['neq'] == null ? undefined : (new Date(json['neq'])),
        'nin': json['nin'] == null ? undefined : json['nin'],
        '_null': json['null'] == null ? undefined : json['null'],
    };
}

export function ListUsersWhereParameterUpdatedAtAnyOfToJSON(json: any): ListUsersWhereParameterUpdatedAtAnyOf {
    return ListUsersWhereParameterUpdatedAtAnyOfToJSONTyped(json, false);
}

export function ListUsersWhereParameterUpdatedAtAnyOfToJSONTyped(value?: ListUsersWhereParameterUpdatedAtAnyOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'eq': value['eq'] == null ? value['eq'] : value['eq'].toISOString(),
        'gt': value['gt'] == null ? value['gt'] : value['gt'].toISOString(),
        'gte': value['gte'] == null ? value['gte'] : value['gte'].toISOString(),
        'ilike': value['ilike'],
        'in': value['_in'],
        'like': value['like'],
        'lt': value['lt'] == null ? value['lt'] : value['lt'].toISOString(),
        'lte': value['lte'] == null ? value['lte'] : value['lte'].toISOString(),
        'neq': value['neq'] == null ? value['neq'] : value['neq'].toISOString(),
        'nin': value['nin'],
        'null': value['_null'],
    };
}

