/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Logout403Response
 */
export interface Logout403Response {
    /**
     * A description of the authorization error
     * @type {string}
     * @memberof Logout403Response
     */
    message: string;
}

/**
 * Check if a given object implements the Logout403Response interface.
 */
export function instanceOfLogout403Response(value: object): value is Logout403Response {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function Logout403ResponseFromJSON(json: any): Logout403Response {
    return Logout403ResponseFromJSONTyped(json, false);
}

export function Logout403ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Logout403Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function Logout403ResponseToJSON(json: any): Logout403Response {
    return Logout403ResponseToJSONTyped(json, false);
}

export function Logout403ResponseToJSONTyped(value?: Logout403Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

