/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestMfaSetup409Response
 */
export interface RequestMfaSetup409Response {
    /**
     * A description of the conflict
     * @type {string}
     * @memberof RequestMfaSetup409Response
     */
    message: string;
}

/**
 * Check if a given object implements the RequestMfaSetup409Response interface.
 */
export function instanceOfRequestMfaSetup409Response(value: object): value is RequestMfaSetup409Response {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function RequestMfaSetup409ResponseFromJSON(json: any): RequestMfaSetup409Response {
    return RequestMfaSetup409ResponseFromJSONTyped(json, false);
}

export function RequestMfaSetup409ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestMfaSetup409Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function RequestMfaSetup409ResponseToJSON(json: any): RequestMfaSetup409Response {
    return RequestMfaSetup409ResponseToJSONTyped(json, false);
}

export function RequestMfaSetup409ResponseToJSONTyped(value?: RequestMfaSetup409Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

