/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SearchMembershipsRequestWhere } from './SearchMembershipsRequestWhere';
import {
    SearchMembershipsRequestWhereFromJSON,
    SearchMembershipsRequestWhereFromJSONTyped,
    SearchMembershipsRequestWhereToJSON,
    SearchMembershipsRequestWhereToJSONTyped,
} from './SearchMembershipsRequestWhere';
import type { SearchDatabasesRequestLimit } from './SearchDatabasesRequestLimit';
import {
    SearchDatabasesRequestLimitFromJSON,
    SearchDatabasesRequestLimitFromJSONTyped,
    SearchDatabasesRequestLimitToJSON,
    SearchDatabasesRequestLimitToJSONTyped,
} from './SearchDatabasesRequestLimit';
import type { SearchMembershipsRequestOrder } from './SearchMembershipsRequestOrder';
import {
    SearchMembershipsRequestOrderFromJSON,
    SearchMembershipsRequestOrderFromJSONTyped,
    SearchMembershipsRequestOrderToJSON,
    SearchMembershipsRequestOrderToJSONTyped,
} from './SearchMembershipsRequestOrder';

/**
 * 
 * @export
 * @interface SearchMembershipsRequest
 */
export interface SearchMembershipsRequest {
    /**
     * 
     * @type {SearchDatabasesRequestLimit}
     * @memberof SearchMembershipsRequest
     */
    limit?: SearchDatabasesRequestLimit;
    /**
     * 
     * @type {SearchMembershipsRequestOrder}
     * @memberof SearchMembershipsRequest
     */
    order?: SearchMembershipsRequestOrder;
    /**
     * Fields to include in the response
     * @type {Set<string>}
     * @memberof SearchMembershipsRequest
     */
    select?: Set<SearchMembershipsRequestSelectEnum>;
    /**
     * 
     * @type {SearchMembershipsRequestWhere}
     * @memberof SearchMembershipsRequest
     */
    where?: SearchMembershipsRequestWhere;
}


/**
 * @export
 */
export const SearchMembershipsRequestSelectEnum = {
    CreatedAt: 'created_at',
    Id: 'id',
    OrganisationId: 'organisation_id',
    Scopes: 'scopes',
    UpdatedAt: 'updated_at',
    UserId: 'user_id'
} as const;
export type SearchMembershipsRequestSelectEnum = typeof SearchMembershipsRequestSelectEnum[keyof typeof SearchMembershipsRequestSelectEnum];


/**
 * Check if a given object implements the SearchMembershipsRequest interface.
 */
export function instanceOfSearchMembershipsRequest(value: object): value is SearchMembershipsRequest {
    return true;
}

export function SearchMembershipsRequestFromJSON(json: any): SearchMembershipsRequest {
    return SearchMembershipsRequestFromJSONTyped(json, false);
}

export function SearchMembershipsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchMembershipsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'limit': json['limit'] == null ? undefined : SearchDatabasesRequestLimitFromJSON(json['limit']),
        'order': json['order'] == null ? undefined : SearchMembershipsRequestOrderFromJSON(json['order']),
        'select': json['select'] == null ? undefined : new Set(json['select']),
        'where': json['where'] == null ? undefined : SearchMembershipsRequestWhereFromJSON(json['where']),
    };
}

export function SearchMembershipsRequestToJSON(json: any): SearchMembershipsRequest {
    return SearchMembershipsRequestToJSONTyped(json, false);
}

export function SearchMembershipsRequestToJSONTyped(value?: SearchMembershipsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'limit': SearchDatabasesRequestLimitToJSON(value['limit']),
        'order': SearchMembershipsRequestOrderToJSON(value['order']),
        'select': value['select'] == null ? undefined : Array.from(value['select'] as Set<any>),
        'where': SearchMembershipsRequestWhereToJSON(value['where']),
    };
}

