/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SearchDatabasesRequestWhereCreatedAt } from './SearchDatabasesRequestWhereCreatedAt';
import {
    SearchDatabasesRequestWhereCreatedAtFromJSON,
    SearchDatabasesRequestWhereCreatedAtFromJSONTyped,
    SearchDatabasesRequestWhereCreatedAtToJSON,
    SearchDatabasesRequestWhereCreatedAtToJSONTyped,
} from './SearchDatabasesRequestWhereCreatedAt';
import type { SearchOrganisationsRequestWhereAndInnerAndInner } from './SearchOrganisationsRequestWhereAndInnerAndInner';
import {
    SearchOrganisationsRequestWhereAndInnerAndInnerFromJSON,
    SearchOrganisationsRequestWhereAndInnerAndInnerFromJSONTyped,
    SearchOrganisationsRequestWhereAndInnerAndInnerToJSON,
    SearchOrganisationsRequestWhereAndInnerAndInnerToJSONTyped,
} from './SearchOrganisationsRequestWhereAndInnerAndInner';

/**
 * 
 * @export
 * @interface SearchOrganisationsRequestWhereAndInner
 */
export interface SearchOrganisationsRequestWhereAndInner {
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchOrganisationsRequestWhereAndInner
     */
    createdAt?: SearchDatabasesRequestWhereCreatedAt;
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchOrganisationsRequestWhereAndInner
     */
    id?: SearchDatabasesRequestWhereCreatedAt;
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchOrganisationsRequestWhereAndInner
     */
    name?: SearchDatabasesRequestWhereCreatedAt;
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchOrganisationsRequestWhereAndInner
     */
    _public?: SearchDatabasesRequestWhereCreatedAt;
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchOrganisationsRequestWhereAndInner
     */
    slug?: SearchDatabasesRequestWhereCreatedAt;
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchOrganisationsRequestWhereAndInner
     */
    updatedAt?: SearchDatabasesRequestWhereCreatedAt;
    /**
     * All conditions must match
     * @type {Array<SearchOrganisationsRequestWhereAndInnerAndInner>}
     * @memberof SearchOrganisationsRequestWhereAndInner
     */
    and?: Array<SearchOrganisationsRequestWhereAndInnerAndInner>;
    /**
     * At least one condition must match
     * @type {Array<SearchOrganisationsRequestWhereAndInnerAndInner>}
     * @memberof SearchOrganisationsRequestWhereAndInner
     */
    or?: Array<SearchOrganisationsRequestWhereAndInnerAndInner>;
}

/**
 * Check if a given object implements the SearchOrganisationsRequestWhereAndInner interface.
 */
export function instanceOfSearchOrganisationsRequestWhereAndInner(value: object): value is SearchOrganisationsRequestWhereAndInner {
    return true;
}

export function SearchOrganisationsRequestWhereAndInnerFromJSON(json: any): SearchOrganisationsRequestWhereAndInner {
    return SearchOrganisationsRequestWhereAndInnerFromJSONTyped(json, false);
}

export function SearchOrganisationsRequestWhereAndInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchOrganisationsRequestWhereAndInner {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['created_at']),
        'id': json['id'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['id']),
        'name': json['name'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['name']),
        '_public': json['public'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['public']),
        'slug': json['slug'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['slug']),
        'updatedAt': json['updated_at'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['updated_at']),
        'and': json['and'] == null ? undefined : ((json['and'] as Array<any>).map(SearchOrganisationsRequestWhereAndInnerAndInnerFromJSON)),
        'or': json['or'] == null ? undefined : ((json['or'] as Array<any>).map(SearchOrganisationsRequestWhereAndInnerAndInnerFromJSON)),
    };
}

export function SearchOrganisationsRequestWhereAndInnerToJSON(json: any): SearchOrganisationsRequestWhereAndInner {
    return SearchOrganisationsRequestWhereAndInnerToJSONTyped(json, false);
}

export function SearchOrganisationsRequestWhereAndInnerToJSONTyped(value?: SearchOrganisationsRequestWhereAndInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': SearchDatabasesRequestWhereCreatedAtToJSON(value['createdAt']),
        'id': SearchDatabasesRequestWhereCreatedAtToJSON(value['id']),
        'name': SearchDatabasesRequestWhereCreatedAtToJSON(value['name']),
        'public': SearchDatabasesRequestWhereCreatedAtToJSON(value['_public']),
        'slug': SearchDatabasesRequestWhereCreatedAtToJSON(value['slug']),
        'updated_at': SearchDatabasesRequestWhereCreatedAtToJSON(value['updatedAt']),
        'and': value['and'] == null ? undefined : ((value['and'] as Array<any>).map(SearchOrganisationsRequestWhereAndInnerAndInnerToJSON)),
        'or': value['or'] == null ? undefined : ((value['or'] as Array<any>).map(SearchOrganisationsRequestWhereAndInnerAndInnerToJSON)),
    };
}

