/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SearchMembershipsRequestWhereAndInnerAndInner } from './SearchMembershipsRequestWhereAndInnerAndInner';
import {
    SearchMembershipsRequestWhereAndInnerAndInnerFromJSON,
    SearchMembershipsRequestWhereAndInnerAndInnerFromJSONTyped,
    SearchMembershipsRequestWhereAndInnerAndInnerToJSON,
    SearchMembershipsRequestWhereAndInnerAndInnerToJSONTyped,
} from './SearchMembershipsRequestWhereAndInnerAndInner';
import type { SearchDatabasesRequestWhereCreatedAt } from './SearchDatabasesRequestWhereCreatedAt';
import {
    SearchDatabasesRequestWhereCreatedAtFromJSON,
    SearchDatabasesRequestWhereCreatedAtFromJSONTyped,
    SearchDatabasesRequestWhereCreatedAtToJSON,
    SearchDatabasesRequestWhereCreatedAtToJSONTyped,
} from './SearchDatabasesRequestWhereCreatedAt';

/**
 * 
 * @export
 * @interface SearchMembershipsRequestWhereAndInner
 */
export interface SearchMembershipsRequestWhereAndInner {
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchMembershipsRequestWhereAndInner
     */
    createdAt?: SearchDatabasesRequestWhereCreatedAt;
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchMembershipsRequestWhereAndInner
     */
    id?: SearchDatabasesRequestWhereCreatedAt;
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchMembershipsRequestWhereAndInner
     */
    organisationId?: SearchDatabasesRequestWhereCreatedAt;
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchMembershipsRequestWhereAndInner
     */
    scopes?: SearchDatabasesRequestWhereCreatedAt;
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchMembershipsRequestWhereAndInner
     */
    updatedAt?: SearchDatabasesRequestWhereCreatedAt;
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchMembershipsRequestWhereAndInner
     */
    userId?: SearchDatabasesRequestWhereCreatedAt;
    /**
     * All conditions must match
     * @type {Array<SearchMembershipsRequestWhereAndInnerAndInner>}
     * @memberof SearchMembershipsRequestWhereAndInner
     */
    and?: Array<SearchMembershipsRequestWhereAndInnerAndInner>;
    /**
     * At least one condition must match
     * @type {Array<SearchMembershipsRequestWhereAndInnerAndInner>}
     * @memberof SearchMembershipsRequestWhereAndInner
     */
    or?: Array<SearchMembershipsRequestWhereAndInnerAndInner>;
}

/**
 * Check if a given object implements the SearchMembershipsRequestWhereAndInner interface.
 */
export function instanceOfSearchMembershipsRequestWhereAndInner(value: object): value is SearchMembershipsRequestWhereAndInner {
    return true;
}

export function SearchMembershipsRequestWhereAndInnerFromJSON(json: any): SearchMembershipsRequestWhereAndInner {
    return SearchMembershipsRequestWhereAndInnerFromJSONTyped(json, false);
}

export function SearchMembershipsRequestWhereAndInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchMembershipsRequestWhereAndInner {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['created_at']),
        'id': json['id'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['id']),
        'organisationId': json['organisation_id'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['organisation_id']),
        'scopes': json['scopes'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['scopes']),
        'updatedAt': json['updated_at'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['updated_at']),
        'userId': json['user_id'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['user_id']),
        'and': json['and'] == null ? undefined : ((json['and'] as Array<any>).map(SearchMembershipsRequestWhereAndInnerAndInnerFromJSON)),
        'or': json['or'] == null ? undefined : ((json['or'] as Array<any>).map(SearchMembershipsRequestWhereAndInnerAndInnerFromJSON)),
    };
}

export function SearchMembershipsRequestWhereAndInnerToJSON(json: any): SearchMembershipsRequestWhereAndInner {
    return SearchMembershipsRequestWhereAndInnerToJSONTyped(json, false);
}

export function SearchMembershipsRequestWhereAndInnerToJSONTyped(value?: SearchMembershipsRequestWhereAndInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': SearchDatabasesRequestWhereCreatedAtToJSON(value['createdAt']),
        'id': SearchDatabasesRequestWhereCreatedAtToJSON(value['id']),
        'organisation_id': SearchDatabasesRequestWhereCreatedAtToJSON(value['organisationId']),
        'scopes': SearchDatabasesRequestWhereCreatedAtToJSON(value['scopes']),
        'updated_at': SearchDatabasesRequestWhereCreatedAtToJSON(value['updatedAt']),
        'user_id': SearchDatabasesRequestWhereCreatedAtToJSON(value['userId']),
        'and': value['and'] == null ? undefined : ((value['and'] as Array<any>).map(SearchMembershipsRequestWhereAndInnerAndInnerToJSON)),
        'or': value['or'] == null ? undefined : ((value['or'] as Array<any>).map(SearchMembershipsRequestWhereAndInnerAndInnerToJSON)),
    };
}

