/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SearchDatabasesRequestWhereCreatedAt } from './SearchDatabasesRequestWhereCreatedAt';
import {
    SearchDatabasesRequestWhereCreatedAtFromJSON,
    SearchDatabasesRequestWhereCreatedAtFromJSONTyped,
    SearchDatabasesRequestWhereCreatedAtToJSON,
    SearchDatabasesRequestWhereCreatedAtToJSONTyped,
} from './SearchDatabasesRequestWhereCreatedAt';

/**
 * 
 * @export
 * @interface SearchOrganisationsRequestWhereAndInnerAndInner
 */
export interface SearchOrganisationsRequestWhereAndInnerAndInner {
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchOrganisationsRequestWhereAndInnerAndInner
     */
    createdAt?: SearchDatabasesRequestWhereCreatedAt;
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchOrganisationsRequestWhereAndInnerAndInner
     */
    id?: SearchDatabasesRequestWhereCreatedAt;
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchOrganisationsRequestWhereAndInnerAndInner
     */
    name?: SearchDatabasesRequestWhereCreatedAt;
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchOrganisationsRequestWhereAndInnerAndInner
     */
    _public?: SearchDatabasesRequestWhereCreatedAt;
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchOrganisationsRequestWhereAndInnerAndInner
     */
    slug?: SearchDatabasesRequestWhereCreatedAt;
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchOrganisationsRequestWhereAndInnerAndInner
     */
    updatedAt?: SearchDatabasesRequestWhereCreatedAt;
}

/**
 * Check if a given object implements the SearchOrganisationsRequestWhereAndInnerAndInner interface.
 */
export function instanceOfSearchOrganisationsRequestWhereAndInnerAndInner(value: object): value is SearchOrganisationsRequestWhereAndInnerAndInner {
    return true;
}

export function SearchOrganisationsRequestWhereAndInnerAndInnerFromJSON(json: any): SearchOrganisationsRequestWhereAndInnerAndInner {
    return SearchOrganisationsRequestWhereAndInnerAndInnerFromJSONTyped(json, false);
}

export function SearchOrganisationsRequestWhereAndInnerAndInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchOrganisationsRequestWhereAndInnerAndInner {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['created_at']),
        'id': json['id'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['id']),
        'name': json['name'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['name']),
        '_public': json['public'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['public']),
        'slug': json['slug'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['slug']),
        'updatedAt': json['updated_at'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['updated_at']),
    };
}

export function SearchOrganisationsRequestWhereAndInnerAndInnerToJSON(json: any): SearchOrganisationsRequestWhereAndInnerAndInner {
    return SearchOrganisationsRequestWhereAndInnerAndInnerToJSONTyped(json, false);
}

export function SearchOrganisationsRequestWhereAndInnerAndInnerToJSONTyped(value?: SearchOrganisationsRequestWhereAndInnerAndInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': SearchDatabasesRequestWhereCreatedAtToJSON(value['createdAt']),
        'id': SearchDatabasesRequestWhereCreatedAtToJSON(value['id']),
        'name': SearchDatabasesRequestWhereCreatedAtToJSON(value['name']),
        'public': SearchDatabasesRequestWhereCreatedAtToJSON(value['_public']),
        'slug': SearchDatabasesRequestWhereCreatedAtToJSON(value['slug']),
        'updated_at': SearchDatabasesRequestWhereCreatedAtToJSON(value['updatedAt']),
    };
}

