/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Pagination options
 * @export
 * @interface SearchDatabasesRequestLimit
 */
export interface SearchDatabasesRequestLimit {
    /**
     * The maximum number of results to return
     * @type {number}
     * @memberof SearchDatabasesRequestLimit
     */
    count?: number;
    /**
     * The number of results to skip
     * @type {number}
     * @memberof SearchDatabasesRequestLimit
     */
    offset?: number;
}

/**
 * Check if a given object implements the SearchDatabasesRequestLimit interface.
 */
export function instanceOfSearchDatabasesRequestLimit(value: object): value is SearchDatabasesRequestLimit {
    return true;
}

export function SearchDatabasesRequestLimitFromJSON(json: any): SearchDatabasesRequestLimit {
    return SearchDatabasesRequestLimitFromJSONTyped(json, false);
}

export function SearchDatabasesRequestLimitFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchDatabasesRequestLimit {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'offset': json['offset'] == null ? undefined : json['offset'],
    };
}

export function SearchDatabasesRequestLimitToJSON(json: any): SearchDatabasesRequestLimit {
    return SearchDatabasesRequestLimitToJSONTyped(json, false);
}

export function SearchDatabasesRequestLimitToJSONTyped(value?: SearchDatabasesRequestLimit | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'offset': value['offset'],
    };
}

