/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SearchTokensRequestOrder } from './SearchTokensRequestOrder';
import {
    SearchTokensRequestOrderFromJSON,
    SearchTokensRequestOrderFromJSONTyped,
    SearchTokensRequestOrderToJSON,
    SearchTokensRequestOrderToJSONTyped,
} from './SearchTokensRequestOrder';
import type { SearchTokensRequestWhere } from './SearchTokensRequestWhere';
import {
    SearchTokensRequestWhereFromJSON,
    SearchTokensRequestWhereFromJSONTyped,
    SearchTokensRequestWhereToJSON,
    SearchTokensRequestWhereToJSONTyped,
} from './SearchTokensRequestWhere';
import type { SearchDatabasesRequestLimit } from './SearchDatabasesRequestLimit';
import {
    SearchDatabasesRequestLimitFromJSON,
    SearchDatabasesRequestLimitFromJSONTyped,
    SearchDatabasesRequestLimitToJSON,
    SearchDatabasesRequestLimitToJSONTyped,
} from './SearchDatabasesRequestLimit';

/**
 * 
 * @export
 * @interface SearchTokensRequest
 */
export interface SearchTokensRequest {
    /**
     * 
     * @type {SearchDatabasesRequestLimit}
     * @memberof SearchTokensRequest
     */
    limit?: SearchDatabasesRequestLimit;
    /**
     * 
     * @type {SearchTokensRequestOrder}
     * @memberof SearchTokensRequest
     */
    order?: SearchTokensRequestOrder;
    /**
     * Fields to include in the response
     * @type {Set<string>}
     * @memberof SearchTokensRequest
     */
    select?: Set<SearchTokensRequestSelectEnum>;
    /**
     * 
     * @type {SearchTokensRequestWhere}
     * @memberof SearchTokensRequest
     */
    where?: SearchTokensRequestWhere;
}


/**
 * @export
 */
export const SearchTokensRequestSelectEnum = {
    Active: 'active',
    CreatedAt: 'created_at',
    ExpiresAt: 'expires_at',
    Id: 'id',
    LastUsedAt: 'last_used_at',
    Name: 'name',
    OrganisationId: 'organisation_id',
    Scopes: 'scopes',
    UpdatedAt: 'updated_at'
} as const;
export type SearchTokensRequestSelectEnum = typeof SearchTokensRequestSelectEnum[keyof typeof SearchTokensRequestSelectEnum];


/**
 * Check if a given object implements the SearchTokensRequest interface.
 */
export function instanceOfSearchTokensRequest(value: object): value is SearchTokensRequest {
    return true;
}

export function SearchTokensRequestFromJSON(json: any): SearchTokensRequest {
    return SearchTokensRequestFromJSONTyped(json, false);
}

export function SearchTokensRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchTokensRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'limit': json['limit'] == null ? undefined : SearchDatabasesRequestLimitFromJSON(json['limit']),
        'order': json['order'] == null ? undefined : SearchTokensRequestOrderFromJSON(json['order']),
        'select': json['select'] == null ? undefined : new Set(json['select']),
        'where': json['where'] == null ? undefined : SearchTokensRequestWhereFromJSON(json['where']),
    };
}

export function SearchTokensRequestToJSON(json: any): SearchTokensRequest {
    return SearchTokensRequestToJSONTyped(json, false);
}

export function SearchTokensRequestToJSONTyped(value?: SearchTokensRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'limit': SearchDatabasesRequestLimitToJSON(value['limit']),
        'order': SearchTokensRequestOrderToJSON(value['order']),
        'select': value['select'] == null ? undefined : Array.from(value['select'] as Set<any>),
        'where': SearchTokensRequestWhereToJSON(value['where']),
    };
}

