/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SearchDatabasesRequestWhereAndInner } from './SearchDatabasesRequestWhereAndInner';
import {
    SearchDatabasesRequestWhereAndInnerFromJSON,
    SearchDatabasesRequestWhereAndInnerFromJSONTyped,
    SearchDatabasesRequestWhereAndInnerToJSON,
    SearchDatabasesRequestWhereAndInnerToJSONTyped,
} from './SearchDatabasesRequestWhereAndInner';
import type { SearchDatabasesRequestWhereCreatedAt } from './SearchDatabasesRequestWhereCreatedAt';
import {
    SearchDatabasesRequestWhereCreatedAtFromJSON,
    SearchDatabasesRequestWhereCreatedAtFromJSONTyped,
    SearchDatabasesRequestWhereCreatedAtToJSON,
    SearchDatabasesRequestWhereCreatedAtToJSONTyped,
} from './SearchDatabasesRequestWhereCreatedAt';

/**
 * 
 * @export
 * @interface SearchDatabasesRequestWhere
 */
export interface SearchDatabasesRequestWhere {
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchDatabasesRequestWhere
     */
    createdAt?: SearchDatabasesRequestWhereCreatedAt;
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchDatabasesRequestWhere
     */
    description?: SearchDatabasesRequestWhereCreatedAt;
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchDatabasesRequestWhere
     */
    id?: SearchDatabasesRequestWhereCreatedAt;
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchDatabasesRequestWhere
     */
    name?: SearchDatabasesRequestWhereCreatedAt;
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchDatabasesRequestWhere
     */
    organisationId?: SearchDatabasesRequestWhereCreatedAt;
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchDatabasesRequestWhere
     */
    _public?: SearchDatabasesRequestWhereCreatedAt;
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchDatabasesRequestWhere
     */
    slug?: SearchDatabasesRequestWhereCreatedAt;
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchDatabasesRequestWhere
     */
    updatedAt?: SearchDatabasesRequestWhereCreatedAt;
    /**
     * All conditions must match
     * @type {Array<SearchDatabasesRequestWhereAndInner>}
     * @memberof SearchDatabasesRequestWhere
     */
    and?: Array<SearchDatabasesRequestWhereAndInner>;
    /**
     * At least one condition must match
     * @type {Array<SearchDatabasesRequestWhereAndInner>}
     * @memberof SearchDatabasesRequestWhere
     */
    or?: Array<SearchDatabasesRequestWhereAndInner>;
}

/**
 * Check if a given object implements the SearchDatabasesRequestWhere interface.
 */
export function instanceOfSearchDatabasesRequestWhere(value: object): value is SearchDatabasesRequestWhere {
    return true;
}

export function SearchDatabasesRequestWhereFromJSON(json: any): SearchDatabasesRequestWhere {
    return SearchDatabasesRequestWhereFromJSONTyped(json, false);
}

export function SearchDatabasesRequestWhereFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchDatabasesRequestWhere {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['created_at']),
        'description': json['description'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['description']),
        'id': json['id'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['id']),
        'name': json['name'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['name']),
        'organisationId': json['organisation_id'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['organisation_id']),
        '_public': json['public'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['public']),
        'slug': json['slug'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['slug']),
        'updatedAt': json['updated_at'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['updated_at']),
        'and': json['and'] == null ? undefined : ((json['and'] as Array<any>).map(SearchDatabasesRequestWhereAndInnerFromJSON)),
        'or': json['or'] == null ? undefined : ((json['or'] as Array<any>).map(SearchDatabasesRequestWhereAndInnerFromJSON)),
    };
}

export function SearchDatabasesRequestWhereToJSON(json: any): SearchDatabasesRequestWhere {
    return SearchDatabasesRequestWhereToJSONTyped(json, false);
}

export function SearchDatabasesRequestWhereToJSONTyped(value?: SearchDatabasesRequestWhere | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': SearchDatabasesRequestWhereCreatedAtToJSON(value['createdAt']),
        'description': SearchDatabasesRequestWhereCreatedAtToJSON(value['description']),
        'id': SearchDatabasesRequestWhereCreatedAtToJSON(value['id']),
        'name': SearchDatabasesRequestWhereCreatedAtToJSON(value['name']),
        'organisation_id': SearchDatabasesRequestWhereCreatedAtToJSON(value['organisationId']),
        'public': SearchDatabasesRequestWhereCreatedAtToJSON(value['_public']),
        'slug': SearchDatabasesRequestWhereCreatedAtToJSON(value['slug']),
        'updated_at': SearchDatabasesRequestWhereCreatedAtToJSON(value['updatedAt']),
        'and': value['and'] == null ? undefined : ((value['and'] as Array<any>).map(SearchDatabasesRequestWhereAndInnerToJSON)),
        'or': value['or'] == null ? undefined : ((value['or'] as Array<any>).map(SearchDatabasesRequestWhereAndInnerToJSON)),
    };
}

