/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SearchUsersRequestOrder } from './SearchUsersRequestOrder';
import {
    SearchUsersRequestOrderFromJSON,
    SearchUsersRequestOrderFromJSONTyped,
    SearchUsersRequestOrderToJSON,
    SearchUsersRequestOrderToJSONTyped,
} from './SearchUsersRequestOrder';
import type { SearchDatabasesRequestLimit } from './SearchDatabasesRequestLimit';
import {
    SearchDatabasesRequestLimitFromJSON,
    SearchDatabasesRequestLimitFromJSONTyped,
    SearchDatabasesRequestLimitToJSON,
    SearchDatabasesRequestLimitToJSONTyped,
} from './SearchDatabasesRequestLimit';
import type { SearchUsersRequestWhere } from './SearchUsersRequestWhere';
import {
    SearchUsersRequestWhereFromJSON,
    SearchUsersRequestWhereFromJSONTyped,
    SearchUsersRequestWhereToJSON,
    SearchUsersRequestWhereToJSONTyped,
} from './SearchUsersRequestWhere';

/**
 * 
 * @export
 * @interface SearchUsersRequest
 */
export interface SearchUsersRequest {
    /**
     * 
     * @type {SearchDatabasesRequestLimit}
     * @memberof SearchUsersRequest
     */
    limit?: SearchDatabasesRequestLimit;
    /**
     * 
     * @type {SearchUsersRequestOrder}
     * @memberof SearchUsersRequest
     */
    order?: SearchUsersRequestOrder;
    /**
     * Fields to include in the response
     * @type {Set<string>}
     * @memberof SearchUsersRequest
     */
    select?: Set<SearchUsersRequestSelectEnum>;
    /**
     * 
     * @type {SearchUsersRequestWhere}
     * @memberof SearchUsersRequest
     */
    where?: SearchUsersRequestWhere;
}


/**
 * @export
 */
export const SearchUsersRequestSelectEnum = {
    CreatedAt: 'created_at',
    Handle: 'handle',
    Id: 'id',
    PublicEmail: 'public_email',
    PublicName: 'public_name',
    UpdatedAt: 'updated_at'
} as const;
export type SearchUsersRequestSelectEnum = typeof SearchUsersRequestSelectEnum[keyof typeof SearchUsersRequestSelectEnum];


/**
 * Check if a given object implements the SearchUsersRequest interface.
 */
export function instanceOfSearchUsersRequest(value: object): value is SearchUsersRequest {
    return true;
}

export function SearchUsersRequestFromJSON(json: any): SearchUsersRequest {
    return SearchUsersRequestFromJSONTyped(json, false);
}

export function SearchUsersRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchUsersRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'limit': json['limit'] == null ? undefined : SearchDatabasesRequestLimitFromJSON(json['limit']),
        'order': json['order'] == null ? undefined : SearchUsersRequestOrderFromJSON(json['order']),
        'select': json['select'] == null ? undefined : new Set(json['select']),
        'where': json['where'] == null ? undefined : SearchUsersRequestWhereFromJSON(json['where']),
    };
}

export function SearchUsersRequestToJSON(json: any): SearchUsersRequest {
    return SearchUsersRequestToJSONTyped(json, false);
}

export function SearchUsersRequestToJSONTyped(value?: SearchUsersRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'limit': SearchDatabasesRequestLimitToJSON(value['limit']),
        'order': SearchUsersRequestOrderToJSON(value['order']),
        'select': value['select'] == null ? undefined : Array.from(value['select'] as Set<any>),
        'where': SearchUsersRequestWhereToJSON(value['where']),
    };
}

