/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Sort results by one or more fields
 * @export
 * @interface SearchDatabasesRequestOrder
 */
export interface SearchDatabasesRequestOrder {
    /**
     * 
     * @type {string}
     * @memberof SearchDatabasesRequestOrder
     */
    createdAt?: SearchDatabasesRequestOrderCreatedAtEnum;
    /**
     * 
     * @type {string}
     * @memberof SearchDatabasesRequestOrder
     */
    description?: SearchDatabasesRequestOrderDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof SearchDatabasesRequestOrder
     */
    id?: SearchDatabasesRequestOrderIdEnum;
    /**
     * 
     * @type {string}
     * @memberof SearchDatabasesRequestOrder
     */
    name?: SearchDatabasesRequestOrderNameEnum;
    /**
     * 
     * @type {string}
     * @memberof SearchDatabasesRequestOrder
     */
    organisationId?: SearchDatabasesRequestOrderOrganisationIdEnum;
    /**
     * 
     * @type {string}
     * @memberof SearchDatabasesRequestOrder
     */
    _public?: SearchDatabasesRequestOrderPublicEnum;
    /**
     * 
     * @type {string}
     * @memberof SearchDatabasesRequestOrder
     */
    slug?: SearchDatabasesRequestOrderSlugEnum;
    /**
     * 
     * @type {string}
     * @memberof SearchDatabasesRequestOrder
     */
    updatedAt?: SearchDatabasesRequestOrderUpdatedAtEnum;
}


/**
 * @export
 */
export const SearchDatabasesRequestOrderCreatedAtEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type SearchDatabasesRequestOrderCreatedAtEnum = typeof SearchDatabasesRequestOrderCreatedAtEnum[keyof typeof SearchDatabasesRequestOrderCreatedAtEnum];

/**
 * @export
 */
export const SearchDatabasesRequestOrderDescriptionEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type SearchDatabasesRequestOrderDescriptionEnum = typeof SearchDatabasesRequestOrderDescriptionEnum[keyof typeof SearchDatabasesRequestOrderDescriptionEnum];

/**
 * @export
 */
export const SearchDatabasesRequestOrderIdEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type SearchDatabasesRequestOrderIdEnum = typeof SearchDatabasesRequestOrderIdEnum[keyof typeof SearchDatabasesRequestOrderIdEnum];

/**
 * @export
 */
export const SearchDatabasesRequestOrderNameEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type SearchDatabasesRequestOrderNameEnum = typeof SearchDatabasesRequestOrderNameEnum[keyof typeof SearchDatabasesRequestOrderNameEnum];

/**
 * @export
 */
export const SearchDatabasesRequestOrderOrganisationIdEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type SearchDatabasesRequestOrderOrganisationIdEnum = typeof SearchDatabasesRequestOrderOrganisationIdEnum[keyof typeof SearchDatabasesRequestOrderOrganisationIdEnum];

/**
 * @export
 */
export const SearchDatabasesRequestOrderPublicEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type SearchDatabasesRequestOrderPublicEnum = typeof SearchDatabasesRequestOrderPublicEnum[keyof typeof SearchDatabasesRequestOrderPublicEnum];

/**
 * @export
 */
export const SearchDatabasesRequestOrderSlugEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type SearchDatabasesRequestOrderSlugEnum = typeof SearchDatabasesRequestOrderSlugEnum[keyof typeof SearchDatabasesRequestOrderSlugEnum];

/**
 * @export
 */
export const SearchDatabasesRequestOrderUpdatedAtEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type SearchDatabasesRequestOrderUpdatedAtEnum = typeof SearchDatabasesRequestOrderUpdatedAtEnum[keyof typeof SearchDatabasesRequestOrderUpdatedAtEnum];


/**
 * Check if a given object implements the SearchDatabasesRequestOrder interface.
 */
export function instanceOfSearchDatabasesRequestOrder(value: object): value is SearchDatabasesRequestOrder {
    return true;
}

export function SearchDatabasesRequestOrderFromJSON(json: any): SearchDatabasesRequestOrder {
    return SearchDatabasesRequestOrderFromJSONTyped(json, false);
}

export function SearchDatabasesRequestOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchDatabasesRequestOrder {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'organisationId': json['organisation_id'] == null ? undefined : json['organisation_id'],
        '_public': json['public'] == null ? undefined : json['public'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

export function SearchDatabasesRequestOrderToJSON(json: any): SearchDatabasesRequestOrder {
    return SearchDatabasesRequestOrderToJSONTyped(json, false);
}

export function SearchDatabasesRequestOrderToJSONTyped(value?: SearchDatabasesRequestOrder | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'],
        'description': value['description'],
        'id': value['id'],
        'name': value['name'],
        'organisation_id': value['organisationId'],
        'public': value['_public'],
        'slug': value['slug'],
        'updated_at': value['updatedAt'],
    };
}

