/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SearchDatabasesRequestWhereAndInnerAndInner } from './SearchDatabasesRequestWhereAndInnerAndInner';
import {
    SearchDatabasesRequestWhereAndInnerAndInnerFromJSON,
    SearchDatabasesRequestWhereAndInnerAndInnerFromJSONTyped,
    SearchDatabasesRequestWhereAndInnerAndInnerToJSON,
    SearchDatabasesRequestWhereAndInnerAndInnerToJSONTyped,
} from './SearchDatabasesRequestWhereAndInnerAndInner';
import type { SearchDatabasesRequestWhereCreatedAt } from './SearchDatabasesRequestWhereCreatedAt';
import {
    SearchDatabasesRequestWhereCreatedAtFromJSON,
    SearchDatabasesRequestWhereCreatedAtFromJSONTyped,
    SearchDatabasesRequestWhereCreatedAtToJSON,
    SearchDatabasesRequestWhereCreatedAtToJSONTyped,
} from './SearchDatabasesRequestWhereCreatedAt';

/**
 * 
 * @export
 * @interface SearchDatabasesRequestWhereAndInner
 */
export interface SearchDatabasesRequestWhereAndInner {
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchDatabasesRequestWhereAndInner
     */
    createdAt?: SearchDatabasesRequestWhereCreatedAt;
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchDatabasesRequestWhereAndInner
     */
    description?: SearchDatabasesRequestWhereCreatedAt;
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchDatabasesRequestWhereAndInner
     */
    id?: SearchDatabasesRequestWhereCreatedAt;
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchDatabasesRequestWhereAndInner
     */
    name?: SearchDatabasesRequestWhereCreatedAt;
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchDatabasesRequestWhereAndInner
     */
    organisationId?: SearchDatabasesRequestWhereCreatedAt;
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchDatabasesRequestWhereAndInner
     */
    _public?: SearchDatabasesRequestWhereCreatedAt;
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchDatabasesRequestWhereAndInner
     */
    slug?: SearchDatabasesRequestWhereCreatedAt;
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchDatabasesRequestWhereAndInner
     */
    updatedAt?: SearchDatabasesRequestWhereCreatedAt;
    /**
     * All conditions must match
     * @type {Array<SearchDatabasesRequestWhereAndInnerAndInner>}
     * @memberof SearchDatabasesRequestWhereAndInner
     */
    and?: Array<SearchDatabasesRequestWhereAndInnerAndInner>;
    /**
     * At least one condition must match
     * @type {Array<SearchDatabasesRequestWhereAndInnerAndInner>}
     * @memberof SearchDatabasesRequestWhereAndInner
     */
    or?: Array<SearchDatabasesRequestWhereAndInnerAndInner>;
}

/**
 * Check if a given object implements the SearchDatabasesRequestWhereAndInner interface.
 */
export function instanceOfSearchDatabasesRequestWhereAndInner(value: object): value is SearchDatabasesRequestWhereAndInner {
    return true;
}

export function SearchDatabasesRequestWhereAndInnerFromJSON(json: any): SearchDatabasesRequestWhereAndInner {
    return SearchDatabasesRequestWhereAndInnerFromJSONTyped(json, false);
}

export function SearchDatabasesRequestWhereAndInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchDatabasesRequestWhereAndInner {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['created_at']),
        'description': json['description'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['description']),
        'id': json['id'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['id']),
        'name': json['name'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['name']),
        'organisationId': json['organisation_id'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['organisation_id']),
        '_public': json['public'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['public']),
        'slug': json['slug'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['slug']),
        'updatedAt': json['updated_at'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['updated_at']),
        'and': json['and'] == null ? undefined : ((json['and'] as Array<any>).map(SearchDatabasesRequestWhereAndInnerAndInnerFromJSON)),
        'or': json['or'] == null ? undefined : ((json['or'] as Array<any>).map(SearchDatabasesRequestWhereAndInnerAndInnerFromJSON)),
    };
}

export function SearchDatabasesRequestWhereAndInnerToJSON(json: any): SearchDatabasesRequestWhereAndInner {
    return SearchDatabasesRequestWhereAndInnerToJSONTyped(json, false);
}

export function SearchDatabasesRequestWhereAndInnerToJSONTyped(value?: SearchDatabasesRequestWhereAndInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': SearchDatabasesRequestWhereCreatedAtToJSON(value['createdAt']),
        'description': SearchDatabasesRequestWhereCreatedAtToJSON(value['description']),
        'id': SearchDatabasesRequestWhereCreatedAtToJSON(value['id']),
        'name': SearchDatabasesRequestWhereCreatedAtToJSON(value['name']),
        'organisation_id': SearchDatabasesRequestWhereCreatedAtToJSON(value['organisationId']),
        'public': SearchDatabasesRequestWhereCreatedAtToJSON(value['_public']),
        'slug': SearchDatabasesRequestWhereCreatedAtToJSON(value['slug']),
        'updated_at': SearchDatabasesRequestWhereCreatedAtToJSON(value['updatedAt']),
        'and': value['and'] == null ? undefined : ((value['and'] as Array<any>).map(SearchDatabasesRequestWhereAndInnerAndInnerToJSON)),
        'or': value['or'] == null ? undefined : ((value['or'] as Array<any>).map(SearchDatabasesRequestWhereAndInnerAndInnerToJSON)),
    };
}

