/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SearchDatabasesRequestWhereCreatedAt } from './SearchDatabasesRequestWhereCreatedAt';
import {
    SearchDatabasesRequestWhereCreatedAtFromJSON,
    SearchDatabasesRequestWhereCreatedAtFromJSONTyped,
    SearchDatabasesRequestWhereCreatedAtToJSON,
    SearchDatabasesRequestWhereCreatedAtToJSONTyped,
} from './SearchDatabasesRequestWhereCreatedAt';

/**
 * 
 * @export
 * @interface SearchResourcesRequestWhereAndInnerAndInner
 */
export interface SearchResourcesRequestWhereAndInnerAndInner {
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchResourcesRequestWhereAndInnerAndInner
     */
    config?: SearchDatabasesRequestWhereCreatedAt;
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchResourcesRequestWhereAndInnerAndInner
     */
    createdAt?: SearchDatabasesRequestWhereCreatedAt;
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchResourcesRequestWhereAndInnerAndInner
     */
    id?: SearchDatabasesRequestWhereCreatedAt;
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchResourcesRequestWhereAndInnerAndInner
     */
    name?: SearchDatabasesRequestWhereCreatedAt;
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchResourcesRequestWhereAndInnerAndInner
     */
    organisationId?: SearchDatabasesRequestWhereCreatedAt;
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchResourcesRequestWhereAndInnerAndInner
     */
    type?: SearchDatabasesRequestWhereCreatedAt;
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchResourcesRequestWhereAndInnerAndInner
     */
    updatedAt?: SearchDatabasesRequestWhereCreatedAt;
}

/**
 * Check if a given object implements the SearchResourcesRequestWhereAndInnerAndInner interface.
 */
export function instanceOfSearchResourcesRequestWhereAndInnerAndInner(value: object): value is SearchResourcesRequestWhereAndInnerAndInner {
    return true;
}

export function SearchResourcesRequestWhereAndInnerAndInnerFromJSON(json: any): SearchResourcesRequestWhereAndInnerAndInner {
    return SearchResourcesRequestWhereAndInnerAndInnerFromJSONTyped(json, false);
}

export function SearchResourcesRequestWhereAndInnerAndInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchResourcesRequestWhereAndInnerAndInner {
    if (json == null) {
        return json;
    }
    return {
        
        'config': json['config'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['config']),
        'createdAt': json['created_at'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['created_at']),
        'id': json['id'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['id']),
        'name': json['name'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['name']),
        'organisationId': json['organisation_id'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['organisation_id']),
        'type': json['type'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['type']),
        'updatedAt': json['updated_at'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['updated_at']),
    };
}

export function SearchResourcesRequestWhereAndInnerAndInnerToJSON(json: any): SearchResourcesRequestWhereAndInnerAndInner {
    return SearchResourcesRequestWhereAndInnerAndInnerToJSONTyped(json, false);
}

export function SearchResourcesRequestWhereAndInnerAndInnerToJSONTyped(value?: SearchResourcesRequestWhereAndInnerAndInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'config': SearchDatabasesRequestWhereCreatedAtToJSON(value['config']),
        'created_at': SearchDatabasesRequestWhereCreatedAtToJSON(value['createdAt']),
        'id': SearchDatabasesRequestWhereCreatedAtToJSON(value['id']),
        'name': SearchDatabasesRequestWhereCreatedAtToJSON(value['name']),
        'organisation_id': SearchDatabasesRequestWhereCreatedAtToJSON(value['organisationId']),
        'type': SearchDatabasesRequestWhereCreatedAtToJSON(value['type']),
        'updated_at': SearchDatabasesRequestWhereCreatedAtToJSON(value['updatedAt']),
    };
}

