/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SearchDatabasesRequestWhereCreatedAt } from './SearchDatabasesRequestWhereCreatedAt';
import {
    SearchDatabasesRequestWhereCreatedAtFromJSON,
    SearchDatabasesRequestWhereCreatedAtFromJSONTyped,
    SearchDatabasesRequestWhereCreatedAtToJSON,
    SearchDatabasesRequestWhereCreatedAtToJSONTyped,
} from './SearchDatabasesRequestWhereCreatedAt';

/**
 * 
 * @export
 * @interface SearchTokensRequestWhereAndInnerAndInner
 */
export interface SearchTokensRequestWhereAndInnerAndInner {
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchTokensRequestWhereAndInnerAndInner
     */
    active?: SearchDatabasesRequestWhereCreatedAt;
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchTokensRequestWhereAndInnerAndInner
     */
    createdAt?: SearchDatabasesRequestWhereCreatedAt;
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchTokensRequestWhereAndInnerAndInner
     */
    expiresAt?: SearchDatabasesRequestWhereCreatedAt;
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchTokensRequestWhereAndInnerAndInner
     */
    id?: SearchDatabasesRequestWhereCreatedAt;
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchTokensRequestWhereAndInnerAndInner
     */
    lastUsedAt?: SearchDatabasesRequestWhereCreatedAt;
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchTokensRequestWhereAndInnerAndInner
     */
    name?: SearchDatabasesRequestWhereCreatedAt;
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchTokensRequestWhereAndInnerAndInner
     */
    organisationId?: SearchDatabasesRequestWhereCreatedAt;
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchTokensRequestWhereAndInnerAndInner
     */
    scopes?: SearchDatabasesRequestWhereCreatedAt;
    /**
     * 
     * @type {SearchDatabasesRequestWhereCreatedAt}
     * @memberof SearchTokensRequestWhereAndInnerAndInner
     */
    updatedAt?: SearchDatabasesRequestWhereCreatedAt;
}

/**
 * Check if a given object implements the SearchTokensRequestWhereAndInnerAndInner interface.
 */
export function instanceOfSearchTokensRequestWhereAndInnerAndInner(value: object): value is SearchTokensRequestWhereAndInnerAndInner {
    return true;
}

export function SearchTokensRequestWhereAndInnerAndInnerFromJSON(json: any): SearchTokensRequestWhereAndInnerAndInner {
    return SearchTokensRequestWhereAndInnerAndInnerFromJSONTyped(json, false);
}

export function SearchTokensRequestWhereAndInnerAndInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchTokensRequestWhereAndInnerAndInner {
    if (json == null) {
        return json;
    }
    return {
        
        'active': json['active'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['active']),
        'createdAt': json['created_at'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['created_at']),
        'expiresAt': json['expires_at'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['expires_at']),
        'id': json['id'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['id']),
        'lastUsedAt': json['last_used_at'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['last_used_at']),
        'name': json['name'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['name']),
        'organisationId': json['organisation_id'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['organisation_id']),
        'scopes': json['scopes'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['scopes']),
        'updatedAt': json['updated_at'] == null ? undefined : SearchDatabasesRequestWhereCreatedAtFromJSON(json['updated_at']),
    };
}

export function SearchTokensRequestWhereAndInnerAndInnerToJSON(json: any): SearchTokensRequestWhereAndInnerAndInner {
    return SearchTokensRequestWhereAndInnerAndInnerToJSONTyped(json, false);
}

export function SearchTokensRequestWhereAndInnerAndInnerToJSONTyped(value?: SearchTokensRequestWhereAndInnerAndInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'active': SearchDatabasesRequestWhereCreatedAtToJSON(value['active']),
        'created_at': SearchDatabasesRequestWhereCreatedAtToJSON(value['createdAt']),
        'expires_at': SearchDatabasesRequestWhereCreatedAtToJSON(value['expiresAt']),
        'id': SearchDatabasesRequestWhereCreatedAtToJSON(value['id']),
        'last_used_at': SearchDatabasesRequestWhereCreatedAtToJSON(value['lastUsedAt']),
        'name': SearchDatabasesRequestWhereCreatedAtToJSON(value['name']),
        'organisation_id': SearchDatabasesRequestWhereCreatedAtToJSON(value['organisationId']),
        'scopes': SearchDatabasesRequestWhereCreatedAtToJSON(value['scopes']),
        'updated_at': SearchDatabasesRequestWhereCreatedAtToJSON(value['updatedAt']),
    };
}

