/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Sort results by one or more fields
 * @export
 * @interface SearchTokensRequestOrder
 */
export interface SearchTokensRequestOrder {
    /**
     * 
     * @type {string}
     * @memberof SearchTokensRequestOrder
     */
    active?: SearchTokensRequestOrderActiveEnum;
    /**
     * 
     * @type {string}
     * @memberof SearchTokensRequestOrder
     */
    createdAt?: SearchTokensRequestOrderCreatedAtEnum;
    /**
     * 
     * @type {string}
     * @memberof SearchTokensRequestOrder
     */
    expiresAt?: SearchTokensRequestOrderExpiresAtEnum;
    /**
     * 
     * @type {string}
     * @memberof SearchTokensRequestOrder
     */
    id?: SearchTokensRequestOrderIdEnum;
    /**
     * 
     * @type {string}
     * @memberof SearchTokensRequestOrder
     */
    lastUsedAt?: SearchTokensRequestOrderLastUsedAtEnum;
    /**
     * 
     * @type {string}
     * @memberof SearchTokensRequestOrder
     */
    name?: SearchTokensRequestOrderNameEnum;
    /**
     * 
     * @type {string}
     * @memberof SearchTokensRequestOrder
     */
    organisationId?: SearchTokensRequestOrderOrganisationIdEnum;
    /**
     * 
     * @type {string}
     * @memberof SearchTokensRequestOrder
     */
    scopes?: SearchTokensRequestOrderScopesEnum;
    /**
     * 
     * @type {string}
     * @memberof SearchTokensRequestOrder
     */
    updatedAt?: SearchTokensRequestOrderUpdatedAtEnum;
}


/**
 * @export
 */
export const SearchTokensRequestOrderActiveEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type SearchTokensRequestOrderActiveEnum = typeof SearchTokensRequestOrderActiveEnum[keyof typeof SearchTokensRequestOrderActiveEnum];

/**
 * @export
 */
export const SearchTokensRequestOrderCreatedAtEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type SearchTokensRequestOrderCreatedAtEnum = typeof SearchTokensRequestOrderCreatedAtEnum[keyof typeof SearchTokensRequestOrderCreatedAtEnum];

/**
 * @export
 */
export const SearchTokensRequestOrderExpiresAtEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type SearchTokensRequestOrderExpiresAtEnum = typeof SearchTokensRequestOrderExpiresAtEnum[keyof typeof SearchTokensRequestOrderExpiresAtEnum];

/**
 * @export
 */
export const SearchTokensRequestOrderIdEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type SearchTokensRequestOrderIdEnum = typeof SearchTokensRequestOrderIdEnum[keyof typeof SearchTokensRequestOrderIdEnum];

/**
 * @export
 */
export const SearchTokensRequestOrderLastUsedAtEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type SearchTokensRequestOrderLastUsedAtEnum = typeof SearchTokensRequestOrderLastUsedAtEnum[keyof typeof SearchTokensRequestOrderLastUsedAtEnum];

/**
 * @export
 */
export const SearchTokensRequestOrderNameEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type SearchTokensRequestOrderNameEnum = typeof SearchTokensRequestOrderNameEnum[keyof typeof SearchTokensRequestOrderNameEnum];

/**
 * @export
 */
export const SearchTokensRequestOrderOrganisationIdEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type SearchTokensRequestOrderOrganisationIdEnum = typeof SearchTokensRequestOrderOrganisationIdEnum[keyof typeof SearchTokensRequestOrderOrganisationIdEnum];

/**
 * @export
 */
export const SearchTokensRequestOrderScopesEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type SearchTokensRequestOrderScopesEnum = typeof SearchTokensRequestOrderScopesEnum[keyof typeof SearchTokensRequestOrderScopesEnum];

/**
 * @export
 */
export const SearchTokensRequestOrderUpdatedAtEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type SearchTokensRequestOrderUpdatedAtEnum = typeof SearchTokensRequestOrderUpdatedAtEnum[keyof typeof SearchTokensRequestOrderUpdatedAtEnum];


/**
 * Check if a given object implements the SearchTokensRequestOrder interface.
 */
export function instanceOfSearchTokensRequestOrder(value: object): value is SearchTokensRequestOrder {
    return true;
}

export function SearchTokensRequestOrderFromJSON(json: any): SearchTokensRequestOrder {
    return SearchTokensRequestOrderFromJSONTyped(json, false);
}

export function SearchTokensRequestOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchTokensRequestOrder {
    if (json == null) {
        return json;
    }
    return {
        
        'active': json['active'] == null ? undefined : json['active'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'expiresAt': json['expires_at'] == null ? undefined : json['expires_at'],
        'id': json['id'] == null ? undefined : json['id'],
        'lastUsedAt': json['last_used_at'] == null ? undefined : json['last_used_at'],
        'name': json['name'] == null ? undefined : json['name'],
        'organisationId': json['organisation_id'] == null ? undefined : json['organisation_id'],
        'scopes': json['scopes'] == null ? undefined : json['scopes'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

export function SearchTokensRequestOrderToJSON(json: any): SearchTokensRequestOrder {
    return SearchTokensRequestOrderToJSONTyped(json, false);
}

export function SearchTokensRequestOrderToJSONTyped(value?: SearchTokensRequestOrder | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'active': value['active'],
        'created_at': value['createdAt'],
        'expires_at': value['expiresAt'],
        'id': value['id'],
        'last_used_at': value['lastUsedAt'],
        'name': value['name'],
        'organisation_id': value['organisationId'],
        'scopes': value['scopes'],
        'updated_at': value['updatedAt'],
    };
}

