/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateDatabaseRequest
 */
export interface UpdateDatabaseRequest {
    /**
     * A description of the database
     * @type {string}
     * @memberof UpdateDatabaseRequest
     */
    description?: string;
    /**
     * The display name of the database
     * @type {string}
     * @memberof UpdateDatabaseRequest
     */
    name?: string;
    /**
     * Whether this database is publicly visible to other organisations
     * @type {boolean}
     * @memberof UpdateDatabaseRequest
     */
    _public?: boolean;
    /**
     * The URL-friendly identifier of the database
     * @type {string}
     * @memberof UpdateDatabaseRequest
     */
    slug?: string;
}

/**
 * Check if a given object implements the UpdateDatabaseRequest interface.
 */
export function instanceOfUpdateDatabaseRequest(value: object): value is UpdateDatabaseRequest {
    return true;
}

export function UpdateDatabaseRequestFromJSON(json: any): UpdateDatabaseRequest {
    return UpdateDatabaseRequestFromJSONTyped(json, false);
}

export function UpdateDatabaseRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateDatabaseRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'name': json['name'] == null ? undefined : json['name'],
        '_public': json['public'] == null ? undefined : json['public'],
        'slug': json['slug'] == null ? undefined : json['slug'],
    };
}

export function UpdateDatabaseRequestToJSON(json: any): UpdateDatabaseRequest {
    return UpdateDatabaseRequestToJSONTyped(json, false);
}

export function UpdateDatabaseRequestToJSONTyped(value?: UpdateDatabaseRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'name': value['name'],
        'public': value['_public'],
        'slug': value['slug'],
    };
}

