/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateTokenRequest
 */
export interface UpdateTokenRequest {
    /**
     * Whether the token is usable
     * @type {boolean}
     * @memberof UpdateTokenRequest
     */
    active?: boolean;
    /**
     * The display name of the token
     * @type {string}
     * @memberof UpdateTokenRequest
     */
    name?: string;
    /**
     * Permission scopes granted to this token
     * @type {Array<string>}
     * @memberof UpdateTokenRequest
     */
    scopes?: Array<string>;
}

/**
 * Check if a given object implements the UpdateTokenRequest interface.
 */
export function instanceOfUpdateTokenRequest(value: object): value is UpdateTokenRequest {
    return true;
}

export function UpdateTokenRequestFromJSON(json: any): UpdateTokenRequest {
    return UpdateTokenRequestFromJSONTyped(json, false);
}

export function UpdateTokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTokenRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'active': json['active'] == null ? undefined : json['active'],
        'name': json['name'] == null ? undefined : json['name'],
        'scopes': json['scopes'] == null ? undefined : json['scopes'],
    };
}

export function UpdateTokenRequestToJSON(json: any): UpdateTokenRequest {
    return UpdateTokenRequestToJSONTyped(json, false);
}

export function UpdateTokenRequestToJSONTyped(value?: UpdateTokenRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'active': value['active'],
        'name': value['name'],
        'scopes': value['scopes'],
    };
}

