/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateResourceRequest
 */
export interface UpdateResourceRequest {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof UpdateResourceRequest
     */
    config?: { [key: string]: any; };
    /**
     * The display name of the resource
     * @type {string}
     * @memberof UpdateResourceRequest
     */
    name?: string;
    /**
     * The resource type
     * @type {string}
     * @memberof UpdateResourceRequest
     */
    type?: UpdateResourceRequestTypeEnum;
}


/**
 * @export
 */
export const UpdateResourceRequestTypeEnum = {
    Postgres: 'postgres',
    S3: 's3',
    Smtp: 'smtp'
} as const;
export type UpdateResourceRequestTypeEnum = typeof UpdateResourceRequestTypeEnum[keyof typeof UpdateResourceRequestTypeEnum];


/**
 * Check if a given object implements the UpdateResourceRequest interface.
 */
export function instanceOfUpdateResourceRequest(value: object): value is UpdateResourceRequest {
    return true;
}

export function UpdateResourceRequestFromJSON(json: any): UpdateResourceRequest {
    return UpdateResourceRequestFromJSONTyped(json, false);
}

export function UpdateResourceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateResourceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'config': json['config'] == null ? undefined : json['config'],
        'name': json['name'] == null ? undefined : json['name'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function UpdateResourceRequestToJSON(json: any): UpdateResourceRequest {
    return UpdateResourceRequestToJSONTyped(json, false);
}

export function UpdateResourceRequestToJSONTyped(value?: UpdateResourceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'config': value['config'],
        'name': value['name'],
        'type': value['type'],
    };
}

