/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyLoginCode202Response
 */
export interface VerifyLoginCode202Response {
    /**
     * A temporary token to complete MFA verification via /auth/mfa/challenge
     * @type {string}
     * @memberof VerifyLoginCode202Response
     */
    mfaToken: string;
}

/**
 * Check if a given object implements the VerifyLoginCode202Response interface.
 */
export function instanceOfVerifyLoginCode202Response(value: object): value is VerifyLoginCode202Response {
    if (!('mfaToken' in value) || value['mfaToken'] === undefined) return false;
    return true;
}

export function VerifyLoginCode202ResponseFromJSON(json: any): VerifyLoginCode202Response {
    return VerifyLoginCode202ResponseFromJSONTyped(json, false);
}

export function VerifyLoginCode202ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyLoginCode202Response {
    if (json == null) {
        return json;
    }
    return {
        
        'mfaToken': json['mfaToken'],
    };
}

export function VerifyLoginCode202ResponseToJSON(json: any): VerifyLoginCode202Response {
    return VerifyLoginCode202ResponseToJSONTyped(json, false);
}

export function VerifyLoginCode202ResponseToJSONTyped(value?: VerifyLoginCode202Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mfaToken': value['mfaToken'],
    };
}

