/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyRegistrationRequest
 */
export interface VerifyRegistrationRequest {
    /**
     * The 6-digit verification code sent via email
     * @type {string}
     * @memberof VerifyRegistrationRequest
     */
    code: string;
    /**
     * The email address of the user
     * @type {string}
     * @memberof VerifyRegistrationRequest
     */
    email: string;
}

/**
 * Check if a given object implements the VerifyRegistrationRequest interface.
 */
export function instanceOfVerifyRegistrationRequest(value: object): value is VerifyRegistrationRequest {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function VerifyRegistrationRequestFromJSON(json: any): VerifyRegistrationRequest {
    return VerifyRegistrationRequestFromJSONTyped(json, false);
}

export function VerifyRegistrationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyRegistrationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'email': json['email'],
    };
}

export function VerifyRegistrationRequestToJSON(json: any): VerifyRegistrationRequest {
    return VerifyRegistrationRequestToJSONTyped(json, false);
}

export function VerifyRegistrationRequestToJSONTyped(value?: VerifyRegistrationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'email': value['email'],
    };
}

