/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyMfaSetupRequest
 */
export interface VerifyMfaSetupRequest {
    /**
     * A 6-digit TOTP code from the authenticator app
     * @type {string}
     * @memberof VerifyMfaSetupRequest
     */
    code: string;
}

/**
 * Check if a given object implements the VerifyMfaSetupRequest interface.
 */
export function instanceOfVerifyMfaSetupRequest(value: object): value is VerifyMfaSetupRequest {
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function VerifyMfaSetupRequestFromJSON(json: any): VerifyMfaSetupRequest {
    return VerifyMfaSetupRequestFromJSONTyped(json, false);
}

export function VerifyMfaSetupRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyMfaSetupRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
    };
}

export function VerifyMfaSetupRequestToJSON(json: any): VerifyMfaSetupRequest {
    return VerifyMfaSetupRequestToJSONTyped(json, false);
}

export function VerifyMfaSetupRequestToJSONTyped(value?: VerifyMfaSetupRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
    };
}

