/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyRegistration200Response
 */
export interface VerifyRegistration200Response {
    /**
     * The unique identifier of the verified user
     * @type {string}
     * @memberof VerifyRegistration200Response
     */
    id: string;
    /**
     * The organisation the user is logged into
     * @type {string}
     * @memberof VerifyRegistration200Response
     */
    organisationId: string;
}

/**
 * Check if a given object implements the VerifyRegistration200Response interface.
 */
export function instanceOfVerifyRegistration200Response(value: object): value is VerifyRegistration200Response {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('organisationId' in value) || value['organisationId'] === undefined) return false;
    return true;
}

export function VerifyRegistration200ResponseFromJSON(json: any): VerifyRegistration200Response {
    return VerifyRegistration200ResponseFromJSONTyped(json, false);
}

export function VerifyRegistration200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyRegistration200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'organisationId': json['organisationId'],
    };
}

export function VerifyRegistration200ResponseToJSON(json: any): VerifyRegistration200Response {
    return VerifyRegistration200ResponseToJSONTyped(json, false);
}

export function VerifyRegistration200ResponseToJSONTyped(value?: VerifyRegistration200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'organisationId': value['organisationId'],
    };
}

